---
permalink: online-help/concept-how-storage-qos-can-control-workload-throughput.html 
sidebar: sidebar 
keywords:  
summary: '您可以创建或编辑服务质量\(QoS\)策略组、以控制其所含工作负载的每秒I/O数(IOPS\)或吞吐量\(MBps\)限制。如果工作负载位于没有设置限制的策略组中，例如默认策略组，或者设置的限制不符合您的需求，您可以增加此限制或将工作负载移动到具有所需限制的新策略组或现有策略组。' 
---
= 存储 QoS 如何控制工作负载吞吐量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建或编辑服务质量(QoS)策略组、以控制其所含工作负载的每秒I/O数(IOPS)或吞吐量(MBps)限制。如果工作负载位于没有设置限制的策略组中，例如默认策略组，或者设置的限制不符合您的需求，您可以增加此限制或将工作负载移动到具有所需限制的新策略组或现有策略组。

可以将"tandard `s`"QoS策略组分配给单个工作负载、例如单个卷或LUN。在这种情况下，工作负载可以使用完整吞吐量限制。此外、还可以将QoS策略组分配给多个工作负载；在这种情况下、工作负载之间将共享吞吐量限制。例如，如果为三个工作负载分配的 QoS 限制为 9 ， 000 IOPS ，则合并 IOPS 将限制为超过 9 ， 000 IOPS 。

也可以将 "`自适应` "QoS 策略组分配给单个或多个工作负载。但是，即使分配给多个工作负载，每个工作负载也会获得完整的吞吐量限制，而不是与其他工作负载共享吞吐量值。此外，自适应 QoS 策略会根据卷大小为每个工作负载自动调整吞吐量设置，从而在卷大小发生变化时保持 IOPS 与 TB 数的比率。例如、如果自适应QoS策略中的峰值设置为5、000 IOPS/TB、则10 TB卷的吞吐量上限为50、000 IOPS。如果卷的大小稍后调整为20 TB、则自适应QoS会将上限调整为100、000 IOPS。

从 ONTAP 9.5 开始，您可以在定义自适应 QoS 策略时包括块大小。如果工作负载使用的块大小非常大、最终使用的吞吐量百分比非常大、则此功能可以有效地将此策略从IOPS/TB阈值转换为MBps阈值。

对于共享组QoS策略、如果策略组中所有工作负载的IOPS或MBps超过设置的限制、则策略组会限制工作负载以限制其活动、从而降低策略组中所有工作负载的性能。如果策略组限制生成动态性能事件、则事件问题描述 将显示相关策略组的名称。

在"性能/卷"清单页面中、您可以按IOPS和MBps对受影响的卷进行排序、以查看哪些工作负载的使用率可能会导致事件发生。在"性能/卷资源管理器"页面中、您可以选择其他卷或LUN以与受影响的工作负载IOPS或MBps吞吐量使用量进行比较。

通过将过度使用节点资源的工作负载分配给限制性更强的策略组设置，策略组会限制工作负载以限制其活动，从而减少该节点上资源的使用。但是，如果您希望工作负载能够使用更多节点资源，则可以增加策略组的值。

您可以使用 System Manager 或 ONTAP 命令管理策略组，包括以下任务：

* 创建策略组
* 在策略组中添加或删除工作负载
* 在策略组之间移动工作负载
* 更改策略组的吞吐量限制
* 将工作负载移动到其他聚合和 / 或节点

