---
permalink: online-help/concept-using-a-threshold-policy-with-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: '您可以创建节点阈值策略，以便在潜在故障转移会将接管节点的性能降低到不可接受的水平时，您可以在 " 性能 / 节点故障转移规划 " 页面中收到通知。' 
---
= 将阈值策略与节点故障转移规划页面结合使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建节点阈值策略，以便在潜在故障转移会将接管节点的性能降低到不可接受的水平时，您可以在 " 性能 / 节点故障转移规划 " 页面中收到通知。

如果在连续六个收集时间段（ 30 分钟）内违反阈值，则名为 "`Node HA pair over-utilized` " 的系统定义的性能阈值策略将生成警告事件。如果 HA 对中节点的总已用性能容量超过 200% ，则会视为违反此阈值。

系统定义的阈值策略中的事件会提醒您，故障转移会将接管节点的延迟发生原因增加到不可接受的级别。当您看到此策略为特定节点生成的事件时，您可以导航到该节点的 " 性能 / 节点故障转移规划 " 页面，以查看因故障转移而导致的预测延迟值。

除了使用此系统定义的阈值策略之外，您还可以使用 "`Performance Capacity Used - Takeover` " 计数器创建阈值策略，然后将此策略应用于选定节点。如果指定的阈值低于 200% ，则可以在违反系统定义策略的阈值之前收到事件。如果您希望在生成系统定义的策略事件之前收到通知，则还可以指定超过阈值的最短时间，即 30 分钟以内。

例如，您可以定义一个阈值策略，以便在 HA 对中节点的总已用性能容量超过 175% 且持续 10 分钟以上时生成警告事件。您可以将此策略应用于 Node1 和 Node2 ，从而形成 HA 对。收到 Node1 或 Node2 的警告事件通知后，您可以查看该节点的 " 性能 / 节点故障转移规划 " 页面，以评估对接管节点的估计性能影响。您可以采取更正操作，以避免在发生故障转移时接管节点过载。如果在节点的已用总性能容量低于 200% 时采取措施，则即使在此期间发生故障转移，接管节点的延迟也不会达到不可接受的水平。
