---
permalink: online-help/concept-understanding-the-um-recommendations-to-tier-data-to-the-cloud.html 
sidebar: sidebar 
keywords:  
summary: '"性能/卷"清单页面显示与卷上存储的非活动用户数据大小相关的信息。在某些情况下、Unified Manager会确定通过将非活动数据分层到启用了FabricPool的聚合的云层\(云提供程序或StorageGRID \)而获益的某些卷。' 
---
= 了解 Unified Manager 有关将数据分层到云的建议
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"性能/卷"清单页面显示与卷上存储的非活动(冷)用户数据大小相关的信息。在某些情况下， Unified Manager 会确定通过将非活动数据分层到启用了 FabricPool 的聚合的云层（云提供商或 StorageGRID ）而获益的某些卷。

[NOTE]
====
FabricPool 是在 ONTAP 9.2 中引入的，因此，如果您使用的 ONTAP 软件版本早于 9.2 ，则 Unified Manager 对数据进行分层的建议需要升级 ONTAP 软件。此外、还可以使用 `auto` 分层策略是在ONTAP 9.4中引入的、因此建议使用 `auto` 分层策略、则必须升级到ONTAP 9.4或更高版本。

====
性能/卷清单页面上的以下三个字段提供了有关是否可以通过将非活动数据移动到云层来提高存储系统的磁盘利用率并节省性能层上的空间的信息。

* * 分层策略 *
+
分层策略可确定卷上的数据是否仍保留在性能层上，或者某些数据是否已从性能层移动到云层。

+
此字段中的值表示卷上设置的分层策略，即使卷当前不驻留在 FabricPool 聚合上也是如此。只有当卷位于 FabricPool 聚合上时，分层策略才会生效。

* * 冷数据 *
+
冷数据显示卷上存储的非活动（冷）用户数据的大小。

+
只有在使用ONTAP 9.4或更高版本的软件时、此处才会显示一个值、因为它要求部署卷的聚合具有 `inactive data reporting` 参数设置为 `enabled`、并且已达到最小冷却天数阈值(对于使用的卷 `snapshot-only` 或 `auto` 分层策略)。否则，此值将列为 "`N/A` " 。

* * 云建议 *
+
在捕获到有关卷上数据活动的足够信息后， Unified Manager 可能会确定不需要执行任何操作，或者您可以通过将非活动数据分层到云层来节省性能层上的空间。



[NOTE]
====
冷数据字段每 15 分钟更新一次，但在对卷执行冷数据分析时，云建议字段每 7 天更新一次。因此，各个字段之间的确切冷数据量可能会有所不同。" 云建议 " 字段显示运行分析的日期。

====
启用非活动数据报告后，冷数据字段将显示确切的非活动数据量。如果没有非活动数据报告功能， Unified Manager 将使用性能统计信息来确定卷上的数据是否处于非活动状态。在这种情况下，冷数据字段不会显示非活动数据量，但将光标悬停在 * 层 * 一词上方可查看云建议时会显示此数据量。

您将看到以下云建议：

* * 学习 * 。没有收集足够的数据来提供建议。
* * 层 * 。经过分析，确定卷包含非活动（冷）数据，您应将此卷配置为将此数据移动到云层。在某些情况下，可能需要先将卷移动到启用了 FabricPool 的聚合。在其他情况下，如果卷已位于 FabricPool 聚合上，则只需更改分层策略即可。
* * 无操作 * 。卷的非活动数据非常少，卷已在 FabricPool 聚合上设置为 "`auto` " 分层策略，或者卷是数据保护卷。当卷脱机或在 MetroCluster 配置中使用时，也会显示此值。


要移动卷或更改卷分层策略或聚合非活动数据报告设置、请使用OnCommand 系统管理器、ONTAP 命令行界面命令或这些工具的组合。

如果您以OnCommand 管理员或存储管理员角色登录到Unified Manager、则将光标悬停在*层*一词上时、云建议中会显示*配置卷*链接。单击此按钮可在 System Manager 中打开卷页面以进行建议的更改。
