---
permalink: online-help/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: '标注规则是您定义的用于标注存储对象(卷、集群或Storage Virtual Machine \(SVM\)\)的标准。您可以使用条件组或条件来定义标注规则。' 
---
= 标注规则在 Unified Manager 中的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
标注规则是您定义的用于标注存储对象（卷，集群或 Storage Virtual Machine （ SVM ））的标准。您可以使用条件组或条件来定义标注规则。

* 您必须将标注规则与标注关联。
* 您必须为标注规则关联一个对象类型；一个标注规则只能关联一个对象类型。
* Unified Manager 会在每个监控周期之后，或者在创建，编辑，删除或重新排列规则时从存储对象添加或删除标注。
* 一个标注规则可以具有一个或多个条件组，每个条件组可以具有一个或多个条件。
* 存储对象可以具有多个标注。特定标注的标注规则也可以在规则条件中使用不同的标注来向已标注的对象添加另一个标注。




== 条件

您可以创建多个条件组，每个条件组可以具有一个或多个条件。您可以在标注的标注规则中应用定义的所有条件组，以便为存储对象添加标注。

条件组中的条件使用逻辑 AND 执行。必须满足条件组中的所有条件。创建或修改标注规则时，系统会创建一个条件，此条件仅应用，选择和标注满足条件组中所有条件的存储对象。如果要缩小要标注的存储对象的范围，可以在一个条件组中使用多个条件。

您可以使用以下操作数和运算符并指定所需值来创建存储对象的条件。

|===
| 存储对象类型 | 适用的操作数 


 a| 
Volume
 a| 
* 对象名称
* 所属集群名称
* 所属 SVM 名称
* 标注




 a| 
SVM
 a| 
* 对象名称
* 所属集群名称
* 标注




 a| 
集群
 a| 
* 对象名称
* 标注


|===
如果选择标注作为任何存储对象的操作数，则可以使用 "`is` " 运算符。对于所有其他操作数，您可以选择 "`is` " 或 "`contains` " 作为运算符。如果选择 "`is` " 运算符，则会评估此条件，以确定该操作数值与为选定操作数提供的值是否完全匹配。如果选择 "`contains` " 运算符，则系统会评估此条件以满足以下条件之一：

* 该操作数值与选定操作数的值完全匹配。
* 操作数值包含为选定操作数提供的值。




== 包含条件的标注规则示例

对于具有以下两个条件的卷，请考虑使用一个条件组的标注规则：

* 名称包含 "`vol` "
* SVM 名称为 `data_sVM`


此标注规则会将名称中包含 "`vol` " 且托管在名称为 `data_sVM` 的 SVM 上的所有卷添加到选定标注和标注类型中。



== 条件组

条件组使用逻辑或执行，然后应用于存储对象。存储对象必须满足要标注的条件组之一的要求。满足所有条件组条件的存储对象将添加标注。您可以使用条件组来扩大要标注的存储对象的范围。



== 包含条件组的标注规则示例

假设一个卷具有两个条件组的标注规则；每个组包含以下两个条件：

* 条件组 1
+
** 名称包含 "`vol` "
** SVM 名称是 `data_sVM` 。此条件组会为名称中包含 "`vol` " 且托管在名称为 " `data_sVM` " 的 SVM 上的所有卷添加标注。


* 条件组 2.
+
** 名称包含 "`vol` "
** data-priority 的标注值为 "`critical` " 此条件组会为名称中包含 "`vol` " 且使用数据优先级标注值 "`Critical` " 标注的所有卷添加标注。




如果将包含这两个条件组的标注规则应用于存储对象，则会为以下存储对象添加标注：

* 名称中包含 "`vol` " 且托管在名称为 " `data_svm` " 的 SVM 上的所有卷。
* 名称中包含 "`vol` " 且使用数据优先级标注值 "`Critical` " 进行标注的所有卷。

