---
permalink: online-help/concept-roles-of-workloads-involved-in-a-performance-incident.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 使用角色确定工作负载是否参与性能事件。角色包括受影响的人，抢占资源的人和鲨鱼。用户定义的工作负载可以同时是受影响的工作负载，抢占资源的工作负载和资源的工作负载。 
---
= 性能事件中涉及的工作负载的角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 使用角色确定工作负载是否参与性能事件。角色包括受影响的人，抢占资源的人和鲨鱼。用户定义的工作负载可以同时是受影响的工作负载，抢占资源的工作负载和资源的工作负载。

|===
| Role | Description 


 a| 
受影响的对象
 a| 
一种用户定义的工作负载，其性能因其他工作负载（称为抢占资源）过度使用集群组件而下降。只有用户定义的工作负载才会被标识为受影响的工作负载。Unified Manager会根据延迟偏差确定受影响的工作负载、事件期间的实际延迟远远超出预期延迟范围。



 a| 
抢占资源
 a| 
一种用户定义或系统定义的工作负载，其集群组件的过度使用导致称为 " 受影响 " 的其他工作负载的性能下降。Unified Manager 会根据集群组件使用情况的偏差来确定抢占资源的工作负载，在发生事件时，该工作负载的实际使用量已远远超出预期使用范围。



 a| 
鲨鱼
 a| 
与事件中涉及的所有工作负载相比，集群组件使用率最高的用户定义工作负载。Unified Manager 可根据事件期间对集群组件的使用情况来确定鲨鱼工作负载。

|===
集群上的工作负载可以共享多个集群组件、例如存储聚合以及用于网络和数据处理的CPU。如果工作负载（例如卷）增加了对集群组件的使用量，使其无法高效满足工作负载需求，则此组件将处于争用状态。过度使用集群组件的工作负载是一个抢占资源的工作负载。共享这些组件且其性能受抢占资源的其他工作负载也会受到影响。系统定义的工作负载（例如重复数据删除或 Snapshot 副本）中的活动也可能升级为 "`bullying` " 。

当 Unified Manager 检测到事件时，它会确定涉及的所有工作负载和集群组件，包括导致事件的抢占资源的工作负载，处于争用状态的集群组件以及因抢占资源的工作负载活动增加而导致性能下降的受影响工作负载。

[NOTE]
====
如果 Unified Manager 无法识别抢占资源的工作负载，则仅会针对受影响的工作负载和所涉及的集群组件发出警报。

====
Unified Manager 可以确定受抢占资源的工作负载影响的工作负载，还可以确定这些工作负载何时成为抢占资源的工作负载。工作负载本身可能会成为抢占资源的工作负载。例如，如果高性能工作负载受到策略组限制的限制，则会限制策略组中的所有工作负载，包括其自身。在进行中的性能事件中，如果工作负载是抢占资源的工作负载或受影响的工作负载，则可能会更改其角色，或者不再参与此事件。在"性能/卷详细信息"页面的"事件列表"表中、选定卷更改其参与者角色后、将显示角色更改的日期和时间。
