---
permalink: online-help/concept-what-happens-to-performance-threshold-policies-when-an-object-is-moved-opm.html 
sidebar: sidebar 
keywords:  
summary: 由于性能阈值策略已分配给存储对象，因此，如果移动对象，则在移动完成后，所有已分配的阈值策略仍会附加到该对象。例如，如果将卷或 LUN 移动到其他聚合，则阈值策略对于新聚合上的卷或 LUN 仍处于活动状态。 
---
= 移动对象时性能阈值策略会发生什么情况
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由于性能阈值策略已分配给存储对象，因此，如果移动对象，则在移动完成后，所有已分配的阈值策略仍会附加到该对象。例如，如果将卷或 LUN 移动到其他聚合，则阈值策略对于新聚合上的卷或 LUN 仍处于活动状态。

如果阈值策略（组合策略）存在二级计数器条件，例如，如果为聚合或节点分配了其他条件，则二级计数器条件将应用于已将卷或 LUN 移动到的新聚合或节点。

如果正在使用已更改阈值策略的对象存在任何新的活动事件，则这些事件将标记为已废弃，并且阈值策略将开始将计数器作为新定义的阈值策略进行监控。

卷移动操作会导致 ONTAP 发送信息性更改事件。"性能资源管理器"页面和"性能/卷详细信息"页面上的"事件"时间线中会显示一个更改事件图标、以指示移动操作完成的时间。

[NOTE]
====
如果将对象移动到其他集群，则会从此对象中删除用户定义的阈值策略。如果需要，必须在移动操作完成后为对象分配阈值策略。但是，动态阈值策略和系统定义的阈值策略会在对象移动到新集群后自动应用于该对象。

====


== 在 HA 接管和交还期间阈值策略功能

在高可用性（ HA ）配置中执行接管或交还操作时，从一个节点移动到另一个节点的对象将以与手动移动操作相同的方式保留其阈值策略。由于 Unified Manager 每 15 分钟检查一次集群配置更改，因此在下次轮询集群配置之前，不会确定切换到新节点所产生的影响。

[NOTE]
====
如果接管和交还操作都在 15 分钟的配置更改收集期间内发生，则可能看不到性能统计信息从一个节点移动到另一个节点。

====


== 聚合重新定位期间的阈值策略功能

如果使用将聚合从一个节点移动到另一个节点 `aggregate relocation start` 命令、单阈值策略和组合阈值策略都会保留在所有对象上、并且阈值策略的节点部分会应用于新节点。



== MetroCluster 切换期间的阈值策略功能

在 MetroCluster 配置中，从一个集群移动到另一个集群的对象不会保留其用户定义的阈值策略设置。如果需要，您可以对已移至配对集群的卷和 LUN 应用阈值策略。对象移回其原始集群后，系统将自动重新应用用户定义的阈值策略。

xref:concept-volume-behavior-during-switchover-and-switchback.adoc[切换和切回期间的卷行为]
