---
permalink: online-help/concept-types-of-workloads-monitored-by-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 Unified Manager 监控两种类型的工作负载的性能：用户定义的工作负载和系统定义的工作负载。 
---
= Unified Manager 监控的工作负载类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 监控两种类型的工作负载的性能：用户定义的工作负载和系统定义的工作负载。

* * 用户定义的工作负载 _*
+
从应用程序到集群的 I/O 吞吐量。这些进程涉及读取和写入请求。FlexVol 卷或FlexGroup 卷是用户定义的工作负载。

+
[NOTE]
====
Unified Manager 仅监控集群上的工作负载活动。它不会监控应用程序，客户端或应用程序与集群之间的路径。

====
+
如果工作负载符合以下一项或多项条件，则 Unified Manager 将无法监控此工作负载：

+
** 它是处于只读模式的数据保护（ DP ）副本。(请注意、在使用ONTAP 8.3及更高版本时、系统会监控DP卷中用户生成的流量。)
** 它是无限卷。
** 它是脱机数据克隆。
** 它是 MetroCluster 配置中的镜像卷。


* * 系统定义的工作负载 _ *
+
与存储效率，数据复制和系统运行状况相关的内部流程，包括：

+
** 存储效率，例如重复数据删除
** 磁盘运行状况，包括 RAID 重建，磁盘擦洗等
** 数据复制，例如 SnapMirror 副本
** 管理活动
** 文件系统运行状况，包括各种 WAFL 活动
** 文件系统扫描程序，例如 WAFL 扫描
** 副本卸载，例如从 VMware 主机卸载存储效率操作
** 系统运行状况，例如卷移动，数据压缩等
** 不受监控的卷




只有当系统定义的工作负载使用的集群组件处于争用状态时，图形用户界面才会显示这些工作负载的性能数据。例如，您不能搜索系统定义的工作负载的名称以在图形用户界面中查看其性能数据。如果显示了多个系统定义的相同类型的工作负载、则工作负载名称将附加一个字母。此信函仅供支持人员使用。
