---
permalink: online-help/reference-edit-volume-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: '您可以将警报配置为在生成与卷容量相关的事件时发送通知、并对此事件采取更正操作。例如、对于"卷已满"阈值、您可以将警报配置为在指定时间段内条件持续存在时发送通知。' 
---
= 编辑卷阈值对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将警报配置为在生成与卷容量相关的事件时发送通知、并对此事件采取更正操作。例如、对于"卷已满"阈值、您可以将警报配置为在指定时间段内条件持续存在时发送通知。

您必须具有OnCommand 管理员或存储管理员角色。

通过编辑卷阈值对话框、您可以配置应用于选定卷的卷级别阈值。在卷级别配置阈值时、这些阈值优先于组级别阈值或全局级别阈值。

您可以在卷级别为容量、Snapshot副本、qtree配额、增长和索引节点配置阈值设置。配置卷阈值类型的组操作时、未在卷级别配置的设置将使用组操作阈值。如果未配置卷阈值类型的组操作、则编辑卷阈值对话框中未配置的区域将使用全局阈值。



== 容量区域

"容量"区域用于设置以下卷容量阈值条件：

* *空间接近全满*
+
指定将卷视为接近全满时的百分比。它还会显示与指定阈值对应的卷大小。

+
您也可以使用滑块设置阈值。

* *空间已满*
+
指定将卷视为全满时的百分比。它还会显示与指定阈值对应的卷大小。

+
您也可以使用滑块设置阈值。

* *达到全满前的天数*
+
指定卷容量达到全满前的剩余天数。





== Snapshot 副本

通过Snapshot副本区域、您可以为卷中的Snapshot副本设置以下阈值条件。

* * Snapshot预留已满*
+
指定将为Snapshot副本预留的空间视为已满时的百分比。

* *达到全满前的天数*
+
指定为Snapshot副本预留的空间达到容量全满前的剩余天数。

* *计数*
+
指定卷上被视为过多的Snapshot副本的数量。





== qtree配额区域

通过qtree配额区域、您可以为选定卷设置以下qtree配额阈值条件：

* *接近过量提交*
+
指定根据qtree配额将卷视为接近过量使用时的百分比。

* *过量提交*
+
指定根据qtree配额将卷视为过量使用时的百分比。





== 增长区域

"增长"区域用于为卷增长设置以下阈值条件：

* *增长率*
+
指定在系统生成卷增长率异常事件之前将卷的增长率视为正常的百分比。

* *增长率敏感度*
+
指定应用于卷增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"卷增长率异常"事件。

+
增长率敏感度值越低、表示卷对增长率的变化非常敏感。

+
[NOTE]
====
如果在全局阈值级别修改卷的增长率敏感度、则此更改也会应用于全局阈值级别聚合的增长率敏感度。

====




== 索引节点区域

通过索引节点区域、您可以为索引节点设置以下阈值条件：

* *接近全满*
+
指定将卷视为已占用其大部分索引节点的百分比。

+
您也可以使用滑块设置阈值。

* *全满*
+
指定将卷视为已使用其所有索引节点时的百分比。

+
您也可以使用滑块设置阈值。





== 命令按钮

使用命令按钮可以对选定卷执行以下任务：

* *还原为默认值*
+
用于将阈值还原为以下值之一：

+
** 组值、前提是卷属于某个组且该组具有卷阈值操作类型。
** 全局值、卷不属于任何组或卷所属的组没有卷阈值操作类型。


* * 保存 *
+
保存所有阈值设置。

* *保存并关闭*
+
保存所有阈值设置、然后关闭对话框。

* * 取消 *
+
忽略对阈值设置所做的更改(如果有)、然后关闭对话框。


