---
permalink: online-help/reference-advanced-secondary-setting-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用高级二级设置对话框在二级卷上启用版本灵活复制，多个副本备份以及与空间相关的设置。如果要更改启用或禁用当前设置，可以使用高级二级设置对话框。 
---
= 高级二级设置对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用高级二级设置对话框在二级卷上启用版本灵活复制，多个副本备份以及与空间相关的设置。如果要更改启用或禁用当前设置，可以使用高级二级设置对话框。

与空间相关的设置可最大程度地提高所存储的数据量，包括以下内容：重复数据删除，数据压缩，自动增长和空间保证。

此对话框包括以下字段：

* * 启用版本灵活复制 *
+
启用具有版本灵活复制功能的 SnapMirror 。即使目标卷运行的ONTAP 版本低于源卷的版本、只要源卷和目标都运行的是ONTAP 8.3或更高版本、版本灵活的复制也可以为源卷提供SnapMirror保护。

+
** 启用备份
+
如果启用了版本灵活复制，则还可以将 SnapMirror 源数据的多个 Snapshot 副本传输到 SnapMirror 目标并保留在 SnapMirror 目标上。



* * 启用重复数据删除 *
+
在 SnapVault 关系中的二级卷上启用重复数据删除，以便消除重复的数据块以节省空间。当空间节省至少为 10% 且数据覆盖速率不快时，您可以使用重复数据删除。重复数据删除通常用于虚拟化环境，文件共享和备份数据。默认情况下，此设置处于禁用状态。启用后，此操作将在每次传输后启动。

+
** Enable compression
+
启用透明的数据压缩。当空间节省至少为 10% ，潜在开销可接受以及有足够的系统资源在非高峰时段完成压缩时，您可以使用数据压缩。在 SnapVault 关系中，此设置默认处于禁用状态。只有在选择重复数据删除时，才可使用数据压缩。

** 实时压缩
+
通过在将数据写入磁盘之前压缩数据，可以立即节省空间。如果系统在高峰时段的利用率不超过 50% ，并且系统可以在高峰时段容纳新的写入和额外的 CPU ，则可以使用实时压缩。只有在选择 "`Enable Compression` " 时，此设置才可用。



* * 启用自动增长 *
+
用于在可用空间百分比低于指定阈值时自动增长目标卷，前提是相关聚合上有可用空间。

* * 最大大小 *
+
设置卷可增长到的最大百分比。默认值比源卷大小大 20% 。如果当前大小大于或等于最大自动增长百分比，则卷不会自动增长。只有在启用了自动增长设置时，才会启用此字段。

* * 增量大小 *
+
指定卷在达到源卷的最大百分比之前自动增长的百分比增量。

* * 空间保证 *
+
确保在二级卷上分配足够的空间，以便数据传输始终成功。空间保证设置可以是以下设置之一：

+
** 文件
** Volume
** 无、例如、您的卷可能为200 GB、其中包含的文件总数为50 GB；但是、这些文件只包含10 GB的数据。无论源卷上的内容如何，卷保证都会为目标卷分配 200 GB 的空间。文件保证会分配 50 GB 以确保为源上的文件预留足够的空间；在这种情况下，选择无意味着目标上仅为源上的文件数据所使用的实际空间分配 10 GB 。


+
默认情况下，空间保证设置为卷。





== 命令按钮

命令按钮可用于执行以下任务：

* * 应用 *
+
保存选定的效率设置，并在配置保护对话框中单击 * 应用 * 时应用这些设置。

* * 取消 *
+
丢弃所做的选择并关闭 " 高级目标设置 " 对话框。



* 相关信息 *

https://www.netapp.com/pdf.html?item=/media/19753-tr-3966.pdf["NetApp技术报告3966：《NetApp数据压缩和重复数据删除部署和实施指南(集群模式Data ONTAP)》"^]
