---
permalink: online-help/reference-notifications-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以将 Unified Manager 服务器配置为在生成事件或将事件分配给用户时发送通知。您还可以配置通知机制。例如，可以通过电子邮件或 SNMP 陷阱发送通知。 
---
= 设置/通知页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 Unified Manager 服务器配置为在生成事件或将事件分配给用户时发送通知。您还可以配置通知机制。例如，可以通过电子邮件或 SNMP 陷阱发送通知。

您必须具有OnCommand 管理员或存储管理员角色。



== email

通过此区域，您可以为警报通知配置以下电子邮件设置：

* * 发件人地址 *
+
指定发送警报通知的电子邮件地址。共享报告时，此值也用作报告的发件人地址。如果"发件人地址"已预先填充地址"`OnCommand@localhost.com`"、则应将其更改为实际有效的电子邮件地址、以确保所有电子邮件通知均已成功传送。





== SMTP 服务器

使用此区域可以配置以下 SMTP 服务器设置：

* * 主机名或 IP 地址 *
+
指定 SMTP 主机服务器的主机名，该主机服务器用于向指定的收件人发送警报通知。

* * 用户名 *
+
指定 SMTP 用户名。只有在 SMTP 服务器中启用了 SMTPAUTH 时，才需要 SMTP 用户名。

* * 密码 *
+
指定 SMTP 密码。只有在 SMTP 服务器中启用了 SMTPAUTH 时，才需要 SMTP 用户名。

* * 端口 *
+
指定 SMTP 主机服务器用于发送警报通知的端口。

+
默认值为 25. 。

* *使用STARTTLS *
+
选中此复选框可使用 TLS/SSL 协议（也称为 start_tls 和 StartTLS ）在 SMTP 服务器和管理服务器之间提供安全通信。

* * 使用 SSL*
+
选中此复选框可使用 SSL 协议在 SMTP 服务器和管理服务器之间提供安全通信。





== SNMP

使用此区域可以配置以下 SNMP 陷阱设置：

* * 版本 *
+
根据所需的安全类型指定要使用的 SNMP 版本。选项包括版本 1 ，版本 3 ，具有身份验证的版本 3 以及具有身份验证和加密的版本 3 。默认值为版本 1 。

* * 陷阱目标主机 *
+
指定接收管理服务器发送的 SNMP 陷阱的主机名或 IP 地址（ IPv4 或 IPv6 ）。

* * 出站陷阱端口 *
+
指定 SNMP 服务器接收管理服务器发送的陷阱所通过的端口。

+
默认值为 162. 。

* * 社区 *
+
用于访问主机的社区字符串。

* * 引擎 ID*
+
指定 SNMP 代理的唯一标识符，并由管理服务器自动生成。引擎 ID 可用于 SNMP 版本 3 ，具有身份验证的 SNMP 版本 3 和具有身份验证和加密的 SNMP 版本 3 。

* * 用户名 *
+
指定 SNMP 用户名。用户名可用于 SNMP 版本 3 ， SNMP 版本 3 和 SNMP 版本 3 以及身份验证和加密。

* * 身份验证协议 *
+
指定用于对用户进行身份验证的协议。协议选项包括 MD5 和 SHA 。默认值为 MD5 。身份验证协议适用于具有身份验证的 SNMP 版本 3 和具有身份验证和加密的 SNMP 版本 3 。

* * 身份验证密码 *
+
指定对用户进行身份验证时使用的密码。身份验证密码可用于具有身份验证的 SNMP 版本 3 和具有身份验证和加密的 SNMP 版本 3 。

* * 隐私协议 *
+
指定用于对 SNMP 消息进行加密的隐私协议。协议选项包括 AES 128 和 DES 。默认值为 AES 128 。SNMP 版本 3 提供了隐私协议，并支持身份验证和加密。

* * 隐私密码 *
+
指定使用隐私协议时的密码。隐私密码适用于具有身份验证和加密功能的 SNMP 版本 3 。


