---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: '通过"运行状况/集群存储摘要"页面、您可以查看有关所有集群中存储容量和利用率的汇总信息。此信息有助于您了解可能的容量风险并采取适当措施重新平衡工作负载。' 
---
= 运行状况/集群存储摘要页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过"运行状况/集群存储摘要"页面、您可以查看有关所有集群中存储容量和利用率的汇总信息。此信息有助于您了解可能的容量风险并采取适当措施重新平衡工作负载。

使用*导出*按钮将所有受监控集群的详细信息导出为逗号分隔值 (`.csv`)文件。

* *集群*
+
集群名称。

* *高可用性对*
+
通过形成两个节点获得的HA对值。

* *型号/系列*
+
集群的型号或系列名称。

* *操作系统版本*
+
系统上安装的ONTAP 版本。

* *总原始容量*
+
显示阵列中所有磁盘的总物理容量。

* *未配置原始容量*
+
容器类型不是聚合、损坏、备用或共享的磁盘的未配置容量。此容量始终高于ONTAP 中磁盘的物理容量。例如、假设磁盘为2 TB。在ONTAP 中、磁盘的物理容量为1.6 TB、而在Unified Manager中、未配置的原始容量为1.8 TB。

* *聚合总容量*
+
用户可用聚合的总大小。这包括Snapshot副本预留。

* *聚合已用容量*
+
聚合上已使用的容量。这包括卷、LUN和其他存储效率技术开销占用的容量。

* *聚合未用容量*
+
可用于在聚合上存储其他数据的容量。这包括Snapshot副本预留。

* *已分配LUN容量*
+
映射的LUN的容量。

* *未分配的LUN容量*
+
未映射到主机的所有LUN的容量。

* *卷总容量*
+
卷的总容量(已用+未用)。

* *卷已用容量*
+
卷的已用容量。

* *卷未使用容量*
+
卷的未使用容量。

* *卷保护容量*
+
已启用SnapMirror和SnapVault 的卷的容量。

* *集群许可云层总计*
+
已在云层中获得许可的总容量。对于需要FabricPool 许可证的存储提供程序、例如Amazon S3、Microsoft Azure Cloud、IBM Cloud Object Storage或Alibaba Cloud Object Storage、将显示此字段。

* *已使用集群许可云层*
+
需要FabricPool 许可证的存储提供程序的云层中数据所使用的空间。

* *已用集群StorageGRID 容量*
+
不需要FabricPool 许可证的存储提供程序(例如StorageGRID)的云层中数据所使用的空间。


