---
permalink: online-help/reference-management-groups-page.html 
sidebar: sidebar 
keywords:  
summary: '通过"管理/组"页面、您可以在Unified Manager中创建组、以便轻松管理存储对象。组是存储对象(集群、卷和SVM\)的动态集合、由您为组创建的组规则定义。' 
---
= 管理/组页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过"管理/组"页面、您可以在Unified Manager中创建组、以便轻松管理存储对象。组是存储对象(集群、卷和SVM)的动态集合、由您为组创建的组规则定义。

"管理/组"页面包含用于添加、删除或编辑组、组规则和组操作的选项卡。以操作员身份登录时、您将只对页面具有读取访问权限。以存储管理员或Unified Manager管理员身份登录时、您可以访问每个选项卡中的添加、编辑或删除按钮。



== 组选项卡

组选项卡将显示您创建的组的名称和问题描述。您可以执行添加、编辑或删除组等任务。此选项卡还会显示与组关联的组规则和组操作的数量、组中的集群、SVM和卷的数量。



== 命令按钮

* * 添加 * 。
+
显示添加组对话框、在此可以添加组并为组提供名称和问题描述。

+
您也可以稍后将组规则应用于组以包括存储对象。

* * 编辑 * 。
+
显示编辑组对话框、在此可以编辑选定组的名称和问题描述。

* * 删除 *
+
删除选定组。





== 列表视图

列表视图以表格形式显示您在Unified Manager中创建的组。您可以使用列筛选器自定义显示的数据。默认情况下、此列表按组名称排序。

* * 名称 *
+
显示组的名称。

* * 问题描述 *
+
显示组的问题描述。

* *关联规则*
+
显示添加到组的规则数。

* *关联操作*
+
显示添加到组的组操作数。

* *适用集群*
+
显示组中包含的集群数量。

* *适用的SVM*
+
显示组中包含的SVM数量。

* *适用卷*
+
显示组中包含的卷数。





== 组规则选项卡

"组规则"选项卡显示您为包含存储对象的组创建的组规则。您可以执行添加、编辑或删除组规则等任务。此选项卡还会显示为其创建组规则的组名称以及应用此规则的存储对象。您还可以查看满足组规则的存储对象的数量。



== 命令按钮

* * 添加 * 。
+
显示添加组规则对话框、在此可以为存储对象创建组规则。

* * 编辑 * 。
+
显示编辑组规则对话框、在此可以重新配置先前配置的组规则。

* * 删除 *
+
删除选定的组规则。





== 列表视图

列表视图以表格形式显示您为特定存储对象(集群、卷或SVM)创建的组规则以及满足定义的组规则的存储对象计数。

* * 名称 *
+
显示规则的名称。

* *关联组*
+
显示为其定义组规则的组的名称。

* *目标对象类型*
+
显示应用组规则的存储对象的类型。

* *适用对象*
+
显示根据组规则包含在组中的存储对象的计数。





== 组操作选项卡

组操作选项卡显示您为组定义的组操作的名称和类型。您可以执行添加、编辑、删除或重新排列组操作等任务。此选项卡还会显示应用组操作的组的名称。



== 命令按钮

* * 添加 * 。
+
显示添加操作对话框、在此可以为一组存储对象创建组操作。例如、您可以设置组中存储对象的阈值级别。

* * 编辑 * 。
+
显示编辑操作对话框、在此可以重新配置先前配置的组操作。

* * 删除 *
+
删除选定的组操作。

* *重新排序*
+
显示重新排列组操作对话框以重新排列组操作的顺序。





== 列表视图

列表视图以表格形式显示您在Unified Manager服务器中为组创建的组操作。您可以使用列筛选器自定义显示的数据。

* *排名*
+
显示要应用于组中存储对象的组操作的顺序。

* * 名称 *
+
显示组操作的名称。

* *关联组*
+
显示为其定义组操作的组的名称。

* *操作类型*
+
显示可以对组中的存储对象执行的组操作的类型。

+
不能为一个组创建多个具有相同操作类型的组操作。例如、您可以创建一个组操作来为组设置卷阈值。但是、您不能为同一组创建另一个组操作来更改卷阈值。

* * 问题描述 *
+
显示组操作的问题描述。


