---
permalink: online-help/reference-configure-protection-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用配置保护对话框为集群上的所有读取，写入和数据保护卷创建 SnapMirror 和 SnapVault 关系，以确保复制源卷或主卷上的数据。 
---
= 配置保护对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用配置保护对话框为集群上的所有读取，写入和数据保护卷创建 SnapMirror 和 SnapVault 关系，以确保复制源卷或主卷上的数据。



== 源选项卡

* * 拓扑视图 *
+
以可视方式显示您要创建的关系。默认情况下，拓扑中的源会突出显示。

* * 源信息 *
+
显示有关选定源卷的详细信息，包括以下信息：

+
** 源集群名称
** Source SVM name
** 卷的累积总大小
+
显示选定的所有源卷的总大小。

** 卷的累计已用大小
+
显示所有选定源卷的累计已用卷大小。

** 源卷
+
在表中显示以下信息：

+
*** 源卷
+
显示选定源卷的名称。

*** Type
+
显示卷类型。

*** Snaplock type
+
显示卷的 SnapLock 类型。选项包括 "Compliance" ， "Enterprise" 和 "Non-SnapLock" 。

*** Snapshot 副本
+
显示用于基线传输的 Snapshot 副本。如果源卷为读 / 写卷，则 Snapshot 副本列中的默认值表示默认情况下会创建新的 Snapshot 副本，并用于基线传输。如果源卷是数据保护卷，则 Snapshot 副本列中的默认值表示不会创建新的 Snapshot 副本，所有现有 Snapshot 副本都会传输到目标。单击 Snapshot 副本值将显示 Snapshot 副本列表，您可以从中选择现有 Snapshot 副本以用于基线传输。如果源类型为数据保护，则不能选择其他默认 Snapshot 副本。









== SnapMirror 选项卡

用于在创建 SnapMirror 关系时为保护关系指定目标集群， Storage Virtual Machine （ SVM ）和聚合，以及目标的命名约定。您还可以指定 SnapMirror 策略和计划。

* * 拓扑视图 *
+
以可视方式显示您要创建的关系。默认情况下，拓扑中的 SnapMirror 目标资源会突出显示。

* * 目标信息 *
+
用于选择保护关系的目标资源：

+
** 高级链接
+
在创建 SnapMirror 关系时启动 " 高级目标设置 " 对话框。

** 集群
+
列出可用作保护目标主机的集群。此字段为必填字段。

** Storage Virtual Machine （ SVM ）
+
列出选定集群上可用的 SVM 。必须先选择集群，然后才能填充 SVM 列表。此字段为必填字段。

** 聚合
+
列出选定 SVM 上可用的聚合。在填充聚合列表之前，必须先选择一个集群。此字段为必填字段。聚合列表显示以下信息：

+
*** 排名
+
如果多个聚合满足某个目标的所有要求，则此排名将根据以下条件指示列出该聚合的优先级：

+
.... 最好使用位于源卷节点以外的其他节点上的聚合来启用故障域隔离。
.... 最好使用卷数较少的节点上的聚合在集群中的节点之间实现负载平衡。
.... 优先使用可用空间大于其他聚合的聚合来启用容量平衡。排名为 1 表示根据这三个标准，聚合是最首选的聚合。


*** Aggregate name
+
聚合的名称

*** 可用容量
*** 聚合上可用于数据的空间量
*** 资源池
+
聚合所属资源池的名称



** 命名约定
+
指定应用于目标卷的默认命名约定。您可以接受提供的命名约定，也可以创建自定义约定。命名约定可以具有以下属性： %C ， %M ， %V 和 %N ，其中 %C 是集群名称， %M 是 SVM 名称， %V 是源卷， %N 是拓扑目标节点名称。

+
如果您的输入无效，则命名约定字段将以红色突出显示。单击 "`预览名称` " 链接可显示您输入的命名约定的预览，在文本字段中键入命名约定时，预览文本会动态更新。创建关系时、目标名称会附加一个介于001和999之间的后缀、以替换 `nnn` 预览文本中将显示此信息、其中001先分配、002再分配、依此类推。



* * 关系设置 *
+
用于指定保护关系使用的最大传输速率， SnapMirror 策略和计划：

+
** 最大传输速率
+
指定通过网络在集群之间传输数据的最大速率。如果选择不使用最大传输速率，则关系之间的基线传输将无限制。但是、如果您运行的是ONTAP 8.2、并且主集群和二级集群相同、则会忽略此设置。

** SnapMirror 策略
+
指定关系的 ONTAP SnapMirror 策略。默认值为 DPDefault 。

** 创建策略
+
启动创建 SnapMirror 策略对话框，在此可以创建和使用新的 SnapMirror 策略。

** SnapMirror 计划
+
指定关系的 ONTAP SnapMirror 策略。可用计划包括无， 5 分钟， 8 小时，每天，每小时， 和每周。默认值为无，表示此关系没有关联的计划。没有计划的关系没有滞后状态值，除非它们属于存储服务。

** 创建计划
+
启动创建计划对话框，在此可以创建新的 SnapMirror 计划。







== SnapVault 选项卡

用于在创建 SnapVault 关系时为保护关系指定二级集群， SVM 和聚合以及二级卷的命名约定。您还可以指定 SnapVault 策略和计划。

* * 拓扑视图 *
+
以可视方式显示您要创建的关系。默认情况下，拓扑中的 SnapVault 二级资源会突出显示。

* * 二级信息 *
+
用于为保护关系选择二级资源：

+
** 高级链接
+
启动高级二级设置对话框。

** 集群
+
列出了可用作二级保护主机的集群。此字段为必填字段。

** Storage Virtual Machine （ SVM ）
+
列出选定集群上可用的 SVM 。必须先选择集群，然后才能填充 SVM 列表。此字段为必填字段。

** 聚合
+
列出选定 SVM 上可用的聚合。在填充聚合列表之前，必须先选择一个集群。此字段为必填字段。聚合列表显示以下信息：

+
*** 排名
+
如果多个聚合满足某个目标的所有要求，则此排名将根据以下条件指示列出该聚合的优先级：

+
.... 最好使用位于主卷节点以外的其他节点上的聚合来启用故障域隔离。
.... 最好使用卷数较少的节点上的聚合在集群中的节点之间实现负载平衡。
.... 优先使用可用空间大于其他聚合的聚合来启用容量平衡。排名为 1 表示根据这三个标准，聚合是最首选的聚合。


*** Aggregate name
+
聚合的名称

*** 可用容量
*** 聚合上可用于数据的空间量
*** 资源池
+
聚合所属资源池的名称



** 命名约定
+
指定应用于二级卷的默认命名约定。您可以接受提供的命名约定，也可以创建自定义约定。命名约定可以具有以下属性： %C ， %M ， %V 和 %N ，其中 %C 是集群名称， %M 是 SVM 名称， %V 是源卷， %N 是拓扑二级节点名称。

+
如果您的输入无效，则命名约定字段将以红色突出显示。单击 "`预览名称` " 链接可显示您输入的命名约定的预览，在文本字段中键入命名约定时，预览文本会动态更新。如果键入的值无效，则无效信息将在预览区域中显示为红色问号。创建关系时、二级名称会附加一个介于001和999之间的后缀、以替换 `nnn` 预览文本中将显示此信息、其中001先分配、002再分配、依此类推。



* * 关系设置 *
+
用于指定保护关系使用的最大传输速率， SnapVault 策略和 SnapVault 计划：

+
** 最大传输速率
+
指定通过网络在集群之间传输数据的最大速率。如果选择不使用最大传输速率，则关系之间的基线传输将无限制。但是、如果您运行的是ONTAP 8.2、并且主集群和二级集群相同、则会忽略此设置。

** SnapVault 策略
+
指定关系的 ONTAP SnapVault 策略。默认值为 XDPDefault 。

** 创建策略
+
启动创建 SnapVault 策略对话框，在此可以创建和使用新的 SnapVault 策略。

** SnapVault 计划
+
指定关系的 ONTAP SnapVault 计划。可用计划包括无， 5 分钟， 8 小时，每天，每小时， 和每周。默认值为无，表示此关系没有关联的计划。没有计划的关系没有滞后状态值，除非它们属于存储服务。

** 创建计划
+
启动创建计划对话框，在此可以创建 SnapVault 计划。







== 命令按钮

命令按钮可用于执行以下任务：

* * 取消 *
+
丢弃所做的选择，然后关闭配置保护对话框。

* * 应用 *
+
应用您的选择并开始保护过程。


