---
permalink: online-help/reference-resynchronize-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 通过重新同步对话框，您可以重新同步先前已断开的 SnapMirror 或 SnapVault 关系上的数据，然后将目标设置为读 / 写卷。如果删除了源卷上所需的通用 Snapshot 副本，从而导致 SnapMirror 或 SnapVault 更新失败，您也可以重新同步。 
---
= 重新同步对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过重新同步对话框，您可以重新同步先前已断开的 SnapMirror 或 SnapVault 关系上的数据，然后将目标设置为读 / 写卷。如果删除了源卷上所需的通用 Snapshot 副本，从而导致 SnapMirror 或 SnapVault 更新失败，您也可以重新同步。



== 重新同步选项选项卡

通过重新同步选项选项卡，您可以为要重新同步的保护关系设置传输优先级和最大传输速率。

* * 传输优先级 *
+
运行传输的优先级。您可以选择 " 正常 " 或 " 低 " 。与指定了正常传输优先级的策略的关系将在具有指定低传输优先级的策略的关系之前运行。

* * 最大传输速率 *
+
指定通过网络在集群之间传输数据的最大速率。选中后，网络带宽将限制为您指定的值。您可以输入一个数值，然后选择 KB/ 秒（ KBps ）， MB/ 秒（ MBps ）， GB/ 秒（ GBps ）或 Tbps 。如果选择不使用最大传输速率，则关系之间的基线传输将无限制。但是、如果您运行的是ONTAP 8.2、并且主集群和二级集群相同、则此设置将被禁用。





== 源 Snapshot 副本选项卡

源 Snapshot 副本选项卡显示了有关用于基线传输的源 Snapshot 副本的以下信息：

* * 源卷 *
+
显示相应源卷的名称。

* * 目标卷 *
+
显示选定目标卷的名称。

* * 源类型 *
+
显示卷类型：读 / 写或数据保护。

* * Snapshot 副本 *
+
显示用于数据传输的 Snapshot 副本。单击 Snapshot 副本值将显示选择源 Snapshot 副本对话框，在此对话框中，可以根据您的保护关系类型以及要执行的操作选择要传输的特定 Snapshot 副本。





== 命令按钮

* * 提交 *
+
开始重新同步过程并关闭重新同步对话框。

* * 取消 *
+
取消选择并关闭重新同步对话框。


