---
permalink: online-help/reference-components-of-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: '" 性能 / 节点故障转移规划 " 页面的组件将显示在网格和 " 正在比较 " 窗格中。通过这些部分，您可以评估节点故障转移对接管节点性能的影响。' 
---
= 节点故障转移规划页面的组件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
" 性能 / 节点故障转移规划 " 页面的组件将显示在网格和 " 正在比较 " 窗格中。通过这些部分，您可以评估节点故障转移对接管节点性能的影响。



== 性能统计信息网格

" 性能 / 节点故障转移规划 " 页面显示一个网格，其中包含延迟， IOPS ，利用率和已用性能容量的统计信息。

[NOTE]
====
此页面和"性能/节点性能资源管理器"页面中显示的IOPS值可能不同。

====
在网格中，每个节点都分配有以下角色之一：

* 主卷
+
当 HA 配对节点出现故障时接管该配对节点的节点。根对象始终是主节点。

* 合作伙伴
+
在故障转移情形下出现故障的节点。

* 估计接管
+
与主节点相同。为此节点显示的性能统计信息显示接管节点接管故障配对节点后的性能。



[NOTE]
====
尽管接管节点的工作负载相当于故障转移后两个节点的合并工作负载，但估计接管节点的统计信息并不是主节点和配对节点的统计信息之和。例如，如果主节点的延迟为 2 毫秒 / 操作，而配对节点的延迟为 3 毫秒 / 操作，则估计接管节点的延迟可能为 4 毫秒 / 操作此值是 Unified Manager 执行的计算。

====
如果希望配对节点成为根对象，可以单击其名称。显示 " 性能 / 节点性能资源管理器 " 页面后，您可以单击 * 故障转移规划 * 选项卡以查看此节点故障情形下的性能变化情况。例如，如果 Node1 是主节点， Node2 是配对节点，则可以单击 Node2 将其设为主节点。通过这种方式，您可以查看估计性能如何根据发生故障的节点而发生变化。



== 正在比较窗格

以下列表介绍了默认情况下 " 正在比较 " 窗格中显示的组件：

* * 事件图表 *
+
它们的显示格式与 " 性能 / 节点性能资源管理器 " 页面中的显示格式相同。它们仅与主节点相关。

* * 计数器图表 *
+
它们会显示网格中显示的性能计数器的历史统计信息。在每个图表中， " 估计接管 " 节点的图形显示了在任何给定时间发生故障转移时的估计性能。

+
例如，假设 " 利用率 " 图表在上午 11 点显示 " 估计接管 " 节点的 73%2 月 8 日。如果当时发生了故障转移，则接管节点的利用率将为 73% 。

+
历史统计信息可帮助您找到启动故障转移的最佳时间，从而最大限度地降低接管节点过载的可能性。您只能在接管节点的预测性能可接受时计划故障转移。



默认情况下，根对象和配对节点的统计信息都会显示在 " 正在比较 " 窗格中。与 " 性能 / 节点性能资源管理器 " 页面不同，此页面不会显示 * 添加 * 按钮，用于添加对象进行统计信息比较。

您可以按照与 " 性能 / 节点性能资源管理器 " 页面中相同的方式自定义 " 比较 " 窗格。以下列表显示了自定义图表的示例：

* 单击节点名称可在计数器图表中显示或隐藏节点的统计信息。
* 单击 * 缩放视图 * 可在新窗口中显示特定计数器的详细图表。

