---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: '通过聚合的"配置/运行状况阈值"页面、您可以为受监控聚合配置全局运行状况阈值。在全局配置选项时、所有对象的默认值都将被修改。但是，如果在对象级别更改了默认值，则不会修改全局值。' 
---
= 聚合的配置/运行状况阈值页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过聚合的"配置/运行状况阈值"页面、您可以为受监控聚合配置全局运行状况阈值。在全局配置选项时、所有对象的默认值都将被修改。但是，如果在对象级别更改了默认值，则不会修改全局值。

您必须具有OnCommand 管理员或存储管理员角色。

违反阈值时会生成事件。您可以对此类事件采取更正操作。

阈值不适用于节点的根聚合。

您可以为以下各项设置聚合运行状况阈值：容量、聚合增长和聚合Snapshot副本。



== 容量区域

"容量"区域用于设置以下聚合容量阈值条件。请注意、如果对位于聚合上的卷启用自动增长、则根据自动增长设置的最大卷大小(而不是原始卷大小)、聚合容量阈值将视为已违反。

* *空间接近全满*
+
指定将聚合视为接近全满时的百分比：

+
** 默认值：80%
+
此阈值必须低于聚合全满阈值、才能使管理服务器生成事件。

** 生成的事件：聚合接近全满
** 事件严重性：警告


* *空间已满*
+
指定将聚合视为全满时的百分比：

+
** 默认值：90%
** 生成的事件：聚合已满
** 事件严重性：错误


* *接近过量提交*
+
指定将聚合视为接近过量使用时的百分比：

+
** 默认值：95%
+
此阈值必须低于聚合过量使用全满阈值、才能使管理服务器生成事件。

** 生成的事件：聚合接近过量提交
** 事件严重性：警告


* *过量提交*
+
指定将聚合视为过量使用时的百分比：

+
** 默认值：100%
** 生成的事件：聚合已过量提交
** 事件严重性：错误


* *达到全满前的天数*
+
指定聚合达到全满容量之前的剩余天数：

+
** 默认值：7
** 生成的事件：聚合达到全满前的天数
** 事件严重性：错误






== 增长区域

"增长"区域用于为聚合增长设置以下阈值条件：

* *增长率*
+
指定在系统生成"聚合增长率异常"事件之前将聚合的增长率视为正常的百分比：

+
** 默认值：1%
** 生成的事件：聚合增长率异常
** 事件严重性：警告


* *增长率敏感度*
+
指定应用于聚合增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"聚合增长率异常"事件。

+
增长率敏感度值越低、表示聚合对增长率的变化非常敏感。增长率敏感度的范围为1到5。

+
** 默认值：2


+
[NOTE]
====
如果在全局阈值级别修改聚合的增长率敏感度、则此更改也会应用于全局阈值级别卷的增长率敏感度。

====




== Snapshot副本区域

"Snapshot副本"区域用于设置以下Snapshot预留阈值条件：

* * Snapshot预留已满*
+
指定聚合占用为Snapshot副本预留的所有空间时的百分比：

+
** 默认值：90%
** 生成的事件：聚合Snapshot预留已满
** 事件严重性：警告






== 命令按钮

* * 还原为出厂默认值 *
+
用于将配置设置还原为出厂默认值。

* * 保存 *
+
保存选定选项的配置设置。


