---
permalink: online-help/reference-performance-statistics-displayed-in-the-data-breakdown-charts.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用这些图形查看卷的性能趋势。您还可以查看有关读取和写入、网络协议活动、QoS策略组限制对延迟的影响、缓存存储的读取和写入比率、工作负载使用的总集群CPU时间以及特定集群组件的统计信息。 
---
= 数据细分图表中显示的性能统计信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用这些图形查看卷的性能趋势。您还可以查看有关读取和写入、网络协议活动、QoS策略组限制对延迟的影响、缓存存储的读取和写入比率、工作负载使用的总集群CPU时间以及特定集群组件的统计信息。

这些视图最多可显示自当前日期起30天的统计信息。在历史数据图表上、如果选择的时间范围超过1天、则根据屏幕分辨率、这些图表将显示天数中延迟和IOPS的最大值。

[NOTE]
====
您可以使用*全选*复选框选择或取消选择列出的所有图表选项。

====
* * 延迟 *
+
以下图表详细列出了选定工作负载的延迟或响应时间信息：

+
** *集群组件*
+
显示选定卷使用的每个集群组件所用时间的图形。

+
该图表可帮助您确定每个组件的延迟影响、因为它与总延迟相关。您可以使用每个组件旁边的复选框显示和隐藏其图形。

+
对于QoS策略组、仅显示用户定义的策略组的数据。系统定义的策略组(如默认策略组)显示零。

** *读取/写入延迟*
+
显示选定卷工作负载在选定时间范围内成功发出读取和写入请求的延迟情况的图形。

+
写入请求为橙色线、读取请求为蓝色线。这些请求特定于选定卷工作负载的延迟、而不是集群上的所有工作负载。

+
[NOTE]
====
读取和写入统计信息可能并不总是与延迟图表中显示的总延迟统计信息的总和相同。根据Unified Manager收集和分析工作负载的读取和写入统计信息的方式、这是预期行为。

====
** *策略组影响*
+
显示受QoS策略组吞吐量限制影响的选定卷工作负载的延迟百分比的图形。

+
如果工作负载受到限制、则百分比表示限制在特定时间点对延迟的影响程度。百分比值表示限制量：

+
*** 0%=无限制
*** >0%=限制
*** > 20%=严重限制如果集群可以处理更多工作、您可以通过增加策略组限制来减少限制。另一个选项是将工作负载移动到不太繁忙的聚合。




+
[NOTE]
====
此图表仅显示设置了吞吐量限制的用户定义的QoS策略组中的工作负载。它不会显示工作负载是位于系统定义的策略组(例如默认策略组)中、还是位于不具有QoS限制的策略组中。对于QoS策略组、您可以将光标指向策略组的名称、以显示其吞吐量限制以及上次修改时间。如果在将关联集群添加到Unified Manager之前修改了策略组、则上次修改时间为Unified Manager首次发现集群的日期和时间。

====
* * IOPS *
+
以下图表详细列出了选定工作负载的IOPS数据：

+
** *读取/写入/其他*
+
显示一个图形、其中显示了选定时间范围内每秒读取和写入IOPS以及其他IOPS的数量。

+
其他IOPS是指客户端启动的非读取或写入协议活动。例如、在NFS环境中、这可以是元数据操作、例如getattr、setattr或fsstat。在CIFS环境中、这可以是属性查找、目录列表或防病毒扫描。写入IOPS为橙色线、读取请求为蓝色线。这些请求特定于选定卷工作负载的所有操作、而不是集群上的所有操作。



* * MBps*
+
以下图表详细列出了选定工作负载的吞吐量数据：

+
** *缓存命中率*
+
显示选定时间范围内缓存满足的客户端应用程序读取请求百分比的图形。

+
缓存可以位于Flash Cache卡上、也可以位于Flash Pool聚合中的固态驱动器(SSD)上。以蓝色显示的缓存命中是从缓存中读取的。橙色的缓存未命中是从聚合中的磁盘读取的。这些请求特定于选定卷工作负载、而不是集群上的所有工作负载。

+
您可以在Unified Manager的"运行状况"页面和OnCommand 系统管理器中查看有关卷缓存使用情况的更多详细信息。



* *组件*
+
以下图表按选定工作负载使用的集群组件详细列出了数据：

+
** *集群CPU时间*
+
显示选定工作负载使用的集群中所有节点的CPU使用时间图形(以毫秒为单位)。

+
此图显示了网络处理和数据处理的CPU总使用时间。此外、还包括与选定工作负载关联且使用相同节点进行数据处理的系统定义工作负载的CPU时间。您可以使用该图表确定工作负载是否占用了集群上的CPU资源。此外、您还可以将该图表与延迟图表下的读/写延迟图表或IOPS图表下的读/写/其他图表结合使用、以确定工作负载活动随时间发生的变化如何影响集群CPU利用率。

** *磁盘利用率*
+
显示一个图形、其中显示了存储聚合中数据磁盘在选定时间范围内的利用率百分比。

+
利用率仅包括来自选定卷工作负载的磁盘读取和写入请求。不包括从缓存读取。利用率特定于选定卷工作负载、而不是磁盘上的所有工作负载。如果受监控卷涉及卷移动、则此图表中的利用率值适用于卷移动到的目标聚合。




