---
permalink: online-help/reference-dynamic-performance-event-chart-details.html 
sidebar: sidebar 
keywords:  
summary: 对于动态性能事件，事件详细信息页面的系统诊断部分列出了处于争用状态的集群组件延迟或使用率最高的前几个工作负载。性能统计信息基于检测到性能事件的时间，直到上次分析事件为止。这些图表还会显示处于争用状态的集群组件的历史性能统计信息。 
---
= 动态性能事件图表详细信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于动态性能事件，事件详细信息页面的系统诊断部分列出了处于争用状态的集群组件延迟或使用率最高的前几个工作负载。性能统计信息基于检测到性能事件的时间，直到上次分析事件为止。这些图表还会显示处于争用状态的集群组件的历史性能统计信息。

例如，您可以确定组件利用率较高的工作负载，以确定要移至利用率较低的组件的工作负载。移动工作负载将减少当前组件的工作量，从而可能使该组件摆脱争用状态。此部分的是检测到事件并最后分析事件的时间和日期范围。对于活动事件（新事件或已确认事件），上次分析的时间将继续更新。

将光标悬停在延迟和活动图表上方时，这些图表将显示排名靠前的工作负载的名称。单击图表右侧的工作负载类型菜单，您可以根据工作负载在事件中的角色（包括 _鲨 鱼 _ ， _bulles_ 或 _victims_ ）对这些工作负载进行排序，并显示有关其延迟及其在争用集群组件上的使用情况的详细信息。您可以将实际值与预期值进行比较，以查看工作负载何时超出其预期延迟或使用量范围。请参见 xref:concept-types-of-workloads-monitored-by-unified-manager.adoc[Unified Manager监控的工作负载]。

[NOTE]
====
按延迟峰值偏差排序时，表中不会显示系统定义的工作负载，因为延迟仅适用于用户定义的工作负载。延迟值非常低的工作负载不会显示在表中。

====
有关动态性能阈值的详细信息、请参见 xref:reference-performance-event-analysis-and-notification.adoc[什么是事件]。有关Unified Manager如何对工作负载进行排名并确定排序顺序的信息、请参见 xref:concept-how-unified-manager-determines-the-performance-impact-for-an-incident.adoc[Unified Manager 如何确定事件的性能影响]。

图形中的数据显示上次分析事件之前 24 小时的性能统计信息。每个工作负载的实际值和预期值均基于工作负载参与事件的时间。例如，检测到事件后，工作负载可能会参与事件，因此其性能统计信息可能与检测事件时的值不匹配。默认情况下，工作负载按延迟峰值（最高）偏差排序。

[NOTE]
====
由于 Unified Manager 最多可保留 30 天的 5 分钟历史性能和事件数据，因此，如果事件超过 30 天，则不会显示任何性能数据。

====
* * 工作负载排序列 *
+
** * 延迟图表 *
+
显示上次分析期间事件对工作负载延迟的影响。

** * 组件使用情况列 *
+
显示有关处于争用状态的集群组件的工作负载使用情况的详细信息。在图中，实际使用量为蓝线。红色条会突出显示从检测时间到上次分析时间的事件持续时间。有关详细信息，请参见 xref:reference-workload-performance-measurement-values.adoc[工作负载性能测量]。

+
[NOTE]
====
对于网络组件，由于网络性能统计信息来自集群之外的活动，因此不会显示此列。

====
** * 组件使用情况 *
+
显示网络处理，数据处理和聚合组件的利用率历史记录（以百分比表示），或者显示 QoS 策略组组件的活动历史记录（以百分比表示）。不会显示网络或互连组件的图表。您可以指向统计信息以查看特定时间点的使用情况统计信息。

** *总写入MBps历史记录*
+
仅对于 MetroCluster 资源组件，显示在 MetroCluster 配置中镜像到配对集群的所有卷工作负载的总写入吞吐量（以 MB/ 秒（ MBps ）为单位）。

** * 事件历史记录 *
+
显示红色阴影线以指示处于争用状态的组件的历史事件。对于已废弃的事件，此图表将显示检测到选定事件之前以及解决该事件之后发生的事件。




