---
permalink: online-help/reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 通过生成用户和组配额电子邮件地址的规则页面，您可以创建规则，以便根据与集群， SVM ，卷， qtree ，用户关联的用户配额指定电子邮件地址。 或用户组。违反配额时，系统会向指定的电子邮件地址发送通知。 
---
= 生成用户和组配额电子邮件地址的规则页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过生成用户和组配额电子邮件地址的规则页面，您可以创建规则，以便根据与集群， SVM ，卷， qtree ，用户关联的用户配额指定电子邮件地址。 或用户组。违反配额时，系统会向指定的电子邮件地址发送通知。



== 规则区域

您必须为配额电子邮件地址定义规则。您还可以添加注释来说明规则。



== 如何定义规则

您必须按要执行的顺序输入规则。如果满足第一个规则的条件，则会根据此规则生成电子邮件地址。如果不满足此标准，则会考虑下一个规则的标准，依此类推。每行都列出一个单独的规则。默认规则是列表中的最后一个规则。您可以更改规则的优先级顺序。但是，您不能更改默认规则的顺序。

例如，如果要使用电子邮件地址 qtree1@xyz.com 接收有关 qtree1 违反配额的通知，并对所有其他 qtree 使用电子邮件地址 admin@xyz.com ，则必须按以下顺序列出这些规则：

* 如果（ $qtree = "qtree1" ），则为 qtree1@xyz.com
* 如果（ $qtree = * ），则为 admin@xyz.com


如果未满足指定规则的任何条件，则使用默认规则：

如果（ $user_or_Group = * ），则为 $user_or_Group@ $domain

如果多个用户具有相同的配额，则这些用户的名称将显示为逗号分隔值，并且这些规则不适用于此配额。



== 如何添加注释

您可以添加注释来说明规则。您应在每个注释的开头使用 # ，每行都列出一个单独的注释。



== 规则语法

规则的语法必须为以下语法之一：

* 如果(_valid variable* operator_*)、则为_email ID_@域名_
+
`if` 是一个关键字、并且小写。运算符为 = 。电子邮件 ID 可以包含任意字符，有效变量 $USER_OR_GROUP ， $USER 或 $GROUP ，也可以包含任意字符和有效变量 $USER_OR_GROUP ， $USER 或 $GROUP 的组合。域名可以包含任意字符，有效变量 $domain ，也可以包含任意字符和有效变量 $domain 的组合。有效变量可以是大写或小写，但不能是两者的组合。例如， $domain 和 $domain 是有效的，但 $Domain 不是有效的变量。

* 如果(_valid variable* operator_"_string_")、则为_email ID_@域名_
+
`if` 是一个关键字、小写。运算符可以是 `contains` 或=。电子邮件 ID 可以包含任意字符，有效变量 $USER_OR_GROUP ， $USER 或 $GROUP ，也可以包含任意字符和有效变量 $USER_OR_GROUP ， $USER 或 $GROUP 的组合。域名可以包含任意字符，有效变量 $domain ，也可以包含任意字符和有效变量 $domain 的组合。有效变量可以是大写或小写，但不能是两者的组合。例如， $domain 和 $domain 是有效的，但 $Domain 不是有效的变量。





== 命令按钮

使用命令按钮可以保存，验证或取消创建的规则：

* * 验证 *
+
验证已创建规则的语法。如果验证期间出现错误，则会显示生成错误的规则以及一条错误消息。

* * 还原为出厂默认值 *
+
用于将地址规则还原为出厂默认值。

* * 保存 *
+
验证规则的语法，如果没有错误，则保存该规则。如果验证期间出现错误，则会显示生成错误的规则以及一条错误消息。


