---
permalink: online-help/reference-user-defined-threshold-policies-page-opm.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用配置/性能阈值页面查看所有当前定义的性能阈值策略。此页面还提供了用于创建、克隆、编辑和删除阈值策略的功能。 
---
= 配置/性能阈值页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用配置/性能阈值页面查看所有当前定义的性能阈值策略。此页面还提供了用于创建、克隆、编辑和删除阈值策略的功能。

性能阈值策略列表按策略名称的字母顺序进行排序。您可以单击列标题，按该列对策略进行排序。如果要查找特定策略、可以使用筛选器和搜索机制细化清单列表中显示的阈值策略列表。



== 筛选器和搜索栏

通过*筛选*按钮、您可以仅显示符合特定条件的策略、从而细化阈值策略列表。

通过*搜索*按钮、您可以输入完整或部分策略名称以细化清单列表中显示的阈值策略列表、从而搜索特定策略。



== 命令按钮

* * 创建 * 。
+
创建新的性能阈值策略。

* * 克隆 *
+
根据选定策略的副本创建新的性能阈值策略。

* * 编辑 * 。
+
修改选定的性能阈值策略。使用此策略的所有存储对象都会更新、以使用经过修订的策略。

* * 删除 *
+
删除选定的性能阈值策略。此策略将从使用此策略的所有存储对象中删除。您可以单击"关联对象"列中的项以查看当前正在使用此策略的对象。





== 阈值策略列表

* * 策略名称 *
+
显示阈值策略的名称。您可以将光标置于策略名称上方以查看策略的详细信息。

* * 问题描述 *
+
显示阈值策略的简短问题描述。

* *第一条件*
+
显示阈值策略的主要条件、包括定义的性能计数器、警告触发值和严重触发值。您可以将光标置于条件名称上方以查看条件的详细信息。

* *第二条件*
+
显示二级阈值策略条件(如果已定义)。您可以将光标置于条件名称上方以查看条件的详细信息。如果未定义第二个条件、则此列为空。

+
[NOTE]
====
定义第二个条件时、只有在同时违反这两个条件时、才会生成事件。

====
* *关联对象*
+
显示可以应用阈值策略的存储对象的类型以及正在使用此策略的对象的数量。此字段为空、直到您将策略至少分配给一个对象为止。

+
您可以单击列标题、按对象类型对策略进行排序：卷、LUN、聚合等。您可以单击策略名称以显示当前正在使用阈值策略的对象填充的清单页面。


