---
permalink: online-help/reference-edit-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以编辑警报属性，例如与警报关联的资源，事件，脚本和通知选项。 
---
= 编辑警报对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以编辑警报属性，例如与警报关联的资源，事件，脚本和通知选项。



== Name

通过此区域，您可以编辑警报的名称和问题描述。

* * 警报名称 *
+
用于编辑警报名称。

* * 警报问题描述 *
+
用于指定警报的问题描述。

* * 警报状态 *
+
用于启用或禁用警报。





== Resources

通过此区域，您可以根据要触发警报的动态规则选择单个资源或对资源进行分组。您可以通过从下拉列表中选择资源类型来搜索资源，也可以指定确切的资源名称来显示特定资源。

* * 包括 *
+
用于包括要触发警报的资源。您可以指定一个文本字符串，以便对与该字符串匹配的资源进行分组，并选择要包含在警报中的此组。例如，您可以对名称包含 "`vol0` " 字符串的所有卷进行分组。

* * 排除 *
+
用于排除不希望触发警报的资源。例如，您可以排除名称包含 "`xyz` " 字符串的所有卷。

+
[NOTE]
====
只有在选择特定资源类型的所有资源时、才会显示排除选项卡、例如 <<All Volumes>> 或 <<All Volumes whose name contains '_xyz_'>>。

====




== 事件

通过此区域，您可以选择要触发警报的事件。您可以根据特定严重性为事件触发警报，也可以针对一组事件触发警报。

* * 事件严重性 *
+
用于根据严重性类型选择事件，可以是 " 严重 " ， " 错误 " 或 " 警告 " 。

* * 事件名称包含 *
+
用于选择名称包含指定字符的事件。





== 操作

此区域用于指定通知方法和通知频率。

* * 向这些用户发送警报 *
+
用于编辑电子邮件地址或用户名，或者指定新的电子邮件地址或用户名以接收通知。

* * 通知频率 *
+
用于编辑管理服务器发送通知的频率，直到事件被确认，解决或移至已废弃状态为止。

+
您可以选择以下通知方法：

+
** 仅通知一次
** 按指定频率通知
** 在指定时间范围内以指定频率通知


* * 问题描述 SNMP 陷阱 *
+
用于指定是否应将 SNMP 陷阱发送到全局配置的 SNMP 主机。

* * 执行脚本 *
+
用于将脚本与警报关联。此脚本会在生成警报时执行。





== 命令按钮

* * 保存 *
+
保存更改并关闭对话框。

* * 取消 *
+
丢弃所做的更改并关闭对话框。


