---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 通过存储摘要报告、您可以查看有关HA对中存储容量的汇总信息。此信息有助于您了解可能的容量风险并采取适当措施重新平衡工作负载。单节点集群信息在报告中不可见。 
---
= 存储摘要报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过存储摘要报告、您可以查看有关HA对中存储容量的汇总信息。此信息有助于您了解可能的容量风险并采取适当措施重新平衡工作负载。单节点集群信息在报告中不可见。



== 存储摘要报告图表视图

存储摘要报告以两种格式显示：

* 存储摘要报告图表视图
* 存储摘要报告表格视图


此图表显示了聚合在一段时间内已用和未用数据容量的容量趋势。总数据容量显示在垂直(y)轴上、集群名称显示在水平(x)轴上。因此、图表中的每个条代表一个集群。您可以通过将光标置于特定点上方来查看图中特定点的详细信息。

* *集群名称*
+
显示集群名称。

* *高可用性对*
+
显示通过形成两个节点获得的HA对值。

* * 型号 *
+
显示型号的名称。

* *操作系统版本*
+
显示使用的ONTAP 版本。

* *总原始容量*
+
显示阵列中所有磁盘的总物理容量。

* *未配置原始容量*
+
显示容器类型不是聚合、损坏、备用或共享的磁盘的未配置容量。此容量始终高于ONTAP 中磁盘的物理容量。例如、假设磁盘为2 TB。在ONTAP 中、磁盘的物理容量为1.6 TB、而在Unified Manager中、未配置的原始容量为1.8 TB。

* *聚合总容量*
+
显示用户可用聚合的总大小。这包括Snapshot副本预留。

* *聚合已用容量*
+
显示聚合上已使用的容量。这包括卷、LUN和其他存储效率技术开销占用的容量。

* *聚合未用容量*
+
显示可用于在聚合上存储其他数据的容量。这包括Snapshot副本预留。

* *已分配LUN容量*
+
显示已映射的LUN的容量。

* *未分配的LUN容量*
+
显示未映射到主机的所有LUN的容量。

* *卷总容量*
+
显示卷的总容量(已用+未用)。

* *卷已用容量*
+
显示卷的已用容量。

* *卷未使用容量*
+
显示卷的未用容量。

* *卷保护容量*
+
显示已启用SnapMirror和SnapVault 的卷的容量。

* *集群许可云层总计*
+
显示已在云层中获得许可的总容量。对于需要FabricPool 许可证的存储提供程序、例如Amazon S3、IBM云对象存储、Microsoft Azure Cloud或Alibaba云对象存储、将显示此字段。

* *已使用集群许可云层*
+
显示需要FabricPool 许可证的存储提供程序的云层中数据所使用的空间。

* *已用集群StorageGRID 容量*
+
显示不需要FabricPool 许可证的存储提供程序(例如StorageGRID)的云层中数据所使用的空间。


