---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: '"信息板/概述"页面以图形方式显示集群、聚合和Storage Virtual Machine (SVM\)等存储对象的运行状况。根据生成的可用性、容量、性能和保护相关事件、这些存储对象将归类为"运行状况良好"、"存在风险"或"发生意外事件"、或者对于与保护相关的事件、归类为"运行状况良好"、"警告"或"错误"。' 
---
= 信息板/概述页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"信息板/概述"页面以图形方式显示集群、聚合和Storage Virtual Machine (SVM)等存储对象的运行状况。根据生成的可用性、容量、性能和保护相关事件、这些存储对象将归类为"运行状况良好"、"存在风险"或"发生意外事件"、或者对于与保护相关的事件、归类为"运行状况良好"、"警告"或"错误"。



== 集群无法访问栏

如果无法访问集群、Unified Manager将在每个页面顶部的栏中显示详细信息。如果所有集群均可访问、则此窗格将隐藏。

您可以按F5刷新窗格中显示的信息。此操作可确保窗格显示有关当前无法访问的集群的最新信息。例如、如果删除了包含"集群不可访问"事件的集群、或者事件的状态为"已废弃"、则在刷新窗格时、系统会删除有关此事件的信息。

您可以单击 * 详细信息 * 按钮查看有关无法访问的集群的详细信息。此操作将打开事件清单页面。关闭此栏后、只有在重新登录到Unified Manager时、此栏才会再次显示。



== 概述区域

* *可用性窗格*
+
显示有关Unified Manager监控的集群、聚合和SVM的可用性信息。存储对象分为"运行状况良好"、"存在风险"或"发生意外事件"。例如、缺少备用磁盘的集群的状态显示为存在风险。

+
此窗格还会显示每个类别中的存储对象数量。单击任何对象总数将转到该对象的页面。例如、单击集群总数将转到运行状况/集群清单页面。单击列顶部的数字将转到事件清单页面。

* *容量窗格*
+
显示有关Unified Manager监控的聚合和SVM容量的信息。存储对象分为"运行状况良好"、"存在风险"或"发生意外事件"。例如、已用容量达到全满阈值的聚合的状态显示为"存在风险"。

+
此窗格还会显示每个类别中的存储对象数量。

* *性能窗格*
+
显示有关Unified Manager监控的集群、SVM和卷的性能信息。根据生成的性能相关意外事件、存储对象归类为"运行状况良好"、"存在风险"或"发生意外事件"。例如、工作负载的I/O响应时间已达到最大阈值的卷的状态将显示为"已发生意外事件"。

+
此窗格还会显示Unified Manager监控的集群、SVM和卷的总数。单击任何对象总数将转到该对象的页面。例如、单击集群总数将转到"性能/集群"清单页面。

* *保护窗格*
+
显示有关Unified Manager监控的保护关系的信息。保护关系分为"运行状况良好"、"警告"或"错误"。例如、滞后持续时间超过滞后警告阈值的关系将显示为"警告"。

+
此窗格还会显示每个保护类别中的存储对象总数。单击"滞后状态"、"异步存储"、"异步镜像"或"同步"类别对应的链接将转到"保护/卷关系"页面中这些对象的筛选列表。


