---
permalink: online-help/reference-volume-data-protection-configuration-report.html 
sidebar: sidebar 
keywords:  
summary: '通过卷数据保护配置报告、您可以查看节点或集群中使用的未受保护卷和Storage Virtual Machine (SVM\)。通过此信息、您可以了解系统的数据保护风险、并查看系统中受保护卷和未受保护卷的详细信息。' 
---
= 卷数据保护配置报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过卷数据保护配置报告、您可以查看节点或集群中使用的未受保护卷和Storage Virtual Machine (SVM)。通过此信息、您可以了解系统的数据保护风险、并查看系统中受保护卷和未受保护卷的详细信息。

卷数据保护配置报告以两种格式显示：

* 受保护和未受保护的卷饼图
* 未受保护的卷数据表格视图




== 受保护和未受保护的卷饼图

显示系统中受保护卷和未受保护卷的相对百分比。



== 未受保护的卷数据表格视图

* *集群*
+
显示集群名称。

* * Storage Virtual Machine*
+
显示包含卷的Storage Virtual Machine (SVM)的名称。

* * 卷 *
+
显示卷名称。

* *总数据容量(GB)*
+
显示总数据容量(已用+可用)(以GB为单位)。

* *已用数据容量(GB)*
+
显示已用数据容量(以GB为单位)。

* *已用数据%*
+
以百分比形式显示已用数据容量。

* *可用数据容量(GB)*
+
显示可用数据容量(以GB为单位)。

* *可用数据%*
+
以百分比形式显示可用数据容量。

* * Snapshot预留已用容量(GB)*
+
显示Snapshot预留中Snapshot副本使用的空间量(以GB为单位)。

* *已用Snapshot预留%*
+
以百分比形式显示Snapshot预留中Snapshot副本使用的空间量。

* * Snapshot预留可用容量(GB)*
+
显示可用于Snapshot副本的空间量(以GB为单位)。

* *快照预留可用%*
+
以百分比形式显示可用于Snapshot副本的空间量。

* * Snapshot预留总容量(GB)*
+
显示聚合的总快照预留容量(以GB为单位)。

* *全满天数*
+
显示聚合达到容量全满前的预计剩余天数。

* *空间全满阈值%*
+
显示聚合已满时的百分比。

* *空间接近全满阈值%*
+
显示聚合接近全满时的百分比。

* *每日增长率%*
+
显示卷中每24小时发生一次的增长率。

* *索引节点总数*
+
显示卷中的索引节点总数。

* *索引节点利用率*
+
指定卷中使用的索引节点空间。

* *配额已提交容量*
+
显示卷中预留的空间。

* *配额过量提交容量(GB)*
+
显示系统生成卷配额过量提交事件之前可使用的空间量(以GB为单位)。

* *快照自动删除*
+
显示是否已启用Snapshot副本自动删除。

* * 重复数据删除 *
+
显示卷是启用还是禁用了重复数据删除。

* *重复数据删除空间节省量(GB)*
+
显示通过使用重复数据删除在卷中节省的空间量(以GB为单位)。

* * 数据压缩 *
+
显示卷是启用还是禁用了数据压缩。

* *压缩空间节省量(GB)*
+
显示通过使用数据压缩在卷中节省的空间量(以GB为单位)。

* * 精简配置 *
+
显示是否为选定卷设置了空间保证。有效值为 " 是 " 和 " 否 "

* * 自动增长 *
+
显示FlexVol 卷在空间不足时大小是否自动增长。

* * 空间保证 *
+
显示卷从聚合中删除可用块时的 FlexVol 卷设置控制。

* * 状态 *
+
显示要导出的卷的状态。

* * SnapLock 类型 *
+
指示卷是SnapLock 卷还是非SnapLock卷。

* *到期日期*

