---
permalink: online-help/reference-email-notification-format-page.html 
sidebar: sidebar 
keywords:  
summary: '电子邮件通知格式页面显示存在与配额相关的问题描述 (已违反软限制或已达到硬限制)时发送给用户或用户组的电子邮件规则。' 
---
= 电子邮件通知格式页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
电子邮件通知格式页面显示存在与配额相关的问题描述（已违反软限制或已达到硬限制）时发送给用户或用户组的电子邮件的规则。

只有在生成以下用户或用户组配额事件时，才会发送电子邮件通知： 已违反用户或组配额磁盘空间软限制，已违反用户或组配额文件数软限制，已达到用户或组配额磁盘空间硬限制或已达到用户或组配额文件数硬限制。

* * 自 *
+
显示发送电子邮件的电子邮件地址，您可以对其进行修改。默认情况下、此地址为指定的"设置/通知"页面的电子邮件地址。

* * 主题 *
+
显示通知电子邮件的主题。

* * 电子邮件详细信息 *
+
显示通知电子邮件的文本。您可以根据需要修改文本。例如，您可以提供与配额属性相关的信息并减少关键字数量。但是，您不应修改关键字。

+
有效的关键字如下所示：

+
** $event_name
+
指定导致电子邮件通知的事件名称。

** $QUOTA_TARGET
+
指定适用配额的 qtree 或卷。

** $QUOTA_USE_Percent
+
指定用户或用户组使用的磁盘硬限制，磁盘软限制，文件硬限制或文件软限制的百分比。

** $QUOTA_Limit
+
指定用户或用户组达到的磁盘硬限制或文件硬限制，并生成以下事件之一：

+
*** 已达到用户或组配额磁盘空间硬限制
*** 已达到用户或组配额磁盘空间软限制
*** 已达到用户或组配额文件数硬限制
*** 已达到用户或组配额文件数软限制


** $QUOTA_USed
+
指定用户或用户组所使用的磁盘空间或创建的文件数。

** $QUOTA_USER
+
指定用户或用户组名称。







== 命令按钮

命令按钮可用于预览，保存或取消对电子邮件通知格式所做的更改：

* * 预览 *
+
显示通知电子邮件的预览。

* * 还原为出厂默认值 *
+
用于将通知格式还原为出厂默认值。

* * 保存 *
+
保存对通知格式所做的更改。


