---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 通过卷容量和利用率报告、您可以查看有关集群中卷的容量和利用率的信息。通过此信息、您可以了解可能的容量风险、并查看聚合的已配置、已用和未用容量。此外、此报告还有助于您决定是否启用重复数据删除和精简配置等节省空间的功能。 
---
= 卷容量和利用率报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过卷容量和利用率报告、您可以查看有关集群中卷的容量和利用率的信息。通过此信息、您可以了解可能的容量风险、并查看聚合的已配置、已用和未用容量。此外、此报告还有助于您决定是否启用重复数据删除和精简配置等节省空间的功能。



== 卷容量和利用率报告表格视图

* *集群*
+
显示集群名称。

* * Storage Virtual Machine*
+
显示包含卷的Storage Virtual Machine (SVM)的名称。

* * 卷 *
+
显示卷名称。

* *总数据容量*
+
显示卷中的总数据容量(已用+可用)。

* *已用数据容量*
+
显示卷中的已用数据容量。

* *已用数据%*
+
以百分比形式显示卷中的已用数据。

* *可用数据容量*
+
显示卷中的可用数据容量。

* *可用数据%*
+
以百分比形式显示卷中的可用数据容量。

* *每日增长率%*
+
显示卷中每24小时发生一次的增长率。

* *全满天数*
+
显示在卷容量达到全满前的预计剩余天数。

* *空间全满阈值%*
+
指定将卷视为已满的限制。

* *空间接近全满阈值%*
+
指定被视为接近全满的卷的限制。

* *增长率阈值%*
+
指定在系统生成"聚合增长率异常"事件之前、聚合的增长率视为正常。

* *增长率敏感度阈值*
+
指定应用于卷增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"卷增长率异常"事件。

* *达到全满前的天数阈值*
+
指定达到容量全满前的剩余天数。

* *快照溢出%*
+
显示Snapshot副本占用的数据空间百分比。

* * Snapshot预留已用容量*
+
显示卷中Snapshot副本使用的空间量。

* *已用Snapshot预留%*
+
以百分比形式显示卷中Snapshot副本使用的空间量。

* * Snapshot预留可用容量*
+
显示卷中Snapshot副本的可用空间量。

* *快照预留可用%*
+
以百分比形式显示卷中可用于Snapshot副本的空间量。

* * Snapshot预留总容量*
+
显示卷中的Snapshot副本总容量。

* * Snapshot副本预留全满阈值%*
+
指定将为Snapshot副本预留的空间视为已满时的百分比。

* * Snapshot副本计数阈值*
+
指定卷上被视为过多的Snapshot副本的数量。

* * Snapshot副本达到全满前的天数阈值*
+
指定为Snapshot副本预留的空间达到容量全满前的剩余天数。

* *索引节点数*
+
显示卷中的索引节点数。

* *索引节点利用率%*
+
指定卷中已用索引节点空间的百分比。

* *索引节点全满阈值*
+
指定将卷视为已使用其所有索引节点时的百分比。

* *索引节点接近全满阈值*
+
指定将卷视为已占用其大部分索引节点的百分比。

* *配额已提交容量*
+
显示卷中预留的空间。

* *配额过量提交的容量*
+
显示系统生成卷配额过量提交事件之前可使用的空间量。

* *配额过量提交阈值%*
+
指定卷接近过量使用时的百分比。

* *配额接近过量提交阈值%*
+
指定卷空间接近过量使用时的百分比。

* *快照自动删除*
+
显示是否已启用Snapshot副本自动删除。

* * 重复数据删除 *
+
显示卷是启用还是禁用了重复数据删除。

* *重复数据删除空间节省*
+
显示通过使用重复数据删除在卷中节省的空间量。

* * 数据压缩 *
+
显示卷是启用还是禁用了数据压缩。

* *压缩空间节省*
+
显示通过使用数据压缩在卷中节省的空间量。

* *缓存策略*
+
显示与选定卷关联的缓存策略。此策略提供有关如何对卷执行Flash Pool缓存的信息。有关缓存策略的详细信息、请参见运行状况/卷清单页面。

* *缓存保留优先级*
+
显示用于保留缓存池的优先级。

* * 精简配置 *
+
显示是否为选定卷设置了空间保证。有效值为 " 是 " 和 " 否 "

* * 自动增长 *
+
显示FlexVol 卷在空间不足时大小是否自动增长。

* * 空间保证 *
+
显示卷从聚合中删除可用块时的 FlexVol 卷设置控制。

* * 状态 *
+
显示要导出的卷的状态。

* * SnapLock 类型 *
+
指示卷是SnapLock 卷还是非SnapLock卷。

* *到期日期*
+
SnapLock 到期日期。

* * 分层策略 *
+
如果此卷部署在启用了FabricPool的聚合上、则会显示为该卷设置的分层策略。


