---
permalink: online-help/reference-remote-authentication-page.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用 " 远程身份验证 " 页面配置 Unified Manager ，使其能够与身份验证服务器进行通信，以便对尝试登录到 Unified Manager Web UI 的远程用户进行身份验证。' 
---
= 远程身份验证页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 " 远程身份验证 " 页面配置 Unified Manager ，使其能够与身份验证服务器进行通信，以便对尝试登录到 Unified Manager Web UI 的远程用户进行身份验证。

您必须具有OnCommand 管理员或存储管理员角色。

选中启用远程身份验证复选框后，您可以使用身份验证服务器启用远程身份验证。

* * 身份验证服务 *
+
用于将管理服务器配置为在 Active Directory ， OpenLDAP 等目录服务提供程序中对用户进行身份验证，或者指定您自己的身份验证机制。只有在启用了远程身份验证后，才能指定身份验证服务。

+
** * Active Directory*
+
*** 管理员名称
+
指定身份验证服务器的管理员名称。

*** Password
+
指定用于访问身份验证服务器的密码。

*** 基本可分辨名称
+
指定远程用户在身份验证服务器中的位置。例如、如果身份验证服务器的域名为ou@domain.com、则基本可分辨名称为 `cn=ou,dc=domain,dc=com`。

*** 禁用嵌套组查找
+
指定是启用还是禁用嵌套组查找选项。默认情况下，此选项处于禁用状态。如果使用 Active Directory ，则可以通过禁用对嵌套组的支持来加快身份验证速度。

*** 使用安全连接
+
指定用于与身份验证服务器通信的身份验证服务。



** * OpenLDAP*
+
*** 绑定可分辨名称
+
指定用于在身份验证服务器中查找远程用户的绑定可分辨名称以及基本可分辨名称。

*** 绑定密码
+
指定用于访问身份验证服务器的密码。

*** 基本可分辨名称
+
指定远程用户在身份验证服务器中的位置。例如、如果身份验证服务器的域名为ou@domain.com、则基本可分辨名称为 `cn=ou,dc=domain,dc=com`。

*** 使用安全连接
+
指定使用安全 LDAP 与 LDAPS 身份验证服务器进行通信。



** * 其他 *
+
*** 绑定可分辨名称
+
指定与基本可分辨名称一起使用的绑定可分辨名称，以便在您配置的身份验证服务器中查找远程用户。

*** 绑定密码
+
指定用于访问身份验证服务器的密码。

*** 基本可分辨名称
+
指定远程用户在身份验证服务器中的位置。例如、如果身份验证服务器的域名为ou@domain.com、则基本可分辨名称为 `cn=ou,dc=domain,dc=com`。

*** 协议版本
+
指定身份验证服务器支持的轻型目录访问协议（ LDAP ）版本。您可以指定是否必须自动检测协议版本，或者将版本设置为 2 或 3 。

*** 用户名属性
+
指定身份验证服务器中包含要由管理服务器进行身份验证的用户登录名的属性名称。

*** 组成员资格属性
+
指定一个值，用于根据用户的身份验证服务器中指定的属性和值将管理服务器组成员资格分配给远程用户。

*** UGID
+
如果远程用户包括在身份验证服务器中作为 groupOfuniqueNames 对象的成员，则可以使用此选项根据该 groupOfuniqueNames 对象中的指定属性将管理服务器组成员资格分配给远程用户。

*** 禁用嵌套组查找
+
指定是启用还是禁用嵌套组查找选项。默认情况下，此选项处于禁用状态。如果使用 Active Directory ，则可以通过禁用对嵌套组的支持来加快身份验证速度。

*** 成员
+
指定身份验证服务器用于存储有关组中各个成员的信息的属性名称。

*** 用户对象类
+
指定远程身份验证服务器中用户的对象类。

*** 组对象类
+
指定远程身份验证服务器中所有组的对象类。

*** 使用安全连接
+
指定用于与身份验证服务器通信的身份验证服务。





+
[NOTE]
====
如果要修改身份验证服务，请确保删除任何现有身份验证服务器并添加新的身份验证服务器。

====




== 身份验证服务器区域

" 身份验证服务器 " 区域显示管理服务器与之通信以查找远程用户并对其进行身份验证的身份验证服务器。远程用户或组的凭据由身份验证服务器维护。

* * 命令按钮 *
+
用于添加，编辑或删除身份验证服务器。

+
** 添加
+
用于添加身份验证服务器。

+
如果要添加的身份验证服务器属于高可用性对(使用同一数据库)、则还可以添加配对身份验证服务器。这样，当其中一个身份验证服务器无法访问时，管理服务器便可与配对服务器进行通信。

** 编辑
+
用于编辑选定身份验证服务器的设置。

** 删除
+
删除选定的身份验证服务器。



* * 名称或 IP 地址 *
+
显示用于在管理服务器上对用户进行身份验证的身份验证服务器的主机名或 IP 地址。

* * 端口 *
+
显示身份验证服务器的端口号。

* * 测试身份验证 *
+
此按钮可通过对远程用户或组进行身份验证来验证身份验证服务器的配置。

+
测试时，如果仅指定用户名，则管理服务器将在身份验证服务器中搜索远程用户，但不会对用户进行身份验证。如果同时指定用户名和密码，则管理服务器将搜索远程用户并对其进行身份验证。

+
如果禁用了远程身份验证，则无法测试身份验证。


