---
permalink: online-help/reference-create-schedule-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 通过创建计划对话框，您可以为 SnapMirror 和 SnapVault 关系传输创建基本或高级保护计划。您可以创建一个新的计划来增加因频繁更新数据而导致的数据传输频率，也可以在不频繁更改数据时创建一个不太频繁的计划。 
---
= 创建计划对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过创建计划对话框，您可以为 SnapMirror 和 SnapVault 关系传输创建基本或高级保护计划。您可以创建一个新的计划来增加因频繁更新数据而导致的数据传输频率，也可以在不频繁更改数据时创建一个不太频繁的计划。

无法为 SnapMirror 同步关系配置计划。

* * 目标集群 *
+
在配置保护对话框的 SnapVault 选项卡或 SnapMirror 选项卡中选择的集群名称。

* * 计划名称 *
+
为计划提供的名称。计划名称可以包含字符 A 到 Z ， a 到 z ， 0 到 9 以及以下任何特殊字符：！@ # $ % ｛ caret ｝ & * （） _ - 。计划名称不能包含以下字符： < > 。

* * 基本或高级 *
+
要使用的计划模式。

+
基本模式包括以下要素：

+
** 重复
+
计划传输的频率。选项包括每小时，每天和每周。

** day
+
如果选择了每周重复，则会在一周中的哪一天发生传输。

** 时间
+
如果选择 " 每日 " 或 " 每周 " ，则会在一天中的某个时间进行传输。



+
高级模式包括以下要素：

+
** months
+
以逗号分隔的数字列表，表示一年中的月份。有效值为 0 到 11 ，零表示 1 月，依此类推。此元素是可选的。将此字段留空表示传输每月发生。

** 天
+
以逗号分隔的数字列表，表示一个月中的某一天。有效值为 1 到 31 。此元素是可选的。将此字段留空意味着在一个月中的每一天都会发生传输。

** weekDays
+
以逗号分隔的数字列表，表示一周中的天数。有效值为 0 到 6 ， 0 表示星期日，依此类推。此元素是可选的。将此字段留空表示一周中的每一天都会发生传输。如果指定了一周中的某一天，但未指定一个月中的一天，则传输仅在一周中的指定日期发生，而不是每天发生。

** hours
+
以逗号分隔的数字列表，表示一天中的小时数。有效值为 0 到 23 ， 0 表示午夜。此元素是可选的。

** minutes
+
以逗号分隔的数字列表，表示一小时内的分钟数。有效值为 0 到 59 。此元素为必填项。




