---
permalink: online-help/reference-edit-aggregate-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以将警报配置为在生成与聚合容量相关的事件时发送通知、并对此事件采取更正操作。例如、对于聚合全满阈值、您可以将警报配置为在指定时间段内条件持续存在时发送通知。 
---
= 编辑聚合阈值对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将警报配置为在生成与聚合容量相关的事件时发送通知、并对此事件采取更正操作。例如、对于聚合全满阈值、您可以将警报配置为在指定时间段内条件持续存在时发送通知。

您必须具有OnCommand 管理员或存储管理员角色。

通过编辑聚合阈值对话框、您可以配置应用于选定聚合的聚合级别阈值。如果您配置聚合级别阈值、则这些阈值优先于全局级别阈值。您可以在聚合级别为容量、增长和Snapshot副本配置阈值设置。如果未配置这些设置、则会应用全局阈值。

[NOTE]
====
阈值不适用于节点的根聚合。

====


== 容量区域

"容量"区域用于设置以下聚合容量阈值条件：

* *空间接近全满*
+
指定将聚合视为接近全满时的百分比。它还会显示与指定阈值对应的聚合大小。

+
您也可以使用滑块设置阈值。

* *空间已满*
+
指定将聚合视为全满时的百分比。它还会显示与指定阈值对应的聚合大小。

+
您也可以使用滑块设置阈值。

* *接近过量提交*
+
指定将聚合视为接近过量使用时的百分比。

* *过量提交*
+
指定将聚合视为过量使用时的百分比。

* *达到全满前的天数*
+
指定聚合达到容量全满前的剩余天数。





== 增长区域

"增长"区域用于为聚合增长设置以下阈值条件：

* *增长率*
+
指定在系统生成"聚合增长率异常"事件之前将聚合的增长率视为正常的百分比。

* *增长率敏感度*
+
指定应用于聚合增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"聚合增长率异常"事件。

+
增长率敏感度值越低、表示聚合对增长率的变化非常敏感。

+
[NOTE]
====
如果在全局阈值级别修改聚合的增长率敏感度、则此更改也会应用于全局阈值级别卷的增长率敏感度。

====




== Snapshot副本区域

"Snapshot副本"区域用于设置以下Snapshot预留阈值条件：

* * Snapshot预留已满*
+
指定聚合已占用为Snapshot副本预留的所有空间的百分比。

+
您也可以使用滑块设置阈值。





== 命令按钮

使用命令按钮可以对选定聚合执行以下任务：

* *还原为默认值*
+
用于将聚合级别阈值还原为全局值。

* * 保存 *
+
保存所有阈值设置。

* *保存并关闭*
+
保存所有阈值设置、然后关闭对话框。

* * 取消 *
+
忽略对阈值设置所做的更改(如果有)、然后关闭对话框。


