---
permalink: online-help/reference-initialize-update-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: '通过 " 初始化 / 更新 " 对话框，您可以对新保护关系执行首次基线传输，或者如果关系已初始化，而您希望执行手动，计划外的增量更新，则可以更新此关系。' 
---
= 初始化 / 更新对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 " 初始化 / 更新 " 对话框，您可以对新保护关系执行首次基线传输，或者如果关系已初始化，而您希望执行手动，计划外的增量更新，则可以更新此关系。



== 传输选项选项卡

通过传输选项选项卡，您可以更改传输的初始化优先级并更改传输期间使用的带宽。

* * 传输优先级 *
+
运行传输的优先级。您可以选择 " 正常 " 或 " 低 " 。与指定了正常传输优先级的策略的关系将在指定低传输优先级的策略之前运行。默认情况下，选择 " 正常 " 。

* * 最大传输速率 *
+
指定通过网络在集群之间传输数据的最大速率。如果选择不使用最大传输速率，则关系之间的基线传输将无限制。但是、如果您运行的是ONTAP 8.2、并且主集群和二级集群相同、则会忽略此设置。如果选择多个具有不同最大传输速率的关系，则可以指定以下最大传输速率设置之一：

+
** 使用在设置或编辑单个关系期间指定的值
+
选中后，初始化和更新操作将使用创建或编辑每个关系时指定的最大传输速率。只有在初始化或更新具有不同传输速率的多个关系时，此字段才可用。

** 无限制
+
表示关系之间的传输没有带宽限制。只有在初始化或更新具有不同传输速率的多个关系时，此字段才可用。

** 将带宽限制为
+
选中后，网络带宽将限制为您指定的值。您可以输入一个数值，然后选择 KB/ 秒（ KBps ）， MB/ 秒（ MBps ）， GB/ 秒（ Gbps ）或 TB/ 秒（ Tbps ）。您指定的最大传输速率必须大于 1 KBps 且小于 4 Tbps 。







== 源 Snapshot 副本选项卡

源 Snapshot 副本选项卡显示了有关用于基线传输的源 Snapshot 副本的以下信息：

* * 源卷 *
+
显示相应源卷的名称。

* * 目标卷 *
+
显示选定目标卷的名称。

* * 源类型 *
+
显示卷类型。类型可以是读 / 写或数据保护。

* * Snapshot 副本 *
+
显示用于数据传输的 Snapshot 副本。单击 Snapshot 副本值将显示选择源 Snapshot 副本对话框，在此对话框中，您可以根据您的保护关系类型以及正在执行的操作选择要传输的特定 Snapshot 副本。指定其他 Snapshot 副本的选项不适用于数据保护类型的源。





== 命令按钮

命令按钮可用于执行以下任务：

* * 取消 *
+
丢弃所做的选择并关闭初始化 / 更新对话框。

* * 提交 *
+
保存所做的选择并启动初始化或更新作业。


