---
permalink: online-help/reference-snapmirror-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: SnapMirror关系事件可为您提供有关SnapMirror关系状态的信息、以便您可以监控潜在问题。事件按影响区域分组，并包括事件和陷阱名称，影响级别，源类型和严重性。 
---
= SnapMirror 关系事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror关系事件可为您提供有关SnapMirror关系状态的信息、以便您可以监控潜在问题。事件按影响区域分组，并包括事件和陷阱名称，影响级别，源类型和严重性。



== 影响区域：保护

星号（ * ）表示已转换为 Unified Manager 事件的 EMS 事件。

|===
| 事件名称（陷阱名称） | 影响级别 | 源类型 | severity 


 a| 
镜像复制运行不正常（ ocumEvtSnapmirrorRelationshipUnhealthy ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
警告



 a| 
镜像复制已断开（ ocumEvtSnapmirrorRelationshipStateBrokenoff ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error



 a| 
镜像复制初始化失败（ ocumEvtSnapmirrorRelationshipInitializeFailed ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error



 a| 
镜像复制更新失败（ ocumEvtSnapmirrorRelationshipUpdateFailed ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error



 a| 
镜像复制滞后错误（ ocumEvtSnapMirrorRelationshipLagError ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error



 a| 
镜像复制滞后警告（ ocumEvtSnapMirrorRelationshipLagWarning ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
警告



 a| 
镜像复制重新同步失败（ ocumEvtSnapmirrorRelationshipResyncFailed ）
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error



 a| 
已删除镜像复制已删除的ocumEvtSnapmirrorRelationshipDeleted"
 a| 
风险
 a| 
SnapMirror 关系
 a| 
警告



 a| 
同步复制不同步*
 a| 
风险
 a| 
SnapMirror 关系
 a| 
警告



 a| 
同步复制已还原*
 a| 
事件
 a| 
SnapMirror 关系
 a| 
信息



 a| 
同步复制自动重新同步失败*
 a| 
风险
 a| 
SnapMirror 关系
 a| 
error

|===