---
permalink: online-help/reference-event-details-page.html 
sidebar: sidebar 
keywords:  
summary: 在事件详细信息页面中，您可以查看选定事件的详细信息，例如事件严重性，影响级别，影响区域和事件源。此外，您还可以查看追加信息，了解可通过哪些修复方法来解析问题描述。 
---
= 事件详细信息页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在事件详细信息页面中，您可以查看选定事件的详细信息，例如事件严重性，影响级别，影响区域和事件源。此外，您还可以查看追加信息，了解可通过哪些修复方法来解析问题描述。

* * 事件名称 *
+
事件的名称以及上次查看事件的时间。

+
对于非性能事件，当事件处于 " 新增 " 或 " 已确认 " 状态时，上次看到的信息未知，因此会隐藏。

* * 事件问题描述 *
+
事件的简短问题描述。

+
在某些情况下，事件问题描述会提供触发事件的原因。

* * 争用组件 *
+
对于动态性能事件，此部分显示的图标表示集群的逻辑组件和物理组件。如果某个组件处于争用状态，则其图标会圈出并以红色突出显示。

+
可能会显示以下组件：

+
** * 网络 *
+
表示集群上iSCSI协议或光纤通道(FC)协议发出的I/O请求的等待时间。等待时间是指集群在响应I/O请求之前等待iSCSI Ready to Transfer (R2T)或FCP Transfer Ready (XFER_RDY)事务完成所花费的时间。如果网络组件处于争用状态、则表示块协议层的等待时间较长、正在影响一个或多个工作负载的延迟。

** * 网络处理 *
+
表示协议层和集群之间的 I/O 处理所涉及的集群软件组件。自检测到事件以来，处理网络处理的节点可能已发生更改。如果网络处理组件处于争用状态，则表示网络处理节点上的高利用率正在影响一个或多个工作负载的延迟。

** * QoS 策略 *
+
表示工作负载所属的存储服务质量(QoS)策略组。如果策略组组件处于争用状态，则表示策略组中的所有工作负载都受到所设置的吞吐量限制的限制，从而影响一个或多个工作负载的延迟。

** * 集群互连 *
+
表示与集群节点物理连接的缆线和适配器。如果集群互连组件处于争用状态，则表示集群互连中 I/O 请求的等待时间较长，正在影响一个或多个工作负载的延迟。

** * 数据处理 *
+
表示集群中与工作负载所在的存储聚合之间的 I/O 处理所涉及的集群软件组件。自检测到事件以来，处理数据处理的节点可能已发生更改。如果数据处理组件处于争用状态，则表示数据处理节点上的高利用率正在影响一个或多个工作负载的延迟。

** * MetroCluster 资源 *
+
表示用于在 MetroCluster 配置中的集群之间镜像数据的 MetroCluster 资源，包括 NVRAM 和交换机间链路（ ISL ）。如果 MetroCluster 组件处于争用状态，则表示本地集群上的工作负载写入吞吐量较高，或者链路运行状况问题描述正在影响本地集群上一个或多个工作负载的延迟。如果集群不在 MetroCluster 配置中，则不会显示此图标。

** * 聚合或 SSD 聚合操作 *
+
表示运行工作负载的存储聚合。如果聚合组件处于争用状态，则表示聚合上的高利用率正在影响一个或多个工作负载的延迟。聚合包含所有HDD、或者混合使用HDD和SSD (Flash Pool聚合)。" `SSD 聚合` " 由所有 SSD （全闪存聚合）组成，或者由 SSD 和云层（ FabricPool 聚合）组成。

** * 云延迟 *
+
表示集群中与存储用户数据的云层之间的 I/O 处理相关的软件组件。如果云延迟组件处于争用状态，则表示从云层上托管的卷进行的大量读取正在影响一个或多个工作负载的延迟。

** * 同步 SnapMirror*
+
表示在 SnapMirror 同步关系中将用户数据从主卷复制到二级卷所涉及的集群软件组件。如果同步 SnapMirror 组件处于争用状态，则表示 SnapMirror 同步操作的活动正在影响一个或多个工作负载的延迟。





" 事件信息 " ， " 系统诊断 " 和 " 建议的操作 " 部分将在其他主题中进行介绍。



== 命令按钮

命令按钮可用于执行以下任务：

* * 注释图标 *
+
用于添加或更新有关事件的注释，并查看其他用户留下的所有注释。



* 操作菜单 *

* * 分配给我 *
+
将事件分配给您。

* * 分配给他人 *
+
打开分配所有者对话框，在此可以将事件分配或重新分配给其他用户。

+
将事件分配给用户时，系统会将用户的名称以及事件分配时间添加到选定事件的事件列表中。

+
您也可以通过将所有权字段留空来取消分配事件。

* * 确认 *
+
确认选定事件，以使您不再收到重复的警报通知。

+
确认事件后，您的用户名以及确认事件的时间将添加到选定事件的事件列表（确认者）中。确认事件后，您将负责管理该事件。

* * 标记为已解决 *
+
用于将事件状态更改为已解决。

+
解决某个事件时，系统会将您的用户名和事件解决时间添加到选定事件的事件列表（解决者）中。对事件采取更正操作后，必须将事件标记为已解决。

* * 添加警报 *
+
显示添加警报对话框，在此可以为选定事件添加警报。


