---
permalink: online-help/reference-create-snapvault-policy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 通过创建 SnapVault 策略对话框，您可以创建一个策略来设置 SnapVault 传输的优先级。您可以使用策略最大程度地提高从主卷到二级卷的传输效率。 
---
= 创建 SnapVault 策略对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过创建 SnapVault 策略对话框，您可以创建一个策略来设置 SnapVault 传输的优先级。您可以使用策略最大程度地提高从主卷到二级卷的传输效率。

* * 目标集群 *
+
在配置保护对话框的 SnapVault 选项卡中选择的集群名称。

* * 目标 SVM*
+
在配置保护对话框的 SnapVault 选项卡中选择的 SVM 的名称。

* * 策略名称 *
+
为新策略提供的名称。策略名称可以包含字符 A 到 Z ， a 到 z ， 0 到 9 ，句点（ . ），连字符（ - ）， 和下划线（ _ ）。

* * 传输优先级 *
+
运行传输的优先级。您可以选择 " 正常 " 或 " 低 " 。指定了正常传输优先级的策略的传输关系将在指定了低传输优先级的策略的传输关系之前运行。默认设置为 " 正常 " 。

* * 注释 *
+
一个可选字段，您可以在其中添加有关 SnapVault 策略的注释，最多 255 个字符。

* * 忽略访问时间 *
+
指定对于仅更改了访问时间的文件是否忽略增量传输。

* * 复制标签 *
+
在表中列出与 ONTAP 选择的在策略中具有特定复制标签的 Snapshot 副本关联的规则。此外，还提供了以下信息和操作：

+
** 命令按钮
+
命令按钮可用于执行以下操作：

+
*** 添加
+
用于创建 Snapshot 副本标签和保留数量。

*** 编辑保留计数
+
用于更改现有 Snapshot 副本标签的保留数量。保留计数必须为 1 到 251 之间的数字。所有规则的所有保留计数之和不能超过 251 。

*** 删除
+
用于删除现有 Snapshot 副本标签。



** Snapshot 副本标签
+
显示 Snapshot 副本标签。如果选择一个或多个具有相同本地 Snapshot 副本策略的卷，则会显示策略中每个标签的条目。如果选择具有两个或更多本地 Snapshot 副本策略的多个卷，则此表将显示所有策略的所有标签

** 计划
+
显示与每个 Snapshot 副本标签关联的计划。如果某个标签具有多个关联计划，则该标签的计划将显示在一个逗号分隔列表中。如果选择多个具有相同标签但计划不同的卷，则此计划将显示 "`Various` " ，以指示多个计划与选定卷关联。

** 目标保留计数
+
显示 SnapVault 二级系统上保留的具有指定标签的 Snapshot 副本的数量。具有多个计划的标签的保留计数显示每个标签和计划对的保留计数总和。如果选择具有两个或更多本地 Snapshot 副本策略的多个卷，则保留计数为空。




