---
permalink: online-help/reference-management-annotations-page.html 
sidebar: sidebar 
keywords:  
summary: 通过管理/标注页面、您可以在Unified Manager中创建标注、以便为存储对象添加标注、也可以编辑或删除标注。您可以使用annotation_value对手动为存储对象添加标注、也可以配置标注规则。存储对象将根据您应用的标注动态标注。 
---
= 管理/标注页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过管理/标注页面、您可以在Unified Manager中创建标注、以便为存储对象添加标注、也可以编辑或删除标注。您可以使用annotation_value对手动为存储对象添加标注、也可以配置标注规则。存储对象将根据您应用的标注动态标注。

以操作员身份登录时、您将只对页面具有读取访问权限。以存储管理员或Unified Manager管理员身份登录时、您可以访问每个选项卡中的添加、编辑或删除按钮。



== 标注选项卡

通过标注选项卡、您可以在Unified Manager中查看、创建、编辑或删除标注。

* *标注列表*
+
显示预定义和自定义标注的名称。此外、还会显示与每个标注关联的标注值计数。您可以单击标注名称以查看标注的详细信息。





== 摘要区域

您可以查看选定标注的以下详细信息：

* * 问题描述 *
+
显示为标注提供的问题描述。

* *创建者*
+
显示创建标注的用户的名称。

* *创建日期*
+
显示创建标注的日期。





== annotation =值对

显示可用于选定标注的标注值对和关联存储对象的列表。

* * 值 *
+
显示"标注=值"对的名称。

* *适用集群*
+
显示使用特定annotation_value对标注的集群数量。您可以单击此数字以查看集群页面、其中会显示与特定值关联的集群的筛选列表。

* *适用的Storage Virtual Machine (SVM)*
+
显示使用特定标注=值对标注的Storage Virtual Machine (SVM)的数量。您可以单击此数字以查看Storage Virtual Machine (SVM)页面、其中会显示与特定值关联的Storage Virtual Machine (SVM)的筛选列表。

* *适用卷*
+
显示使用特定annotation_value对标注的卷数量。您可以单击此数字以查看卷页面、其中会显示与特定值关联的卷的筛选列表。





== 通过规则关联对象

显示选定标注的标注规则和关联存储对象的列表。

* *排名*
+
显示要应用于存储对象的标注规则的顺序。

* *规则*
+
显示标注规则的名称。

* *目标对象类型*
+
显示应用标注规则的存储对象的类型。

* *关联标注值*
+
显示应用于存储对象的annotation_value对。

* *适用对象*
+
显示根据标注规则标注的存储对象的计数。





== 手动对象关联

显示您已手动配置并与存储对象关联的标注列表。

* *标注=值对*
+
显示手动标注的名称和值。

* *适用集群*
+
显示使用特定手动标注值标注的集群数量。您可以单击此数字以查看集群页面、其中会显示与特定值关联的集群的筛选列表。

* *适用的Storage Virtual Machine (SVM)*
+
显示使用特定手动标注值标注的Storage Virtual Machine (SVM)的数量。您可以单击此数字以查看Storage Virtual Machine (SVM)页面、其中会显示与特定值关联的Storage Virtual Machine (SVM)的筛选列表。

* *适用卷*
+
显示使用特定手动标注值标注的卷数量。您可以单击此数字以查看卷页面、其中会显示与特定值关联的卷的筛选列表。





== 命令按钮

您必须具有OnCommand 管理员或存储管理员角色。对于预定义的标注、您不能添加或删除值。

* *添加标注*
+
打开添加标注对话框、在此可以创建新的自定义标注并为标注分配值。

* * 操作 *
+
用于编辑或删除选定标注问题描述。

* * 编辑 * 。
+
打开编辑标注对话框、在此可以修改标注名称和问题描述。

* * 删除 *
+
用于删除标注值。只有当该值与任何标注规则或组规则无关时、才能将其删除。





== 标注规则选项卡

"标注规则"选项卡将显示您为标注存储对象而创建的标注规则。您可以执行添加、编辑、删除标注规则或对标注规则重新排序等任务。您还可以查看满足标注规则的存储对象的数量。



== 命令按钮

您必须具有OnCommand 管理员或存储管理员角色。

* * 添加 * 。
+
显示添加标注规则对话框、在此可以为存储对象创建标注规则。

* * 编辑 * 。
+
显示编辑标注规则对话框、在此可以重新配置先前配置的标注规则。

* * 删除 *
+
删除选定标注规则。

* *重新排序*
+
显示重新排列标注规则对话框、在此可以重新排列标注规则的顺序。





== 列表视图

列表视图以表格形式显示您在Unified Manager服务器中创建的标注规则。您可以使用列筛选器自定义显示的数据。"标注规则"选项卡的列表视图和"标注"选项卡中"关联规则"部分的列表视图包含以下列：

* 排名
* Name
* 目标对象类型
* 关联的标注值
* 适用对象


此时将为"标注规则"选项卡显示一个附加列"关联标注"、其中显示应用于存储对象的标注的名称。
