---
permalink: online-help/reference-node-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 使用性能/节点信息页面可查看节点的物理和逻辑属性列表。此信息可能有助于回答与性能相关的问题。 
---
= 性能/节点信息页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用性能/节点信息页面可查看节点的物理和逻辑属性列表。此信息可能有助于回答与性能相关的问题。



== 节点属性

* * IP 地址 *
+
节点管理LIF的IPv4或IPv6地址。

* * FQDN *
+
节点管理LIF的完全限定域名(FQDN)。

* *操作系统版本*
+
节点上安装的ONTAP 软件版本。

* *型号/系列*
+
节点的平台型号。

* *容量(可用/总计)*
+
节点可用的总存储容量(以GB为单位)以及当前可用的存储容量。

* *集群*
+
此节点所属集群的名称。您可以单击此名称以在"性能/集群资源管理器"页面中显示集群详细信息。

* * HA配对系统*
+
HA配对节点的名称(如果适用)。您可以单击此名称以在"性能/节点资源管理器"页面中显示配对节点详细信息。

* * 聚合 *
+
此节点上的聚合数。您可以单击该数字以在"性能/聚合清单"页面中显示聚合。

+
[NOTE]
====
此处列出的数字可能与"性能/聚合清单"页面中的数字不匹配、因为清单页面不包括根聚合。

====
* * 端口 *
+
此节点上的端口数。您可以单击此数字以在"性能/端口清单"页面中显示端口。

+
[NOTE]
====
此处列出的数字可能与"性能/端口清单"页面中的数字不匹配、因为清单页面不包括节点管理端口。

====
* *联系人/位置*
+
如果可用、则为要联系的有关此节点的管理员的名称以及节点的位置。

* 核心数*/速度*
+
控制器上的CPU核数以及CPU核的速度(如果有)。

* * RAM *
+
如果可用、则为控制器上可用的总内存。





== 闪存设备

[NOTE]
====
只有在节点中安装了 Flash Cache 模块时，才会显示节点的 Flash Cache 数据。

====
* *插槽编号*
+
安装Flash Cache模块的插槽编号。

* * 状态 *
+
模块的运行状态。有效值：

+
** 联机
** offline_failed
** offline_threshold


* *型号/系列*
+
模块的型号。

* *固件修订版*
+
安装在模块上的固件版本。

* * 容量 *
+
已安装Flash Cache模块的大小。


