---
permalink: online-help/reference-add-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 您可以创建警报，以便在生成特定事件时向您发出通知，从而快速解决问题描述问题，从而最大限度地减少对环境的影响。您可以为单个资源或一组资源以及特定严重性类型的事件创建警报。您还可以指定警报的通知方法和频率。 
---
= 添加警报对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建警报，以便在生成特定事件时向您发出通知，从而快速解决问题描述问题，从而最大限度地减少对环境的影响。您可以为单个资源或一组资源以及特定严重性类型的事件创建警报。您还可以指定警报的通知方法和频率。

您必须具有OnCommand 管理员或存储管理员角色。



== Name

使用此区域可以指定警报的名称和问题描述：

* * 警报名称 *
+
用于指定警报名称。

* * 警报问题描述 *
+
用于指定警报的问题描述。





== Resources

通过此区域，您可以根据要触发警报的动态规则选择单个资源或对资源进行分组。_dynamic rule_ 是根据您指定的文本字符串筛选的一组资源。您可以通过从下拉列表中选择资源类型来搜索资源，也可以指定确切的资源名称来显示特定资源。

如果您从任何存储对象详细信息页面创建警报，则此存储对象将自动包含在警报中。

* * 包括 *
+
用于包括要触发警报的资源。您可以指定一个文本字符串，以便对与该字符串匹配的资源进行分组，并选择要包含在警报中的此组。例如、您可以对名称包含"`abc`"字符串的所有卷进行分组。

* * 排除 *
+
用于排除不希望触发警报的资源。例如，您可以排除名称包含 "`xyz` " 字符串的所有卷。

+
只有在选择特定资源类型的所有资源时、才会显示排除选项卡：例如、 <<All Volumes>> 或 <<All Volumes whose name contains '_xyz_'>>。

+
如果某个资源同时符合您指定的包含和排除规则，则排除规则优先于包含规则，并且不会为此事件生成警报。





== 事件

通过此区域，您可以选择要为其创建警报的事件。您可以根据特定严重性为事件创建警报，也可以为一组事件创建警报。

要选择多个事件，应在选择时按住 Ctrl 键。

* * 事件严重性 *
+
用于根据严重性类型选择事件，可以是 " 严重 " ， " 错误 " 或 " 警告 " 。

* * 事件名称包含 *
+
用于选择名称包含指定字符的事件。





== 操作

通过此区域，您可以指定要在触发警报时通知的用户。您还可以指定通知方法和通知频率。

* * 向这些用户发送警报 *
+
用于指定接收通知的用户的电子邮件地址或用户名。

+
如果修改为用户指定的电子邮件地址并重新打开警报进行编辑，则 " 名称 " 字段将显示为空，因为修改后的电子邮件地址不再映射到先前选择的用户。此外、如果您已从"管理/用户"页面修改选定用户的电子邮件地址、则修改后的电子邮件地址不会针对选定用户进行更新。

* * 通知频率 *
+
用于指定在事件被确认，解决或移至已废弃状态之前管理服务器发送通知的频率。

+
您可以选择以下通知方法：

+
** 仅通知一次
** 按指定频率通知
** 在指定时间范围内以指定频率通知


* * 问题描述 SNMP 陷阱 *
+
选中此框可指定是否应将 SNMP 陷阱发送到全局配置的 SNMP 主机。

* * 执行脚本 *
+
用于将自定义脚本添加到警报。此脚本会在生成警报时执行。





== 命令按钮

* * 保存 *
+
创建警报并关闭对话框。

* * 取消 *
+
丢弃所做的更改并关闭对话框。


