---
permalink: online-help/reference-dashboards-performance-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager性能信息板查看正在监控的所有集群的性能状态概况。如果Unified Manager无法与正在监控的集群进行通信、则Dashboards/Performance页面还会显示一条横幅消息。 
---
= 信息板/性能页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager性能信息板查看正在监控的所有集群的性能状态概况。如果Unified Manager无法与正在监控的集群进行通信、则Dashboards/Performance页面还会显示一条横幅消息。



== 概述

集群将根据严重性使用以下标准进行排序：

. 集群不可访问时。
. 集群具有一个或多个活动的严重性能事件(红色对象图标)。
. 集群具有一个或多个活动警告性能事件(黄色对象图标)。
. 如果集群没有活动性能事件(绿色对象图标)：集群按最高IOPS排序。


如果超过用户定义的性能阈值策略中的严重限制、则会生成严重事件。如果超过用户定义的性能阈值策略中的警告限制、或者超过系统定义的阈值策略或动态阈值、则会发送警告事件。

[NOTE]
====
排序顺序取决于活动(新事件或已确认事件)事件的总数、而不是包含事件的对象数量。例如、如果集群A有七个严重卷延迟事件、集群B具有两个严重卷延迟事件和两个严重节点IOPS事件(总共四个严重事件)、集群A (带有一个红色对象图标)将显示在列表的较高位置、尽管集群B具有两个红色对象图标。

====
对于每个集群、将显示以下常见监控事件类型：

* Storage Virtual Machine (SVM)、卷和LUN的延迟事件
* 节点和SVM的IOPS事件
* 节点和SVM的MBps事件
* 节点和聚合的已用性能容量事件
* 节点和聚合的利用率事件


Unified Manager可以接收其他存储对象和计数器的性能事件、例如聚合的MBps事件和卷的IOPS事件。如果集群具有这些类型的事件、则集群名称旁边的图标将指示警告(黄色)或严重(红色)事件。如果五个计数器面板图标中没有黄色或红色、则此图标可能表示存在事件、因为这些事件类型不适合现有计数器面板类别。

您可以单击对象图标以显示该对象的"性能清单"页面、在此可以查看此集群中此类型的所有对象。例如、单击某个卷图标将显示"性能/卷清单"页面、其中显示了选定集群中所有卷的列表、这些卷按性能从差到最佳的顺序进行排序。



== 性能计数器

每个集群有五个性能计数器、每个计数器显示在一个单独的面板中。此信息将在每个五分钟收集期之后自动更新：

|===
| 计数器 | Description 


 a| 
延迟
 a| 
显示集群响应客户端应用程序请求的速度、以每操作毫秒数(毫秒/操作)为单位。图标区域根据超过阈值设置的延迟值指示任何SVM、卷或LUN是否存在任何活动事件。



 a| 
IOPS
 a| 
显示存储系统的运行速度、以每秒输入/输出操作数(IOPS)为单位。

* 此图标区域根据超过阈值设置的IOPS数量指示任何节点或SVM是否存在任何活动事件。
* 底部区域显示了过去五分钟收集期间的总集群IOPS。




 a| 
MBps
 a| 
显示与集群之间传输的数据量、以每秒兆字节数(MBps)为单位。

* 此图标区域根据超过阈值设置的MBps值指示任何节点或SVM是否存在任何活动事件。
* 底部区域显示了过去五分钟收集期间的总集群吞吐量。




 a| 
已用性能容量
 a| 
显示任何节点或聚合是否过度使用其可用性能容量。

* 此图标区域根据超出阈值设置的已用性能容量值指示任何节点或聚合是否存在任何活动事件。
* 底部区域显示最繁忙节点和最繁忙聚合的最高已用性能容量值。


[NOTE]
====
只有在集群中的节点安装了ONTAP 9.0或更高版本的软件时、才会提供性能容量数据。

====


 a| 
利用率
 a| 
显示是否过度使用任何节点或聚合上的资源。

* 此图标区域将根据超出阈值设置的利用率值指示任何节点或聚合是否存在任何活动事件。
* 底部区域显示最繁忙节点和最繁忙聚合的最高利用率值。


|===
省略号(...)在标题区域中、表示当前正在收集性能数据。

对于具有性能事件的集群、您可以单击*查看集群详细信息*以显示性能集群登录页面、在此可以查看有关集群和其他存储对象的详细性能信息。



== 集群状态消息

如果Unified Manager管理的集群变得不可用、性能计数器上方将显示状态消息横幅。如果集群无法访问、则状态消息横幅右侧将显示一个*详细信息*按钮。通过单击状态消息中的*详细信息*按钮、您可以导航到"集群数据源"页面、其中显示了有关问题描述 的完整信息。在集群数据源页面上、您可以找到对导致集群不可用的问题描述 进行故障排除所需的数据。
