---
permalink: online-help/reference-group-action-volume-thresholds-section.html 
sidebar: sidebar 
keywords:  
summary: 通过group action-volume thresholds部分、您可以为卷配置组级别运行状况阈值。这些阈值将应用于组中的所有卷。在组级别配置卷运行状况阈值时、全局运行状况阈值不受影响。 
---
= Group action-volume thresholds部分
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过group action-volume thresholds部分、您可以为卷配置组级别运行状况阈值。这些阈值将应用于组中的所有卷。在组级别配置卷运行状况阈值时、全局运行状况阈值不受影响。

您可以为以下项配置卷运行状况阈值以配置组操作：

* Capacity
* 增长
* qtree配额
* Snapshot 副本
* 索引节点


如果没有为其中任何类别配置卷运行状况阈值、则会使用全局默认值。您可以为以下项设置运行状况阈值：

* Capacity
* 增长
* qtree配额
* Snapshot 副本
* 索引节点




== 容量部分

您可以为以下卷容量运行状况阈值设置条件：

* *空间接近全满*
+
指定将卷视为接近全满时的百分比：

+
** 默认值：80%
+
要使管理服务器生成事件、此阈值必须低于"卷全满"阈值。

** 生成的事件：卷接近全满
** 事件严重性：警告


* *空间已满*
+
指定将卷视为全满时的百分比：

+
** 默认值：90%
** 生成的事件：卷已满
** 事件严重性：错误


* *过量提交*
+
指定将卷视为过量使用时的百分比：

+
** 默认值：100%
** 生成的事件：卷已过量提交
** 事件严重性：错误






== 增长部分

您可以为卷增长设置以下运行状况阈值条件：

* *增长率*
+
指定在系统生成卷增长率异常事件之前将卷的增长率视为正常的百分比：

+
** 默认值：1%
** 生成的事件：卷增长率异常
** 事件严重性：警告


* *增长率敏感度*
+
指定应用于卷增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"卷增长率异常"事件。

+
增长率敏感度值越低、表示聚合对增长率的变化非常敏感。增长率敏感度的范围为1到5。

+
** 默认值：2






== qtree配额部分

您可以为卷配额设置以下运行状况阈值条件：

* *接近过量提交*
+
指定根据qtree配额将卷视为接近过量使用时的百分比：

+
** 默认值：95%
** 生成的事件：卷qtree配额接近过量提交
** 事件严重性：警告


* *过量提交*
+
指定根据qtree配额将卷视为过量使用时的百分比：

+
** 默认值：100%
** 生成的事件：卷qtree配额已过量提交
** 事件严重性：错误






== Snapshot副本部分

您可以为卷中的Snapshot副本设置以下运行状况阈值条件：

* * Snapshot预留已满*
+
指定将为Snapshot副本预留的空间视为已满时的百分比：

+
** 默认值：90%
** 生成的事件：卷Snapshot预留已满
** 事件严重性：错误


* *达到全满前的天数*
+
指定为Snapshot副本预留的空间达到容量全满前的剩余天数：

+
** 默认值：7
** 生成的事件：卷Snapshot预留达到全满前的天数
** 事件严重性：错误


* *计数*
+
指定卷上被视为过多的Snapshot副本的数量：

+
** 默认值：250
** 生成的事件：Snapshot副本太多
** 事件严重性：错误






== 索引节点部分

您可以为索引节点设置以下运行状况阈值条件：

* *接近全满*
+
指定将卷视为已占用其大部分索引节点的百分比：

+
** 默认值：80%
** 生成的事件：索引节点接近全满
** 事件严重性：警告


* *全满*
+
指定将卷视为已使用其所有索引节点时的百分比：

+
** 默认值：90%
** 生成的事件：索引节点已满
** 事件严重性：错误



