---
permalink: online-help/reference-capacity-all-volumes-view.html 
sidebar: sidebar 
keywords:  
summary: '通过"运行状况/卷容量和利用率"页面、您可以查看有关集群中卷的容量和利用率的信息。通过此信息、您可以了解可能的容量风险、并查看卷的已配置、已用和未用容量。此外、此信息还有助于您决定是否启用重复数据删除和精简配置等节省空间的功能。' 
---
= 运行状况/卷容量和利用率页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过"运行状况/卷容量和利用率"页面、您可以查看有关集群中卷的容量和利用率的信息。通过此信息、您可以了解可能的容量风险、并查看卷的已配置、已用和未用容量。此外、此信息还有助于您决定是否启用重复数据删除和精简配置等节省空间的功能。

使用*导出*按钮将所有受监控卷的详细信息导出为逗号分隔值 (`.csv`)文件。

* *集群*
+
集群名称。

* * SVM*
+
包含卷的Storage Virtual Machine (SVM)的名称。

* * 卷 *
+
卷名称。

* *总数据容量*
+
卷中的总数据容量(已用+可用)。

* *已用数据容量*
+
卷中的已用数据容量。

* *已用数据%*
+
卷中已用数据的百分比。

* *可用数据容量*
+
卷中的可用数据容量。

* *可用数据%*
+
卷中的可用数据容量百分比。

* *每日增长率%*
+
卷中每24小时发生一次的增长率。

* *全满天数*
+
在卷容量达到全满前的预计剩余天数。

* *空间全满阈值%*
+
卷中被视为已满的已用空间百分比。

* *空间接近全满阈值%*
+
卷中被视为接近全满的已用空间百分比。

* *增长率阈值%*
+
在系统生成"卷增长率异常"事件之前视为正常的卷增长率。

* *增长率敏感度阈值*
+
应用于卷增长率标准偏差的因子。如果增长率超过因子标准偏差、则会生成"卷增长率异常"事件。

* *达到全满前的天数阈值*
+
达到容量全满前的剩余天数。

* *快照溢出%*
+
Snapshot副本占用的数据空间百分比。

* * Snapshot预留已用容量*
+
卷中Snapshot副本使用的空间量。

* *已用Snapshot预留%*
+
卷中Snapshot副本使用的空间量(以百分比表示)。

* * Snapshot预留可用容量*
+
卷中可用于Snapshot副本的空间量。

* *快照预留可用%*
+
卷中可用于Snapshot副本的空间量、以百分比表示。

* * Snapshot预留总容量*
+
显示卷中的Snapshot副本总容量。

* * Snapshot副本预留全满阈值%*
+
将为Snapshot副本预留的空间视为已满时的百分比。

* * Snapshot副本计数阈值*
+
卷上被视为过多的Snapshot副本的数量。

* * Snapshot副本达到全满前的天数阈值*
+
为Snapshot副本预留的空间达到容量全满前的剩余天数。

* *索引节点数*
+
卷中的索引节点数。

* *索引节点利用率%*
+
卷中已用索引节点空间的百分比。

* *索引节点全满阈值%*
+
将卷视为已使用其所有索引节点的百分比。

* *索引节点接近全满阈值%*
+
将卷视为已占用其大部分索引节点的百分比。

* *配额已提交容量*
+
为卷中的配额预留的空间。

* *配额过量提交的容量*
+
在系统生成卷配额过量提交事件之前可用于配额的空间量。

* *配额过量提交阈值%*
+
卷上用于配额的空间被视为过量使用时的百分比。

* *配额接近过量提交阈值%*
+
将卷上用于配额的空间视为接近过量使用时的百分比。

* *快照自动删除*
+
启用还是禁用Snapshot副本自动删除。

* * 重复数据删除 *
+
卷是启用还是禁用了重复数据删除。

* *重复数据删除空间节省*
+
通过使用重复数据删除在卷中节省的空间量。

* * 数据压缩 *
+
卷是启用还是禁用了数据压缩。

* *压缩空间节省*
+
通过使用数据压缩在卷中节省的空间量。

* *缓存策略*
+
与选定卷关联的缓存策略。

+
此策略提供有关如何对卷执行Flash Pool缓存的信息。有关缓存策略的详细信息、请参见运行状况/卷清单页面。

* *缓存保留优先级*
+
用于保留缓存池的优先级。

* * 精简配置 *
+
是否为选定卷设置了空间保证。有效值为 " 是 " 和 " 否 "

* * 自动增长 *
+
卷的大小是否在空间不足时自动增长。

* * 空间保证 *
+
与卷关联的存储保证选项。

* *保护角色*
+
为卷设置的保护角色。

* * 状态 *
+
要导出的卷的状态。

* * SnapLock 类型 *
+
卷是SnapLock 卷还是非SnapLock卷。

* * SnapLock 到期日期*
+
SnapLock 到期日期。

* * 分层策略 *
+
为卷设置的分层策略。仅部署在启用了FabricPool的聚合上时有效。


