---
permalink: online-help/reference-events-report.html 
sidebar: sidebar 
keywords:  
summary: 通过事件报告、您可以查看有关特定时间段内事件趋势的信息。通过此信息、您可以将近期活动与过去的任何运营活动进行比较、例如配置更改、升级等。此信息还有助于您确定任何未完成的事件。 
---
= 事件报告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过事件报告、您可以查看有关特定时间段内事件趋势的信息。通过此信息、您可以将近期活动与过去的任何运营活动进行比较、例如配置更改、升级等。此信息还有助于您确定任何未完成的事件。



== 事件报告图表视图

事件报告以两种格式显示：

* 事件报告图表视图
* 事件报告表格视图


事件图表以两种格式显示：

* 事件严重性趋势(所有打开的事件)
* 事件状态趋势


此图表显示了一段时间内所有打开事件的事件严重性趋势。事件计数显示在垂直(y)轴上、日期显示在水平(x)轴上。您可以通过将光标置于特定点上方来查看图中特定点的详细信息。详细信息将显示事件严重性、特定严重性类型的事件数量以及事件日期。

显示的事件严重性类型包括"严重"、"错误"和"警告"。事件严重性通过不同的颜色进行区分。在同一日期、可以存在处于不同状态的相同数量的事件。

* *计数*
+
显示事件计数。

* * 日期 *
+
显示日期。x轴显示从事件发生到当前日期的数据。您可以单击并缩放图表以获取详细信息。



该图表显示了一段时间内每天的事件状态趋势。事件计数显示在垂直(y)轴上、日期显示在水平(x)轴上。详细信息将显示事件状态、特定状态的事件数量以及事件日期。

事件状态为"新增"、"已确认"和"已解决"。事件状态可通过不同的颜色来区分。

该图表以绿色条形图显示每天累积生成的新事件。在每天确认和解决已确认和已解决的事件时、这些事件的数量将显示为和。

图表中提供了缩放功能。您可以使用此功能缩放图表中的某个特定点、以提高清晰度。

* * 源 *
+
显示事件源。

* * 状态 *
+
显示事件的严重性。您可以筛选此列以显示特定严重性类型的事件。事件严重性类型为"严重"、"错误"或"警告"。

* * 状态 *
+
显示事件状态："新增"、"已确认"、"已解决"或"已废弃"。您可以筛选此列以显示特定状态的事件。

* * 事件 *
+
显示事件名称。

* * 触发时间 *
+
显示事件的生成时间。此时将显示时间和日期。

* * 未完成天数 *
+
显示从事件发生到其解决或指定为"已废弃"之间的天数。

* * 源类型 *
+
显示与事件关联的对象类型(例如Storage Virtual Machine (SVM)、卷或qtree)。

* *数据优先级*
+
根据存储对象的数据优先级显示标注类型。

* * 影响级别 *
+
显示事件是归类为意外事件、风险还是信息。

* * 影响区域 *
+
显示事件是容量、可用性、性能、保护还是配置事件。

* * 已分配给 *
+
显示将事件分配到的用户的名称。

* * 分配时间 *
+
显示将事件分配给用户的时间。

* * 注释 *
+
显示为事件添加的注释数。

* * 确认者 *
+
显示确认事件的用户的名称。如果事件未确认，则此字段为空。

* * 确认时间 *
+
显示自事件确认以来经过的时间。如果经过的时间超过一周、则时间戳将显示确认事件的时间。

* * 解决者 *
+
显示解决此事件的用户的名称。如果事件未解决，则此字段为空。

* * 解决时间 *
+
显示自事件解决以来经过的时间。如果经过的时间超过一周、则时间戳将显示事件的解决时间。

* * 已废弃时间 *
+
显示事件状态变为"已废弃"的时间。


