---
permalink: online-help/reference-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 使用此页面可查看卷的物理和逻辑属性列表。此信息可能有助于回答与性能相关的问题。此页面的标题取决于您查看的是FlexVol 卷还是FlexGroup 卷。 
---
= 性能/卷或性能/FlexGroup信息页面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用此页面可查看卷的物理和逻辑属性列表。此信息可能有助于回答与性能相关的问题。此页面的标题取决于您查看的是FlexVol 卷还是FlexGroup 卷。



== 卷属性

* * 类型 *
+
卷的类型：读写(rw)或数据保护(dp)。

* * 模式 *
+
卷的模式：FlexVol 或FlexGroup。

+
[NOTE]
====
Unified Manager的性能页面不支持无限卷。

====
* *集群*
+
此FlexVol 卷或FlexGroup 卷所属集群的名称。您可以单击此名称以在"性能/集群资源管理器"页面中显示集群详细信息。

* * 聚合 *
+
此FlexVol 卷所在聚合的名称或此FlexGroup 卷所在聚合的数量。

+
对于FlexVol 卷、您可以单击该名称以在"性能/聚合资源管理器"页面中显示聚合详细信息。对于FlexGroup 卷、您可以单击该数量以在"性能/聚合清单"页面中显示此FlexGroup 卷中使用的聚合。

* * Storage Virtual Machine*
+
此FlexVol 卷或FlexGroup 卷所属SVM的名称。您可以单击此名称以在"性能/SVM资源管理器"页面中显示SVM详细信息。

* * 分层策略 *
+
卷上设置的分层策略。只有当卷部署在FabricPool 聚合上时、此策略才会生效。可用策略包括：

+
** 无此卷的数据始终保留在性能层上。
** 仅Snapshot。只有Snapshot数据才会自动移动到云层。所有其他数据仍保留在性能层上。
** 备份。在数据保护卷上、传输的所有用户数据都从云层开始、但后续客户端读取可以通过发生原因 热数据移动到性能层。
** 自动。当ONTAP 确定此卷上的数据为"`Hot`"或"`Cold`"时、此数据会自动在性能层和云层之间移动。


* * RAID 类型 *
+
此卷所在聚合的性能层上使用的冗余类型。可能的类型：

+
** RAID0
** RAID4
** RAID-DP
** RAID-TEC


+
[NOTE]
====
对于FlexGroup 卷、将显示值"`不适用`"、因为成分卷可能位于不同RAID类型的聚合上。

====
* *容量(可用/总计)*
+
卷上可用的总存储空间(以GB为单位)以及当前可用的存储容量。


