---
permalink: online-help/task-moving-workloads-to-a-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用Unified Manager帮助确定不同高可用性\(HA\)对中节点上可用性能容量比当前运行工作负载的HA对更多的聚合。然后，您可以将选定卷移动到新 HA 对上的聚合。' 
---
= 将工作负载移动到其他 HA 对中的节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 帮助确定不同高可用性（ HA ）对中节点上可用性能容量比当前运行工作负载的 HA 对更多的聚合。然后，您可以将选定卷移动到新 HA 对上的聚合。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 集群必须至少包含两个 HA 对
+
如果集群中只有一个 HA 对，则无法使用此修复过程。

* 您必须已记录 HA 对中当前具有性能问题描述的两个节点的名称。
* 您必须已记录节点收到性能事件的日期和时间。
* 您必须已记录事件ID、例如"`p-sdt-clus1-nod-6982`"。
* Unified Manager 必须已收集和分析一个月或更长时间的性能数据。




== 关于此任务

将高性能工作负载移动到可用性能容量较多的节点上的聚合，可以提高两个节点上的工作负载的性能。此操作步骤 可帮助您确定以下资源、以便将高性能工作负载移动到其他HA对上可用性能容量较多的节点：

* 同一集群上不同 HA 对中可用性能容量最大的节点
* 新节点上可用性能容量最大的聚合
* 当前节点上性能最高的卷




== 步骤

. 确定属于同一集群上不同 HA 对的节点：
+
.. 在 * 事件详细信息 * 页面上，单击节点所在集群的名称。
+
集群详细信息将显示在 " 性能 / 集群登录 " 页面中。

.. 在 * 摘要 * 页面上，单击 * 受管对象 * 窗格中的 * 节点 * 。
+
此集群上的节点列表将显示在"性能/节点"页面中。

.. 记下与当前具有性能问题描述的 HA 对不同的 HA 对中的节点名称。


. 确定新 HA 对中可用性能容量最大的节点：
+
.. 在*性能/节点*页面上、单击*已用性能容量*列、按已用百分比对节点进行排序。
+
此选项将列出您可能希望将工作负载移动到的潜在节点。

.. 记下要将工作负载移动到的其他 HA 对上的节点名称。


. 确定新节点上可用性能容量最大的聚合：
+
.. 在*性能/节点*页面上、单击节点。
+
节点详细信息将显示在 " 性能 / 节点资源管理器 " 页面中。

.. 在 * 查看并比较 * 菜单中，选择 * 此节点上的聚合 * 。
+
此节点上的聚合将显示在网格中。

.. 单击 * 已用性能容量 * 列，按最少使用量对聚合进行排序。
+
此操作将列出您可能希望将工作负载移动到的潜在聚合。

.. 记下要将工作负载移动到的聚合的名称。


. 确定收到事件的节点中的高性能工作负载：
+
.. 返回到事件的 * 事件 * 详细信息页面。
.. 在 * 受影响的卷 * 字段中，单击第一个节点的卷数链接。
+
此时将显示"性能/卷"页面、其中包含该节点上经过筛选的卷列表。

.. 单击 * 总容量 * 列，按最大已分配空间对卷进行排序。
+
此操作将列出您可能要移动的潜在卷。

.. 记下要移动的卷的名称及其所在的当前聚合的名称。
.. 对属于此事件一部分的第二个节点执行步骤 4c 和 4d ，以确定您也要从该节点移动的可能卷。


. 将卷移动到新节点上已确定可用性能容量最大的聚合。
+
您可以使用OnCommand System Manager、OnCommand Workflow Automation 、ONTAP 命令或这些工具的组合来执行移动操作。





== 完成后

几天后，您可以检查是否从此节点或聚合收到相同类型的事件。
