---
permalink: online-help/task-identifying-trends-of-i-o-response-time-on-cluster-components.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用Unified Manager查看卷工作负载的所有受监控集群组件的性能趋势。随着时间的推移、您可以查看哪些组件的使用率最高、利用率最高的是读取请求还是写入请求、以及该使用率如何影响工作负载响应时间。 
---
= 确定集群组件上的I/O响应时间趋势
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager查看卷工作负载的所有受监控集群组件的性能趋势。随着时间的推移、您可以查看哪些组件的使用率最高、利用率最高的是读取请求还是写入请求、以及该使用率如何影响工作负载响应时间。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 您必须已确定要分析的卷或关联LUN的名称。
* 要显示30天的性能统计信息、Unified Manager必须已从集群中收集和分析至少30天的性能统计信息。




== 关于此任务

确定集群组件的性能趋势有助于管理员确定集群是过度使用还是未充分使用。

如果您正在查看事件详细信息页面、则可以单击卷的名称以直接转到"性能/卷详细信息"页面。



== 步骤

. 在*搜索*栏中、键入卷的名称。
+
卷的名称将显示在搜索结果中。

. 单击卷的名称。
+
此卷将显示在"性能/卷详细信息"页面上。

. 在历史数据图表上、单击*。30d*以显示最近30天的历史数据。
. 单击*按*细分数据。
. 在*延迟*下、选择"*集群组件"*和"*读取/写入延迟"*。
. 单击 * 提交 * 。
+
这两个图表均显示在延迟图表下方。

. 查看*集群组件*图表。
+
该图表按集群组件细分总响应时间。聚合的响应时间最长。

. 将*集群组件*图表与*延迟*图表进行比较。
+
"延迟"图表显示了总响应时间的峰值、这些峰值与聚合响应时间的峰值一致。在30天时间范围结束时、有几个站点超出了性能阈值。

. 查看*读取/写入延迟*图表。
+
该图表显示写入请求的响应时间比读取请求的响应时间要长、表示客户端应用程序等待处理其写入请求的时间比平常要长。

. 将*读取/写入延迟*图表与*延迟*图表进行比较。
+
与集群组件图表中的聚合对齐的总响应时间峰值也与读/写延迟图表中的写入值一致。管理员必须确定是否必须处理使用此工作负载的客户端应用程序、或者聚合是否已过度使用。


