---
permalink: online-help/task-creating-a-snapmirror-relationship-with-version-flexible-replication.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用版本灵活的复制创建 SnapMirror 关系。即使源卷和目标卷在不同版本的 ONTAP 下运行，也可以通过版本灵活的复制实施 SnapMirror 保护。 
---
= 使用版本灵活的复制创建 SnapMirror 关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用版本灵活的复制创建 SnapMirror 关系。即使源卷和目标卷在不同版本的 ONTAP 下运行，也可以通过版本灵活的复制实施 SnapMirror 保护。



== 开始之前

* 您必须具有OnCommand 管理员或存储管理员角色。
* 您必须已设置 Workflow Automation 。
* 源和目标 SVM 必须都启用了 SnapMirror 许可证。
* 源和目标 SVM 必须在支持版本灵活复制的 ONTAP 软件版本下运行。




== 关于此任务

使用版本灵活复制的 SnapMirror ，即使在并非所有存储都在一个 ONTAP 版本下运行的异构存储环境中，您也可以实施 SnapMirror 保护；但是，在采用版本灵活复制的 SnapMirror 下执行的镜像操作的速度不如在传统块复制 SnapMirror 下那样快。



== 步骤

. 显示要保护的卷的 * 配置保护 * 对话框。
+
** 如果正在查看"运行状况/卷"详细信息页面的"保护"选项卡、请右键单击具有要保护的卷名称的拓扑视图、然后从菜单中选择*保护*>* SnapMirror *。
** 如果正在查看"运行状况/卷"清单页面、请找到要保护的卷并右键单击该卷；然后从菜单中选择*保护*>* SnapMirror *。此时将显示配置保护对话框。


. 单击 * SnapMirror * 以查看 * SnapMirror * 选项卡。
. 完成 * 配置保护 * 对话框中的 * 目标信息 * 区域和 * 关系设置 * 区域。
+
如果您指定的目标 SVM 在低于所保护的源卷的 ONTAP 早期版本下运行，并且该早期版本支持版本灵活复制，则此任务会自动为 SnapMirror 配置版本灵活复制。

. 如果您指定的目标 SVM 在与源卷相同的 ONTAP 版本下运行，但您仍希望使用版本灵活的复制功能配置 SnapMirror ，请单击 * 高级 * 以启用版本灵活的复制，然后单击 * 应用 * 。
. 单击 * 应用 * 。
+
此时将返回到运行状况/卷详细信息页面。

. 单击*运行状况/卷*详细信息页面顶部的保护配置作业链接。
+
作业任务和详细信息将显示在保护/作业详细信息页面中。

. 在*保护/作业*详细信息页面中、单击*刷新*以更新与保护配置作业关联的任务列表和任务详细信息、并确定作业完成的时间。
. 作业任务完成后、单击浏览器上的*返回*以返回到*运行状况/卷*详细信息页面。
+
新关系将显示在运行状况/卷详细信息页面拓扑视图中。


