---
permalink: online-help/task-responding-to-user-defined-performance-threshold-events.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 Unified Manager 调查因性能计数器超过用户定义的警告或严重阈值而导致的性能事件。此外，您还可以使用 Unified Manager 检查集群组件的运行状况，以查看组件上检测到的最新运行状况事件是否导致性能事件。 
---
= 响应用户定义的性能阈值事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 调查因性能计数器超过用户定义的警告或严重阈值而导致的性能事件。此外，您还可以使用 Unified Manager 检查集群组件的运行状况，以查看组件上检测到的最新运行状况事件是否导致性能事件。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 必须存在新的或废弃的性能事件。




== 步骤

. 显示 * 事件 * 详细信息页面以查看有关事件的信息。
. 查看 * 问题描述 * ，其中介绍了导致事件的违反阈值的情况。
+
例如，消息 "`Latency value of 456 ms/op has triggered a warning event based on threshold setting of 400 ms/op` " 表示对象发生延迟警告事件。

. 将光标悬停在策略名称上方可显示有关触发事件的阈值策略的详细信息。
+
这包括策略名称，正在评估的性能计数器，必须违反才能视为严重或警告事件的计数器值以及计数器必须超过该值的持续时间。

. 记下 * 事件触发时间 * ，以便您可以调查是否同时发生了可能导致此事件的其他事件。
. 按照以下选项之一进一步调查事件，确定是否需要执行任何操作来解决性能问题：
+
|===
| 选项 | 可能的调查操作 


 a| 
单击源对象名称可显示该对象的 " 资源管理器 " 页面。
 a| 
通过此页面，您可以查看对象详细信息，并将此对象与其他类似存储对象进行比较，以查看其他存储对象是否同时具有性能问题描述。例如，查看同一聚合上的其他卷是否也具有性能问题描述。



 a| 
单击集群名称以显示集群摘要页面。
 a| 
通过此页面，您可以查看此对象所在集群的详细信息，以查看大致同时是否发生其他性能问题。

|===

