---
permalink: online-help/task-responding-to-a-system-defined-qos-policy-group-performance-event.html 
sidebar: sidebar 
keywords:  
summary: '如果工作负载吞吐量(IOPS、IOPS/TB或MBps)超过定义的ONTAP QoS策略设置且工作负载延迟正在受到影响、则Unified Manager将生成QoS策略警告事件。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。' 
---
= 响应 QoS 策略组性能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当工作负载吞吐量（ IOPS ， IOPS/TB 或 MBps ）超过定义的 ONTAP QoS 策略设置且工作负载延迟正在受到影响时， Unified Manager 将生成 QoS 策略警告事件。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 必须存在新的，已确认的或已废弃的性能事件。




== 关于此任务

如果工作负载吞吐量在前一小时的每个性能收集期间均超过定义的 QoS 策略设置，则 Unified Manager 将针对 QoS 策略违规生成警告事件。在每个收集期间，工作负载吞吐量可能会短时间超过 QoS 阈值，但 Unified Manager 仅会在图表上显示收集期间的 "`Average` " 吞吐量。因此，您可能会收到 QoS 事件，而工作负载的吞吐量可能并未超过图表中显示的策略阈值。

您可以使用 System Manager 或 ONTAP 命令管理策略组，包括以下任务：

* 为工作负载创建新策略组
* 在策略组中添加或删除工作负载
* 在策略组之间移动工作负载
* 更改策略组的吞吐量限制
* 将工作负载移动到其他聚合或节点




== 步骤

. 显示 * 事件 * 详细信息页面以查看有关事件的信息。
. 查看 * 问题描述 * ，其中介绍了导致事件的违反阈值的情况。
+
例如，消息 " vol1_NFS1 上的`IOPS 值为 1 ， 352 IOPS 已触发警告事件以确定工作负载的潜在性能问题` " 表示卷 vol1_NFS1 上发生 QoS 最大 IOPS 事件。

. 查看 * 事件信息 * 部分，了解有关事件发生时间以及事件处于活动状态的时间长度的更多详细信息。
+
此外，对于共享 QoS 策略吞吐量的卷或 LUN ，您可以看到占用 IOPS 或 MBps 最多的前三个工作负载的名称。

. 在 * 系统诊断 * 部分下，查看两个图表：一个是总平均 IOPS 或 MBps （取决于事件），一个是延迟。按这种方式排列时，您可以查看工作负载接近 QoS 最大限制时哪些集群组件对延迟影响最大。
+
对于共享 QoS 策略事件，吞吐量图表中会显示前三个工作负载。如果共享 QoS 策略的工作负载超过三个，则其他工作负载将添加到 "`其他工作负载` " 类别中。此外，延迟图表还会显示 QoS 策略中所有工作负载的平均延迟。

+
请注意，对于自适应 QoS 策略事件， IOPS 和 MBps 图表将显示 ONTAP 根据卷大小从分配的 IOPS/TB 阈值策略转换而来的 IOPS 或 MBps 值。

. 在 * 建议的操作 * 部分下，查看建议并确定应执行哪些操作以避免增加工作负载的延迟。
+
如果需要，请单击 * 帮助 * 按钮以查看有关可执行的建议操作的更多详细信息，以尝试解决性能事件。


