---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用"运行状况/卷"清单页面为同一Storage Virtual Machine (SVM\)上的一个或多个卷创建SnapVault 关系、以启用数据备份以进行保护。' 
---
= 从运行状况/卷清单页面创建SnapVault 保护关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用"运行状况/卷"清单页面为同一Storage Virtual Machine (SVM)上的一个或多个卷创建SnapVault 关系、以启用数据备份以实现保护目的。



== 开始之前

您必须具有OnCommand 管理员或存储管理员角色。



== 关于此任务

在以下情况下，不会显示 * 保护 * 菜单：

* 如果 RBAC 设置不允许执行此操作：例如，您只有操作员权限
* 当卷ID未知时：例如、当您具有集群间关系且尚未发现目标集群时




== 步骤

. 在左侧导航窗格中、单击*运行状况*>*卷*。
. 在*运行状况/卷*清单页面中、右键单击要保护的卷并选择*保护*。
+
或者、要在同一个Storage Virtual Machine (SVM)上创建多个保护关系、请在"运行状况/卷"清单页面中选择一个或多个卷、然后单击工具栏上的*保护*。

. 从菜单中选择 * SnapVault * 。
+
此时将启动配置保护对话框。

. 单击 * SnapVault * 以查看 * SnapVault * 选项卡并配置二级卷信息。
. 单击 * 高级 * 根据需要设置重复数据删除，数据压缩，自动增长和空间保证，然后单击 * 应用 * 。
. 完成 * 目标信息 * 区域和 * SnapVault * 选项卡中的 * 关系设置 * 区域。
. 单击 * 应用 * 。
+
此时将返回到运行状况/卷清单页面。

. 单击*运行状况/卷*清单页面顶部的保护配置作业链接。
+
如果仅创建一个保护关系、则会显示保护/作业详细信息页面；但是、如果要创建多个保护关系、则会显示与保护操作关联的所有作业的筛选列表。

. 执行以下操作之一：
+
** 如果只有一个作业，请单击 * 刷新 * 以更新与保护配置作业关联的任务列表和任务详细信息，并确定作业完成的时间。
** 如果您有多个作业：
+
... 单击作业列表中的作业。
... 单击 * 刷新 * 可更新与保护配置作业关联的任务列表和任务详细信息，并确定作业完成的时间。
... 使用 * 返回 * 按钮返回到筛选列表并查看其他作业。





