---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以对新的保护关系执行首次基线传输，或者如果关系已初始化，而您希望执行手动的计划外增量更新以立即传输数据，则可以更新此关系。 
---
= 通过运行状况/卷详细信息页面初始化或更新保护关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以对新的保护关系执行首次基线传输，或者如果关系已初始化，而您希望执行手动的计划外增量更新以立即传输数据，则可以更新此关系。



== 开始之前

* 您必须具有OnCommand 管理员或存储管理员角色。
* 您必须已设置 OnCommand Workflow Automation 。




== 步骤

. 从*运行状况/卷*详细信息页面的*保护*选项卡中、在拓扑中找到要初始化或更新的保护关系、然后右键单击它。
. 从菜单中选择 * 初始化 / 更新 * 。
+
或者，从 * 操作 * 菜单中，选择 * 关系 * > * 初始化 / 更新 * 以初始化或更新当前正在查看其详细信息的关系。

+
此时将显示初始化 / 更新对话框。

. 在 * 传输选项 * 选项卡中，选择传输优先级和最大传输速率。
. 单击 * 源 Snapshot 副本 * ；然后在 * Snapshot 副本 * 列中，单击 * 默认 * 。
+
此时将显示选择源 Snapshot 副本对话框。

. 如果要指定现有 Snapshot 副本而不是传输默认 Snapshot 副本，请单击 * 现有 Snapshot 副本 * 并从列表中选择一个 Snapshot 副本。
. 单击 * 提交 * 。
+
此时将返回到初始化 / 更新对话框。

. 如果选择了多个要初始化或更新的源，请为要指定现有 Snapshot 副本的下一个读 / 写源单击 * 默认 * 。
+
您不能为数据保护卷选择其他 Snapshot 副本。

. 单击 * 提交 * 以开始初始化或更新作业。
+
此时将启动初始化或更新作业、您将返回到运行状况/卷详细信息页面、页面顶部将显示一个作业链接。

. 单击*运行状况/卷*详细信息页面上的*查看作业*、跟踪每个初始化或更新作业的状态。
+
此时将显示经过筛选的作业列表。

. 单击每个作业以查看其详细信息。
. 单击浏览器上的后退箭头返回到*运行状况/卷*详细信息页面。
+
当所有作业任务成功完成后，初始化或更新操作完成。


