---
permalink: online-help/task-moving-workloads-to-a-different-node.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 Unified Manager 帮助确定比当前运行工作负载的节点繁忙的其他节点上的聚合，然后将选定卷移动到该聚合。将高性能工作负载移动到不太繁忙的节点上的聚合可以提高两个节点上的工作负载的性能。 
---
= 将工作负载移动到其他节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 帮助确定比当前运行工作负载的节点繁忙的其他节点上的聚合，然后将选定卷移动到该聚合。将高性能工作负载移动到不太繁忙的节点上的聚合可以提高两个节点上的工作负载的性能。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 您必须已记录当前具有性能问题描述的节点的名称。
* 您必须已记录节点收到性能事件的日期和时间。
* 您必须已记录事件ID、例如"`p-sdt-clus1-nod-6982`"。
* Unified Manager 必须已收集和分析一个月或更长时间的性能数据。




== 关于此任务

此操作步骤 可帮助您确定以下资源、以便将高性能工作负载移动到利用率较低的节点：

* 同一集群上可用性能容量最大的节点
* 新节点上可用性能容量最大的聚合
* 当前节点上性能最高的卷




== 步骤

. 确定集群中可用性能容量最大的节点：
+
.. 在 * 事件详细信息 * 页面上，单击节点所在集群的名称。
+
集群详细信息将显示在 " 性能 / 集群登录 " 页面中。

.. 在 * 摘要 * 选项卡上，单击 * 受管对象 * 窗格中的 * 节点 * 。
+
此时将显示此集群上的节点列表。

.. 单击 * 已用性能容量 * 列，按已用百分比最小对节点进行排序。
+
此选项将列出您可能希望将工作负载移动到的潜在节点。

.. 记下要将工作负载移动到的节点的名称。


. 确定新节点上利用率最低的聚合：
+
.. 在左侧导航窗格中、单击*性能*>*聚合*。
+
此时将显示"性能/聚合"页面。

.. 单击 * 筛选 * ，从左侧下拉菜单中选择 * 节点 * ，在文本字段中键入节点名称，然后单击 * 应用筛选器 * 。
+
此时将重新显示"性能/聚合"页面、其中列出了此节点上可用的聚合。

.. 单击 * 已用性能容量 * 列，按最少使用量对聚合进行排序。
+
此操作将列出您可能希望将工作负载移动到的潜在聚合。

.. 记下要将工作负载移动到的聚合的名称。


. 确定收到事件的节点中的高性能工作负载：
+
.. 返回到事件的 * 事件详细信息 * 页面。
.. 在 * 受影响的卷 * 字段中，单击卷数链接。
+
此时将显示"性能/卷"页面、其中包含该节点上经过筛选的卷列表。

.. 单击 * 总容量 * 列，按最大已分配空间对卷进行排序。
+
此操作将列出您可能要移动的潜在卷。

.. 记下要移动的卷的名称及其所在的当前聚合的名称。


. 将卷移动到新节点上已确定可用性能容量最大的聚合。
+
您可以使用OnCommand System Manager、OnCommand Workflow Automation 、ONTAP 命令或这些工具的组合来执行移动操作。





== 完成后

几天后，您可以检查是否从此节点或聚合收到相同类型的事件。
