---
permalink: online-help/task-moving-workloads-to-a-different-aggregate.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 Unified Manager 帮助确定比工作负载当前所在的聚合不太繁忙的聚合，然后将选定卷或 LUN 移动到该聚合。将高性能工作负载移动到不太繁忙的聚合或启用了闪存存储的聚合，可以提高工作负载的性能。 
---
= 将工作负载移动到其他聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 帮助确定比工作负载当前所在的聚合不太繁忙的聚合，然后将选定卷或 LUN 移动到该聚合。将高性能工作负载移动到不太繁忙的聚合或启用了闪存存储的聚合，可以提高工作负载的性能。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 您必须已记录当前具有性能问题描述的聚合的名称。
* 您必须已记录聚合收到事件的日期和时间。
* 您必须已记录事件ID、例如"` p-sdt-clus1-ag-2542`"。
* Unified Manager 必须已收集和分析一个月或更长时间的性能数据。




== 关于此任务

这些步骤可帮助您确定以下资源，以便将高性能工作负载移动到利用率较低的聚合：

* 同一集群上利用率较低的聚合
* 当前聚合上性能最高的卷




== 步骤

. 确定集群中利用率最低的聚合：
+
.. 在 * 事件 * 详细信息页面中，单击聚合所在集群的名称。
+
集群详细信息将显示在 " 性能 / 集群登录 " 页面中。

.. 在 * 摘要 * 页面上，单击 * 受管对象 * 窗格中的 * 聚合 * 。
+
此时将显示此集群上的聚合列表。

.. 单击 * 利用率 * 列，按利用率最低对聚合进行排序。
+
您还可以确定 * 可用容量 * 最大的聚合。此操作将列出您可能希望将工作负载移动到的潜在聚合。

.. 记下要将工作负载移动到的聚合的名称。


. 确定聚合中接收事件的高性能卷：
+
.. 单击具有性能问题描述的聚合。
+
聚合详细信息将显示在 " 性能 / 聚合资源管理器 " 页面中。

.. 从 * 时间范围 * 选择器中，选择 * 过去 30 天 * ，然后单击 * 应用范围 * 。
+
这样，您可以查看比默认 72 小时更长的性能历史记录。您希望移动一个持续使用大量资源的卷，而不仅仅是在过去 72 小时内。

.. 从 * 查看并比较 * 控件中，选择 * 此聚合上的卷 * 。
+
此时将显示此聚合上的 FlexVol 卷和 FlexGroup 成分卷列表。

.. 按最高MBps对卷进行排序、然后按最高IOPS对卷进行排序、以查看性能最高的卷。
.. 记下要移动到其他聚合的卷的名称。


. 将高性能卷移动到已确定利用率较低的聚合。
+
您可以使用OnCommand System Manager、OnCommand Workflow Automation 、ONTAP 命令或这些工具的组合来执行移动操作。





== 完成后

几天后，检查您是否从此节点或聚合收到相同类型的事件。
