---
permalink: online-help/task-creating-user-defined-performance-threshold-policies.html 
sidebar: sidebar 
keywords:  
summary: 您可以为存储对象创建性能阈值策略，以便在性能计数器超过特定值时发送通知。事件通知可确定集群遇到性能问题描述。 
---
= 创建用户定义的性能阈值策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以为存储对象创建性能阈值策略，以便在性能计数器超过特定值时发送通知。事件通知可确定集群遇到性能问题描述。



== 开始之前

您必须具有OnCommand 管理员角色。



== 关于此任务

您可以通过在创建阈值策略页面上输入阈值来创建性能阈值策略。您可以通过在此页面中定义所有策略值来创建新策略、也可以为现有策略创建一个副本并更改副本中的值(称为_clony_)。

数字的有效阈值为 0.001 到 10 ， 000 ， 000 ， 000 ，百分比的有效阈值为 0.001 到 100 ，已用性能容量百分比的有效阈值为 0.001 到 200 。

[NOTE]
====
当前版本提供的阈值用于在计数器值超过阈值设置时发送事件。您不能设置在计数器值低于阈值设置时发送事件的阈值。

====


== 步骤

. 在左侧导航窗格中、选择*配置*>*性能阈值*。
+
此时将显示配置/性能阈值页面。

. 根据您是要构建新策略还是要克隆类似策略并修改克隆的版本，单击相应的按钮。
+
|===
| 至 ... | 单击 


 a| 
创建新策略。
 a| 
* 创建 * 。



 a| 
克隆现有策略
 a| 
选择现有策略并单击 * 克隆 *

|===
+
此时将显示创建阈值策略页面或克隆阈值策略页面。

. 通过指定要为特定存储对象设置的性能计数器阈值来定义阈值策略：
+
.. 选择存储对象类型并为此策略指定名称和问题描述。
.. 选择要跟踪的性能计数器，并指定用于定义警告和严重事件的限制值。
+
您必须至少定义一个警告或一个严重限制。您无需同时定义这两种类型的限制。

.. 如果需要，选择二级性能计数器，并指定警告和严重事件的限制值。
+
如果包含二级计数器，则要求这两个计数器都超过限制值，然后才会违反阈值并报告事件。只能使用组合策略配置某些对象和计数器。

.. 选择要发送的事件必须违反限制值的持续时间。


+
克隆现有策略时，必须为此策略输入一个新名称。

. 单击 * 保存 * 以保存策略。
+
此时将返回配置/性能阈值页面。页面顶部会显示一条成功消息，确认已创建阈值策略，并提供指向该对象类型的 " 清单 " 页面的链接，以便您可以立即将新策略应用于存储对象。





== 完成后

如果此时要将新阈值策略应用于存储对象，则可以单击 * 转到对象类型 now* 链接以转到 " 清单 " 页面。
