---
settings:
  name: OnCommand Unified Manager 9.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  - name: Unified Manager
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Unified Manager 9.5文档
    url: "/index.html"
  - title: 发行说明
    url: "/release-notes.html"
  - title: 入门
    entries:
    - title: 快速开始安装 VMware vSphere
      url: "/qsg-vapp.html"
    - title: 快速开始安装 Linux
      url: "/qsg-linux.html"
    - title: 快速开始安装 Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 发行说明
      url: "/release-notes.html"
    - title: 快速开始安装 VMware vSphere
      url: qsg-vapp.html
    - title: 快速开始安装 Linux
      url: qsg-linux.html
    - title: 快速开始安装 Windows
      url: qsg-windows.html
  - title: 安装配置 Unified Manager
    links:
    - title: 在 VMware vSphere 系统上安装升级
      url: install/concept-installing-upgrading-and-removing-unified-manager-software-on-vmware-vsphere.html
    - title: 在 Linux 系统上安装升级
      url: install/concept-install-upgrade-and-remove-unified-manager-software.html
    - title: 在 Windows 系统上安装升级
      url: install/concept-installing-upgrading-and-removing-unified-manager-software.html
    - title: 配置 Unified Manager
      url: config/concept-configuring-unified-manager.html
  - title: 性能监控
    links:
    - title: 性能阈值
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: 集群性能
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
  - title: 更多资源
    links:
    - title: Unified Manager 视频
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager 博客
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English]
    - title: 最新版本Unified Manager的文档
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
