---
settings:
  name: OnCommand Unified Manager 9.5
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: OnCommand Unified Manager 9.5文档
    url: "/index.html"
  - title: 发行说明
    url: "/release-notes.html"
  - title: 入门
    entries:
    - title: 快速开始安装 VMware vSphere
      url: "/qsg-vapp.html"
    - title: 快速开始安装 Linux
      url: "/qsg-linux.html"
    - title: 快速开始安装 Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: 法律声明
    url: "/legal-notices.html"
