---
permalink: performance-checker/concept-what-the-expected-range-of-performance-is.html 
sidebar: sidebar 
keywords:  
summary: 预期值范围是指对特定时间的性能值上限和下限的预测。对于工作负载延迟，上限值构成性能阈值。当实际值超过性能阈值时、Unified Manager将触发性能事件警报。 
---
= 什么是预期性能范围
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
预期值范围是指对特定时间的性能值上限和下限的预测。对于工作负载延迟，上限值构成性能阈值。当实际值超过性能阈值时、Unified Manager将触发性能事件警报。

例如，在上午 9 ： 00 之间的正常工作时间下午 5 ： 00 ，大多数员工可能会在上午 9 ： 00 之间查看他们的电子邮件和上午 10 ： 30对电子邮件服务器的需求增加意味着在此期间后端存储上的工作负载活动会增加。员工可能会注意到电子邮件客户端的响应速度较慢。

中午 12 ： 00 至中午 12 ： 00 之间的午餐时间和下午 1 ： 00在下午 5 ： 00 之后的工作日结束时，大多数员工很可能会离开计算机。对电子邮件服务器的需求通常会减少，同时也会降低对后端存储的需求。或者，也可以在下午 5 ： 00 后开始计划工作负载操作，例如存储备份或病毒扫描并增加后端存储上的活动。

在几天内、工作负载活动的增加和减少决定了预期活动范围、工作负载的上限和下限。如果某个对象的实际工作负载活动超出上限或下限，并且在一段时间内保持在边界之外，则可能表示该对象已过度使用或未充分使用。



== 如何形成预期范围

Unified Manager必须至少收集3天的工作负载活动、然后才能开始分析、并在图形用户界面中显示I/O响应时间和操作的预期范围。所需的最低数据收集量不会考虑工作负载活动所发生的所有更改。收集前3天的活动后、Unified Manager将每24小时在每天中午12：00调整一次预期范围、以反映工作负载活动的变化并建立更准确的性能阈值。

[NOTE]
====
夏令时(DST)会更改系统时间、从而更改受监控工作负载的预期性能统计信息范围。Unified Manager会立即开始更正预期范围、大约需要15天才能完成。在此期间、您可以继续使用Unified Manager、但由于Unified Manager使用预期范围来检测事件、因此某些事件可能不准确。更改时间之前检测到的事件不受影响。将集群或Unified Manager服务器上的时间手动更改为较早的时间也会影响事件分析结果。

====