---
permalink: performance-checker/concept-cluster-configuration-and-performance-data-collection-activity.html 
sidebar: sidebar 
keywords:  
summary: 集群配置数据的收集间隔为 15 分钟。例如，添加集群后，需要 15 分钟才能在 Unified Manager UI 中显示集群详细信息。更改集群时也会应用此间隔。 
---
= 集群配置和性能数据收集活动
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
集群配置数据 _ 的收集间隔为 15 分钟。例如，添加集群后，需要 15 分钟才能在 Unified Manager UI 中显示集群详细信息。更改集群时也会应用此间隔。

例如，如果向集群中的 SVM 添加两个新卷，则在下一轮询间隔之后，用户界面中会显示这些新对象，最长可能为 15 分钟。

Unified Manager 每五分钟从所有受监控集群收集一次最新的性能统计信息。它会分析此数据以确定性能事件和潜在问题。它会保留30天的五分钟历史性能数据和390天的一小时历史性能数据。这样，您可以查看当月非常精细的性能详细信息以及长达一年的一般性能趋势。

收集轮询会偏移几分钟，以便不会同时发送每个集群的数据，这可能会影响性能。

下表介绍了 Unified Manager 执行的收集活动：

|===
| 活动 | 时间间隔 | Description 


 a| 
性能统计信息轮询
 a| 
每 5 分钟
 a| 
从每个集群收集实时性能数据。



 a| 
统计分析
 a| 
每 5 分钟
 a| 
每次统计信息轮询后， Unified Manager 都会将收集的数据与用户定义的阈值，系统定义的阈值和动态阈值进行比较。

如果违反了任何性能阈值， Unified Manager 将生成事件并向指定用户发送电子邮件（如果已配置）。



 a| 
配置轮询
 a| 
每 15 分钟
 a| 
从每个集群收集详细的清单信息，以确定所有存储对象（节点， SVM ，卷等）。



 a| 
总结
 a| 
每小时
 a| 
将最新收集的 12 个五分钟性能数据汇总为每小时平均值。

每小时平均值将在某些UI页面中使用、并保留390天。



 a| 
预测分析和数据删减
 a| 
每天午夜后
 a| 
分析集群数据，为未来 24 小时的卷延迟和 IOPS 建立动态阈值。

从数据库中删除 30 天之前的任何五分钟性能数据。



 a| 
数据删减
 a| 
每天凌晨 2 点后
 a| 
从数据库中删除超过390天的任何事件和动态阈值。



 a| 
数据删减
 a| 
每天凌晨 3 ： 30 后
 a| 
从数据库中删除超过390天的任何一小时性能数据。

|===