---
permalink: performance-checker/concept-understanding-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: '通过 " 计数器图表 " 窗格中的图表，您可以查看和比较根对象以及从相关对象网格中添加的对象的性能数据。这有助于您了解性能趋势，隔离和解决性能问题。' 
---
= 了解计数器图表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 " 计数器图表 " 窗格中的图表，您可以查看和比较根对象以及从相关对象网格中添加的对象的性能数据。这有助于您了解性能趋势，隔离和解决性能问题。

默认情况下、显示的计数器图表包括事件、延迟、IOPS和MBps。您可以选择显示的可选图表包括利用率，已用性能容量，可用 IOPS ， IOPS/TB 和缓存未命中率。此外，您还可以选择查看 " 延迟 " ， "IOPS" ， "MBps" 和 " 已用性能容量 " 图表的总值或细分值。

默认情况下，性能资源管理器会显示某些计数器图表；存储对象是否支持全部计数器图表。如果不支持计数器、则计数器图表为空、并显示消息 `Not applicable for <object>` 将显示

这些图表显示根对象以及您在 " 比较 " 窗格中选择的所有对象的性能趋势。每个图表中的数据排列如下：

* * X 轴 *
+
显示指定的时间段。如果未指定时间范围，则默认值为过去 72 小时的时间段。

* * Y 轴 *
+
显示选定对象的唯一计数器单位。



趋势线颜色与 " 正在比较 " 窗格中显示的对象名称颜色匹配。您可以将光标置于任何趋势线上的某个点上方，以查看该点的时间和值详细信息。

如果要调查图表中的特定时间段，可以使用以下方法之一：

* 使用 * <* 按钮展开 " 计数器图表 " 窗格以覆盖页面宽度。
* 使用光标（当它过渡到放大镜时）选择图表中某个时间范围的一部分以突出显示并放大该区域。您可以单击重置图表缩放以将图表恢复为默认时间范围。
* 使用 * 缩放视图 * 按钮可显示一个大型单计数器图表，其中包含扩展的详细信息和阈值指示器。


[NOTE]
====
有时，趋势线中会显示空隙。差距意味着 Unified Manager 无法从存储系统收集性能数据，或者 Unified Manager 可能已关闭。

====