---
permalink: performance-checker/concept-collecting-data-and-monitoring-workload-performance.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 每 5 分钟收集并分析一次工作负载活动，以确定性能事件，并每 15 分钟检测一次配置更改。它最多保留30天的5分钟历史性能和事件数据、并使用这些数据预测所有受监控工作负载的预期范围。 
---
= 收集数据并监控工作负载性能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 每 5 分钟收集并分析一次工作负载活动，以确定性能事件，并每 15 分钟检测一次配置更改。它最多保留30天的5分钟历史性能和事件数据、并使用这些数据预测所有受监控工作负载的预期范围。

[NOTE]
====
本章介绍动态阈值的工作原理以及如何使用它们来帮助监控工作负载性能。本章不适用于因用户定义或系统定义的性能阈值违规而导致的统计信息或事件。

====
Unified Manager必须至少收集3天的工作负载活动、然后才能开始分析、并在"性能/卷详细信息"页面和"事件详细信息"页面上显示I/O响应时间和操作的预期范围。收集此活动时、预期范围不会显示工作负载活动发生的所有更改。收集3天的活动后、Unified Manager将每24小时在每天中午12：00调整一次预期范围、以反映工作负载活动的变化并建立更准确的性能阈值。

在Unified Manager监控卷的前4天内、如果自上次数据收集以来已超过24小时、则"性能/卷详细信息"页面上的图表将不会显示该卷的预期范围。上次收集之前检测到的事件仍然可用。

[NOTE]
====
夏令时(DST)会更改系统时间、从而更改受监控工作负载的预期性能统计信息范围。Unified Manager会立即开始更正预期范围、大约需要15天才能完成。在此期间、您可以继续使用Unified Manager、但由于Unified Manager使用预期范围来检测事件、因此某些事件可能不准确。更改时间之前检测到的事件不受影响。将集群或Unified Manager服务器上的时间手动更改为较早的时间也会影响事件分析结果。

====