---
permalink: performance-checker/concept-what-a-data-continuity-collection-cycle-is.html 
sidebar: sidebar 
keywords:  
summary: 数据连续性收集周期会在实时集群性能收集周期之外检索性能数据，默认情况下，该收集周期每五分钟运行一次。通过数据连续性收集， Unified Manager 可以填补因无法收集实时数据而出现的统计数据空白。 
---
= 什么是数据连续性收集周期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
数据连续性收集周期会在实时集群性能收集周期之外检索性能数据，默认情况下，该收集周期每五分钟运行一次。通过数据连续性收集， Unified Manager 可以填补因无法收集实时数据而出现的统计数据空白。

只有使用ONTAP 8.3.1或更高版本软件安装的集群才支持数据连续性收集。

发生以下事件时， Unified Manager 将对历史性能数据执行数据连续性收集轮询：

* 集群最初会添加到 Unified Manager 中。
+
Unified Manager 收集过去 15 天的历史性能数据。这样，您可以在添加集群几小时后查看两周的集群历史性能信息。

+
此外，如果存在系统定义的阈值事件，则会报告上一个时间段的事件。

+
[NOTE]
====
当前不会收集15天的历史卷统计信息。

====
* 当前性能数据收集周期不会按时完成。
+
如果实时性能轮询超出五分钟收集周期，则会启动数据连续性收集周期来收集缺少的信息。如果不进行数据连续性收集，则会跳过下一个收集周期。

* Unified Manager 在一段时间内无法访问，然后恢复联机，如以下情况：
+
** 已重新启动。
** 在软件升级期间或创建备份文件时，它已关闭。
** 已修复网络中断。


* 集群在一段时间内无法访问，然后恢复联机，如以下情况：
+
** 已修复网络中断。
** 广域网连接速度较慢，延迟了正常收集性能数据的时间。




数据连续性收集周期最多可收集 24 小时的历史数据。如果 Unified Manager 停机超过 24 小时，则 UI 页面中会显示性能数据缺失。

数据连续性收集周期和实时数据收集周期不能同时运行。数据连续性收集周期必须在启动实时性能数据收集之前完成。如果需要通过数据连续性收集收集一小时以上的历史数据、则性能信息板顶部将显示该集群的横幅消息。
