---
permalink: performance-checker/reference-types-of-performance-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 标准性能图表可显示选定存储对象的计数器值。每个细分计数器图表都会显示按读取，写入和其他类别细分的总值。此外，在缩放视图中显示图表时，某些细分计数器图表会显示更多详细信息。 
---
= 性能计数器图表的类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
标准性能图表可显示选定存储对象的计数器值。每个细分计数器图表都会显示按读取，写入和其他类别细分的总值。此外，在缩放视图中显示图表时，某些细分计数器图表会显示更多详细信息。

下表显示了可用的性能计数器图表。

|===
| 可用图表 | 绘制问题描述图表 


 a| 
事件
 a| 
显示与根对象的统计图表相关的严重，错误，警告和信息事件。除了显示性能事件之外，还会显示运行状况事件，以便全面了解可能影响性能的原因。



 a| 
延迟—总计
 a| 
响应应用程序请求所需的毫秒数。请注意、平均延迟值是I/O加权值。



 a| 
延迟—细分
 a| 
与"延迟总计"中显示的信息相同、但性能数据会按读取、写入和其他延迟进行细分。只有当选定对象为SVM、节点、聚合、卷、LUN时、此图表选项才适用。或命名空间。



 a| 
延迟—集群组件
 a| 
与"延迟总计"中显示的信息相同、但性能数据按集群组件划分为延迟。只有当选定对象为卷时、此图表选项才适用。



 a| 
IOPS —总计
 a| 
每秒处理的输入 / 输出操作数。



 a| 
IOPS —细分
 a| 
与 "IOPS 总数 " 中显示的信息相同，但性能数据按读取，写入和其他 IOPS 进行细分。如果在缩放视图中显示、则卷图表将显示QoS最小和最大吞吐量值(如果已在ONTAP 中配置)。

只有当选定对象为 SVM ，节点，聚合，卷， LUN 时，此图表选项才适用。 或命名空间。



 a| 
IOPS —协议
 a| 
与 "IOPS 总数 " 中显示的信息相同，但性能数据会分别显示为 CIFS ， NFS ， FCP ， NVMe 和 iSCSI 协议流量的各个图表。只有当选定对象为 SVM 时，此图表选项才适用。



 a| 
IOPS/TB —总计
 a| 
根据工作负载占用的总空间，每秒处理的输入 / 输出操作数（以 TB 为单位）。此计数器也称为I/O密度、用于测量给定存储容量可提供的性能。如果在缩放视图中显示、则卷图表将显示QoS预期和峰值吞吐量值(如果在ONTAP 中配置)。

只有当选定对象为卷时，此图表选项才适用。



 a| 
MBps—总计
 a| 
每秒与对象之间传输的数据 MB 数。



 a| 
MBps—细分
 a| 
与MBps图表中显示的信息相同、但MBps数据会按磁盘读取、Flash Cache读取、写入等进行细分。如果在缩放视图中显示、则卷图表会显示QoS最大吞吐量值(如果在ONTAP 中配置)。

只有当选定对象为 SVM ，节点，聚合，卷， LUN 时，此图表选项才适用。 或命名空间。

[NOTE]
====
只有在节点中安装了 Flash Cache 模块时，才会显示节点的 Flash Cache 数据。

====


 a| 
已用性能容量 - 总计
 a| 
节点或聚合占用的性能容量百分比。

[NOTE]
====
只有在集群中的节点安装了ONTAP 9.0或更高版本的软件时、才会提供性能容量数据。

====


 a| 
已用性能容量—细分
 a| 
已用性能容量数据分为用户协议和系统后台进程。此外，还会显示可用性能容量。



 a| 
Available IOPS —总计
 a| 
此对象上当前可用（空闲）的每秒输入 / 输出操作数。此数字是从 Unified Manager 计算的对象可以执行的总 IOPS 中减去当前使用的 IOPS 的结果。只有当选定对象为节点或聚合时，此图表选项才适用。

[NOTE]
====
只有当集群中的节点安装了ONTAP 9.0或更高版本的软件时、才会显示可用的IOPS数据。

====


 a| 
利用率 - 总计
 a| 
正在使用的对象的可用资源百分比。利用率用于指示节点的节点利用率、聚合的磁盘利用率以及端口的带宽利用率。只有当选定对象是节点、聚合或端口时、此图表选项才适用。



 a| 
缓存未命中率—总计
 a| 
从磁盘返回而不是从缓存返回的客户端应用程序读取请求的百分比。只有当选定对象为卷时，此图表选项才适用。

|===