---
permalink: performance-checker/reference-what-performance-metrics-can-be-monitored-using-thresholds.html 
sidebar: sidebar 
keywords:  
summary: '某些常见性能计数器(例如IOPS和MBps)可以为所有存储对象设置阈值。还有一些计数器只能为特定存储对象设置阈值。' 
---
= 可以使用阈值跟踪哪些性能计数器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
某些常见性能计数器(例如IOPS和MBps)可以为所有存储对象设置阈值。还有一些计数器只能为特定存储对象设置阈值。



== 可用性能计数器

|===
| 存储对象 | 性能计数器 | Description 


 a| 
集群
 a| 
IOPS
 a| 
集群每秒处理的平均输入 / 输出操作数。



 a| 
MBps
 a| 
此集群之间每秒传输的数据的平均 MB 数。
 a| 
Node



 a| 
IOPS
 a| 
节点每秒处理的平均输入 / 输出操作数。
 a| 
MBps



 a| 
此节点之间每秒传输的数据的平均 MB 数。
 a| 
延迟
 a| 
节点响应应用程序请求所用的平均毫秒数。



 a| 
利用率
 a| 
正在使用的节点 CPU 和 RAM 的平均百分比。
 a| 
已用性能容量



 a| 
节点占用的性能容量的平均百分比。
 a| 
已用性能容量—接管
 a| 
节点占用的性能容量及其配对节点的性能容量的平均百分比。



 a| 
聚合
 a| 
IOPS
 a| 
聚合每秒处理的平均输入 / 输出操作数。



 a| 
MBps
 a| 
此聚合之间每秒传输的数据的平均 MB 数。
 a| 
延迟



 a| 
聚合响应应用程序请求所用的平均毫秒数。
 a| 
利用率
 a| 
正在使用的聚合磁盘的平均百分比。



 a| 
已用性能容量
 a| 
聚合占用的性能容量的平均百分比。
 a| 
Storage Virtual Machine （ SVM ）



 a| 
IOPS
 a| 
SVM 每秒处理的平均输入 / 输出操作数。
 a| 
MBps



 a| 
此 SVM 之间每秒传输的数据的平均 MB 数。
 a| 
延迟
 a| 
SVM 响应应用程序请求所用的平均毫秒数。



 a| 
Volume
 a| 
IOPS
 a| 
卷每秒处理的平均输入 / 输出操作数。



 a| 
MBps
 a| 
此卷之间每秒传输的数据的平均 MB 数。
 a| 
延迟



 a| 
卷响应应用程序请求所用的平均毫秒数。
 a| 
缓存未命中率
 a| 
从卷返回而不是从缓存返回的客户端应用程序读取请求的平均百分比。



 a| 
LUN
 a| 
IOPS
 a| 
LUN 每秒处理的平均输入 / 输出操作数。



 a| 
MBps
 a| 
此 LUN 之间每秒传输的数据的平均 MB 数。
 a| 
延迟



 a| 
LUN 响应应用程序请求所用的平均毫秒数。
 a| 
命名空间
 a| 
IOPS



 a| 
命名空间每秒处理的平均输入 / 输出操作数。
 a| 
MBps
 a| 
此命名空间之间每秒传输的数据的平均 MB 数。



 a| 
延迟
 a| 
命名空间响应应用程序请求所用的平均毫秒数。
 a| 
Port



 a| 
带宽利用率
 a| 
正在使用的端口可用带宽的平均百分比。
 a| 
MBps



 a| 
此端口之间每秒传输的数据的平均 MB 数。
 a| 
逻辑接口(LIF)
 a| 
MBps

|===
[NOTE]
====
只有在集群中的节点安装了ONTAP 9.0或更高版本的软件时、才会提供性能容量数据。

====