---
permalink: performance-checker/task-configuring-a-connection-between-a-unified-manager-server-and-an-external-data-provider.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 可以将集群性能数据发送到外部服务器。您可以指定发送的统计数据的类型以及发送数据的间隔。 
---
= 配置从 Unified Manager 服务器到外部数据提供程序的连接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 可以将集群性能数据发送到外部服务器。您可以指定发送的统计数据的类型以及发送数据的间隔。



== 开始之前

* 您必须拥有有权登录到 Unified Manager 服务器维护控制台的用户 ID 。
* 您必须具有有关外部数据提供程序的以下信息：
+
** 服务器名称或 IP 地址（ IPv4 或 IPv6 ）
** 服务器默认端口（如果未使用默认端口 2003 ）


* 您必须已配置远程服务器和第三方软件，以便从 Unified Manager 服务器接收统计数据。
* 您必须知道要发送哪组统计信息：
+
** performation_indicator ：性能监控统计信息
** resource_utilization ：资源利用率和性能监控统计信息
** dry_down ：所有统计信息


* 您必须知道要传输统计信息的时间间隔： 5 ， 10 或 15 分钟
+
默认情况下， Unified Manager 每 5 分钟收集一次统计信息。如果将传输间隔设置为 10 （或 15 ）分钟，则每次传输期间发送的数据量是使用默认 5 分钟间隔时的两（或三）倍。

+
[NOTE]
====
如果将 Unified Manager 性能收集间隔更改为 10 或 15 分钟，则必须更改传输间隔，使其等于或大于 Unified Manager 收集间隔。

====




== 关于此任务

您可以在一个 Unified Manager 服务器和一个外部数据提供程序服务器之间配置连接。



== 步骤

. 以维护用户身份登录到 Unified Manager 服务器的维护控制台。
+
此时将显示 Unified Manager 维护控制台提示符。

. 在维护控制台中，键入 * 外部数据提供程序 * 菜单选项的编号。
+
此时将显示外部服务器连接菜单。

. 键入 * 添加 / 修改服务器连接 * 菜单选项的编号。
+
此时将显示当前服务器连接信息。

. 出现提示时、键入 `y` 以继续。
. 出现提示时，输入目标服务器的 IP 地址或名称以及服务器端口信息（如果与默认端口 2003 不同）。
. 出现提示时、键入 `y` 以验证您输入的信息是否正确。
. 按任意键返回到外部服务器连接菜单。
. 键入 * 修改服务器配置 * 菜单选项的编号。
+
此时将显示当前服务器配置信息。

. 出现提示时、键入 `y` 以继续。
. 出现提示时，输入要发送的统计信息类型，发送统计信息的时间间隔以及是否要立即启用统计信息传输：
+
|===
| 针对 ... | 输入 ... 


 a| 
统计信息组 ID
 a| 
`0` —performance"指示符(默认)

`1` —resource_utilization

`2` -展开



 a| 
供应商标记
 a| 
用于将统计信息存储在外部服务器上的文件夹的描述性名称。"`netapp-performance` " 是默认名称，但您可以输入其他值。

通过使用点分表示法，您可以定义分层文件夹结构。例如、输入 `stats.performance.netapp` 统计信息位于*统计信息*>*性能*>* NetApp *中。



 a| 
传输间隔
 a| 
`5` (默认)、 `10`或 `15` minutes



 a| 
启用 / 禁用
 a| 
`0` —禁用

`1` -启用(默认)

|===
. 出现提示时、键入 `y` 以验证您输入的信息是否正确。
. 按任意键返回到外部服务器连接菜单。
. Type `x` 以退出维护控制台。




== 结果

配置连接后，选定性能数据将按指定的时间间隔发送到目标服务器。要在Graphite中显示指标、需要几分钟的时间。您可能需要刷新浏览器才能查看指标层次结构中的新指标。
