---
permalink: performance-checker/task-responding-to-a-system-defined-node-resources-overutilized-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 如果单个节点的运行效率超过其运行效率上限，则 Unified Manager 会生成节点资源过度利用警告事件，从而可能影响工作负载延迟。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。 
---
= 响应节点资源过度利用的性能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果单个节点的运行效率超过其运行效率上限，则 Unified Manager 会生成节点资源过度利用警告事件，从而可能影响工作负载延迟。通过这些系统定义的事件，可以在许多工作负载受到延迟影响之前更正潜在的性能问题。



== 开始之前

* 您必须具有操作员、OnCommand 管理员或存储管理员角色。
* 必须存在新的或废弃的性能事件。




== 关于此任务

Unified Manager 可通过查找性能容量超过 100% 且持续 30 分钟以上的节点，针对节点资源过度利用策略违规生成警告事件。

您可以使用 System Manager 或 ONTAP 命令更正此类型的性能问题描述，其中包括以下任务：

* 创建 QoS 策略并将其应用于过度使用系统资源的任何卷或 LUN
* 降低已应用工作负载的策略组的 QoS 最大吞吐量限制
* 将工作负载移动到其他聚合或节点
* 通过向节点添加磁盘或升级到 CPU 速度更快且 RAM 更多的节点来增加容量




== 步骤

. 显示 * 事件 * 详细信息页面以查看有关事件的信息。
. 查看 * 问题描述 * ，其中介绍了导致事件的违反阈值的情况。
+
例如，消息 "`Perf.simplicity-02 上 139% 的已用容量值触发了一个警告事件，以确定数据处理单元中的潜在性能问题。` 表示节点 simplication-02 上的性能容量已过度使用，并影响节点性能。

. 在 * 系统诊断 * 部分下，查看三个图表：一个用于显示节点上已用性能容量，一个用于显示排名靠前的工作负载所使用的平均存储 IOPS ，一个用于显示排名靠前的工作负载上的延迟。通过这种方式进行排列，您可以查看哪些工作负载是节点上延迟的发生原因。
+
通过将光标移动到 IOPS 图表上方，您可以查看哪些工作负载应用了 QoS 策略，哪些未应用 QoS 策略。

. 在 * 建议的操作 * 部分下，查看建议并确定应执行哪些操作以避免增加工作负载的延迟。
+
如果需要，请单击 * 帮助 * 按钮以查看有关可执行的建议操作的更多详细信息，以尝试解决性能事件。


