---
permalink: health-checker/concept-how-group-rules-work-for-groups.html 
sidebar: sidebar 
keywords:  
summary: '组规则是您定义的一个标准、用于使存储对象(卷、集群或SVM\)能够包含在特定组中。您可以使用条件组或条件为组定义组规则。' 
---
= 组规则如何用于组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
组规则是您定义的一个标准，用于将存储对象（卷，集群或 SVM ）包含在特定组中。您可以使用条件组或条件为组定义组规则。

* 您必须将组规则与组关联。
* 您必须为组规则关联一个对象类型；一个组规则只关联一个对象类型。
* 在每个监控周期之后，或者在创建，编辑或删除规则时，系统会从组中添加或删除存储对象。
* 一个组规则可以具有一个或多个条件组，每个条件组可以具有一个或多个条件。
* 根据您创建的组规则，存储对象可以属于多个组。




== 条件

您可以创建多个条件组，每个条件组可以具有一个或多个条件。您可以将组规则中定义的所有条件组应用于组，以指定组中包含的存储对象。

条件组中的条件使用逻辑 AND 执行。必须满足条件组中的所有条件。创建或修改组规则时，系统会创建一个条件，此条件仅应用，选择和分组满足条件组中所有条件的存储对象。如果要缩小要包含在一个组中的存储对象的范围，可以在一个条件组中使用多个条件。

您可以使用以下操作数和运算符并指定所需值来创建存储对象的条件。

|===
| 存储对象类型 | 适用的操作数 


 a| 
Volume
 a| 
* 对象名称
* 所属集群名称
* 所属 SVM 名称
* 标注




 a| 
SVM
 a| 
* 对象名称
* 所属集群名称
* 标注




 a| 
集群
 a| 
* 对象名称
* 标注


|===
如果选择标注作为任何存储对象的操作数，则可以使用 "`is` " 运算符。对于所有其他操作数，您可以选择 "`is` " 或 "`contains` " 作为运算符。

* 操作数
+
Unified Manager 中的操作数列表会根据选定对象类型而发生变化。此列表包括您在 Unified Manager 中定义的对象名称，所属集群名称，所属 SVM 名称和标注。

* 运算符
+
操作符列表会根据为条件选择的操作数而发生变化。Unified Manager 中支持的运算符为 "`is` " 和 "`contains` " 。

+
如果选择 "`is` " 运算符，则会评估条件，以确定操作数值与为选定操作数提供的值是否完全匹配。

+
如果选择 "`contains` " 运算符，则系统会评估此条件以满足以下条件之一：

+
** 该操作数值与为选定操作数提供的值完全匹配
** 操作数值包含为选定操作数提供的值


* 价值
+
值字段会根据选定操作数发生变化。





== 包含条件的组规则示例

考虑具有以下两个条件的卷的条件组：

* 名称包含 "`vol` "
* SVM 名称为 `data_sVM`


此条件组会选择名称中包含 "`vol` " 且托管在名称为 " `data_sVM` " 的 SVM 上的所有卷。



== 条件组

条件组使用逻辑或执行，然后应用于存储对象。存储对象必须满足要包括在组中的一个条件组。所有条件组的存储对象将合并在一起。您可以使用条件组来扩大要包含在组中的存储对象的范围。



== 包含条件组的组规则示例

请考虑为一个卷设置两个条件组，每个条件组包含以下两个条件：

* 条件组 1
+
** 名称包含 "`vol` "
** SVM 名称为 `data_sVM` 条件组 1 会选择名称中包含 "`vol` " 且托管在名称为 `data_sVM` 的 SVM 上的所有卷。


* 条件组 2.
+
** 名称包含 "`vol` "
** data-priority 的标注值为 "`critical` " 条件组 2 会选择名称中包含 "`vol` " 且使用数据优先级标注值标注为 "`critical` " 的所有卷。




如果将包含这两个条件组的组规则应用于存储对象，则会将以下存储对象添加到选定组：

* 名称中包含 "`vol` " 且托管在名称为 " `data_svm` " 的 SVM 上的所有卷。
* 名称中包含 "`vol` " 且标注了数据优先级标注值 "`Critical` " 的所有卷。

