---
permalink: health-checker/concept-common-unified-manager-administrative-workflows-and-tasks.html 
sidebar: sidebar 
keywords:  
summary: 与Unified Manager关联的一些常见管理工作流和任务包括：选择要监控的存储集群；诊断对数据可用性、容量和保护产生不利影响的情况；创建保护关系；还原丢失的数据；配置和管理无限卷；根据需要捆绑诊断数据并将其发送给技术支持。 
---
= 常见 Unified Manager 运行状况工作流和任务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
与Unified Manager关联的一些常见管理工作流和任务包括：选择要监控的存储集群；诊断对数据可用性、容量和保护产生不利影响的情况；创建保护关系；还原丢失的数据；配置和管理无限卷；根据需要捆绑诊断数据并将其发送给技术支持。

通过 Unified Manager ，存储管理员可以查看信息板，评估受管存储集群的整体容量，可用性和保护运行状况，然后快速确定，找到，诊断和分配可能出现的任何特定问题以解决问题。

与集群、Storage Virtual Machine (SVM)、卷、FlexGroup 卷或保护关系相关的最重要问题会影响受管存储对象的存储容量、数据可用性或保护可靠性、这些问题会显示在Dashboards/Overview页面上的系统运行状况图和事件中。确定严重问题后、此页面将提供相应的链接来支持相应的故障排除工作流。

Unified Manager 还可以包含在包含相关易管理性工具（例如 OnCommand Workflow Automation （ WFA ））的工作流中，以支持直接配置存储资源。

本文档介绍了与以下管理任务相关的常见工作流：

* 诊断和管理可用性问题
+
如果硬件故障或存储资源配置问题发生原因 在Dashboards/Overview页面中显示数据可用性事件、存储管理员可以通过嵌入的链接查看有关受影响存储资源的连接信息、查看故障排除建议以及将问题描述 解析分配给其他管理员。

* 配置和监控性能意外事件
+
OnCommand 管理员可以监控和管理所监控存储系统资源的性能。有关详细信息、请参见_Unified Manager集群性能管理工作流指南_。

* 诊断和管理卷容量问题
+
如果"Dashboards/Overview"页面中显示卷存储容量问题、则存储管理员可以通过嵌入的链接查看与受影响卷的存储容量相关的当前和历史趋势、查看故障排除建议并将问题描述 解决方案分配给其他管理员。

* 配置，监控和诊断保护关系问题
+
创建和配置保护关系后、存储管理员可以在Dashboards/Overview页面中查看与保护关系相关的潜在问题、并可通过嵌入的链接查看保护关系的当前状态、有关受影响关系的当前和历史保护作业成功信息、和故障排除建议、并将问题描述 解析分配给其他管理员。存储管理员还可以配置和管理SnapMirror和SnapVault 关系。

* 创建备份文件并从备份文件还原数据。
* 将存储对象与标注关联
+
通过将存储对象与标注关联，存储管理员可以筛选和查看与存储对象相关的事件，从而使存储管理员能够确定与事件相关的问题的优先级并解决这些问题。

* 向技术支持发送支持包
+
存储管理员可以使用维护控制台检索支持包并将其发送给技术支持。如果问题描述需要比 AutoSupport 消息更详细的诊断和故障排除信息，则必须将支持包发送给技术支持。

* 创建新报告以进行导入
+
存储管理员可以创建新的 `.rptdesign` 文件。这些报告可以导入到Unified Manager UI中、并在报告页面中查看。

+
报告页面上显示的报告提供了存储对象的当前状态。您可以根据当前使用情况做出重要决策、例如存储采购决策。这些报告提供了卷、磁盘架和聚合等存储对象的详细视图。

+
通过Unified Manager UI中的报告页面、您可以查看有关生成的报告的详细信息。您可以在报告页面中搜索特定报告、保存报告以及删除报告。您还可以从此页面计划、共享和导入报告。

* 创建、配置、监控和保护无限卷
+
在使用Workflow Automation工具为无限卷创建、配置和定义存储类之后、存储管理员可以使用Unified Manager监控该卷及其存储类、设置通知阈值并定义数据策略。存储管理员也可以使用WFA和Unified Manager为无限卷设置数据保护。


