---
permalink: health-checker/concept-types-of-snapmirror-protection.html 
sidebar: sidebar 
keywords:  
summary: 根据数据存储拓扑的部署情况，您可以使用 Unified Manager 配置多种类型的 SnapMirror 保护关系。所有形式的 SnapMirror 保护均可提供故障转移灾难恢复保护，但在性能，版本灵活性和多个备份副本保护方面提供不同的功能。 
---
= SnapMirror 保护的类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据数据存储拓扑的部署情况，您可以使用 Unified Manager 配置多种类型的 SnapMirror 保护关系。所有形式的 SnapMirror 保护均可提供故障转移灾难恢复保护，但在性能，版本灵活性和多个备份副本保护方面提供不同的功能。



== 传统 SnapMirror 异步保护关系

传统的 SnapMirror 异步保护可在源卷和目标卷之间提供块复制镜像保护。

在传统 SnapMirror 关系中，镜像操作的执行速度比在其他 SnapMirror 关系中更快，因为镜像操作基于块复制。但是，传统的 SnapMirror 保护要求目标卷与源卷在同一主要版本（例如 8.x 到 8.x 或 9.x 到 9.x ）中运行的 ONTAP 软件版本相同或更高的次要版本。



== 采用版本灵活复制的 SnapMirror 异步保护

采用版本灵活复制的SnapMirror异步保护可在源卷和目标卷之间提供逻辑复制镜像保护、即使这些卷运行的是不同版本的ONTAP 8.3或更高版本软件(例如8.3至8.3、8.3至9.1或9.0至8.3)也是如此。

在使用版本灵活复制的 SnapMirror 关系中，镜像操作的执行速度不如在传统 SnapMirror 关系中那样快。

由于执行速度较慢，具有版本灵活的复制保护的 SnapMirror 不适合在以下任一情况下实施：

* 源对象包含 1000 多万个要保护的文件。
* 受保护数据的恢复点目标为两小时或更短。（也就是说，目标位置必须始终包含可恢复的镜像数据，这些数据不超过源位置的数据两小时。）


在列出的任一情况下，都需要更快地执行基于块复制的默认 SnapMirror 保护。



== SnapMirror 异步保护，具有版本灵活的复制和备份选项

SnapMirror 异步保护具有版本灵活的复制和备份选项，可在源卷和目标卷之间提供镜像保护，并可在目标上存储镜像数据的多个副本。

存储管理员可以指定从源到目标镜像哪些 Snapshot 副本，还可以指定这些副本在目标上保留多长时间，即使这些副本在源上被删除也是如此。

在使用版本灵活的复制和备份选项的 SnapMirror 关系中，镜像操作的执行速度不如在传统 SnapMirror 关系中那样快。



== 采用严格同步的 SnapMirror 同步保护

采用 " `s` " 同步的 SnapMirror 同步保护可确保主卷和二级卷始终是彼此的真实副本。如果在尝试向二级卷写入数据时复制失败，则指向主卷的客户端 I/O 将中断。



== 采用常规同步的 SnapMirror 同步保护

采用 " `re同步` " 的 SnapMirror 同步保护不要求主卷和二级卷始终是彼此的真实副本，从而确保主卷的可用性。如果在尝试向二级卷写入数据时发生复制失败，则主卷和二级卷将不再同步，客户端 I/O 将继续向主卷写入。

[NOTE]
====
从运行状况/卷清单页面或运行状况/卷详细信息页面监控同步保护关系时、还原按钮和关系操作按钮不可用。

====