---
permalink: health-checker/reference-network-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: 通过网络配置菜单，您可以管理网络设置。如果 Unified Manager 用户界面不可用，则应使用此菜单。 
---
= 网络配置菜单
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过网络配置菜单，您可以管理网络设置。如果 Unified Manager 用户界面不可用，则应使用此菜单。

[NOTE]
====
如果 Unified Manager 安装在 Red Hat Enterprise Linux ， CentOS 或 Microsoft Windows 上，则此菜单不可用。

====
可以使用以下菜单选项。

* * 显示 IP 地址设置 *
+
显示虚拟设备的当前网络设置，包括 IP 地址，网络，广播地址，网络掩码，网关， 和 DNS 服务器。

* * 更改 IP 地址设置 *
+
用于更改虚拟设备的任何网络设置，包括 IP 地址，网络掩码，网关或 DNS 服务器。如果使用维护控制台将网络设置从 DHCP 切换到静态网络，则无法编辑主机名。要进行更改，必须选择 * 提交更改 * 。

* * 显示域名搜索设置 *
+
显示用于解析主机名的域名搜索列表。

* * 更改域名搜索设置 *
+
用于更改解析主机名时要搜索的域名。要进行更改，必须选择 * 提交更改 * 。

* * 显示静态路由 *
+
显示当前静态网络路由。

* * 更改静态路由 *
+
用于添加或删除静态网络路由。要进行更改，必须选择 * 提交更改 * 。

+
** * 添加路由 *
+
用于添加静态路由。

** * 删除路由 *
+
用于删除静态路由。

** * 返回 *
+
返回到 * 主菜单 * 。

** * 退出 *
+
退出维护控制台。



* * 禁用网络接口 *
+
禁用任何可用的网络接口。如果只有一个网络接口可用，则无法将其禁用。要进行更改，必须选择 * 提交更改 * 。

* * 启用网络接口 *
+
启用可用网络接口。要进行更改，必须选择 * 提交更改 * 。

* * 提交更改 *
+
应用对虚拟设备的网络设置所做的任何更改。您必须选择此选项才能实施所做的任何更改，否则不会发生更改。

* 对主机执行 Ping 操作 *
+
对目标主机执行 Ping 操作以确认 IP 地址更改或 DNS 配置。

* * 还原为默认设置 *
+
将所有设置重置为出厂默认值。要进行更改，必须选择 * 提交更改 * 。

* * 返回 *
+
返回到 * 主菜单 * 。

* * 退出 *
+
退出维护控制台。


