---
permalink: health-checker/reference-definitions-of-user-roles.html 
sidebar: sidebar 
keywords:  
summary: 维护用户或OnCommand 管理员会为每个用户分配一个角色。每个角色都包含某些特权。您可以在 Unified Manager 中执行的活动范围取决于分配给您的角色以及该角色包含的权限。 
---
= 用户角色的定义
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
维护用户或OnCommand 管理员会为每个用户分配一个角色。每个角色都包含某些特权。您可以在 Unified Manager 中执行的活动范围取决于分配给您的角色以及该角色包含的权限。

Unified Manager 包括以下预定义的用户角色：

* * 运算符 *
+
查看存储系统信息以及 Unified Manager 收集的其他数据，包括历史记录和容量趋势。通过此角色，存储操作员可以查看，分配，确认，解决和添加事件注释。

* * 存储管理员 *
+
在 Unified Manager 中配置存储管理操作。通过此角色，存储管理员可以配置阈值并创建警报和其他存储管理专用选项和策略。

* * OnCommand 管理员*
+
配置与存储管理无关的设置。此角色可用于管理用户，安全证书，数据库访问和管理选项，包括身份验证， SMTP ，网络和 AutoSupport 。

+
[NOTE]
====
如果Unified Manager安装在Linux系统上、则具有OnCommand 管理员角色的初始用户将自动命名为"`umadmin`"。

====
* * 集成架构 *
+
通过此角色，可以对 Unified Manager 数据库视图进行只读访问，以便将 Unified Manager 与 OnCommand Workflow Automation （ WFA ）集成。

* * 报告架构 *
+
通过此角色，可以直接从 Unified Manager 数据库对报告和其他数据库视图进行只读访问。可以查看的数据库包括：

+
** netapp_model_view
** netapp_performance
** ocum
** ocum_report
** ocum_report_BIRT
** OPM
** scalemonitor



