---
permalink: health-checker/task-resolving-a-flashcard-offline-condition.html 
sidebar: sidebar 
keywords:  
summary: 此工作流举例说明了如何解决闪存卡脱机问题。在这种情况下、您是监控信息板以检查可用性问题的管理员或操作员。您发现闪存卡脱机情况、希望确定可能的发生原因 并解决此问题。 
---
= 解决闪存卡脱机问题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此工作流举例说明了如何解决闪存卡脱机问题。在这种情况下、您是监控信息板以检查可用性问题的管理员或操作员。您发现闪存卡脱机情况、希望确定可能的发生原因 并解决此问题。



== 开始之前

您必须具有操作员、OnCommand 管理员或存储管理员角色。



== 关于此任务

Unified Manager Dashboards/Overview页面的Availability区域中显示的事件信息和链接可监控受监控集群上数据存储资源的整体可用性、从而可以诊断可能影响该可用性的特定事件。

在这种情况下、Dashboards/Overview页面会在其Availability Incidents部分显示事件Flash Cards Offline。如果闪存卡处于脱机状态、则存储数据的可用性会受到影响、因为安装了闪存卡的集群节点的性能会受到影响。您可以执行以下步骤来本地化并确定潜在问题：



== 步骤

. 在*未解决的意外事件和风险*部分的*可用性*面板中、单击为闪存卡脱机显示的超文本链接。
+
此时将显示可用性意外事件的事件详细信息页面。

. 在*事件*详细信息页面上、您可以查看发生原因 字段中显示的信息、并执行以下一项或多项任务：
+
** 将事件分配给管理员。 xref:task-assigning-events-to-specific-users.adoc[分配事件]
** 单击事件源(此处为脱机闪存卡所在的集群节点)以获取有关该节点的详细信息。 xref:task-performing-corrective-action-for-a-flashcard-offline.adoc[对闪存卡脱机执行更正操作]
** 确认事件。 xref:task-acknowledging-and-resolving-events.adoc[确认并解决事件]



