---
permalink: health-checker/task-creating-a-snapmirror-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用运行状况/卷详细信息页面创建SnapMirror关系、以便启用数据复制以实现保护。使用 SnapMirror 复制，您可以在源上发生数据丢失时从目标卷还原数据。 
---
= 通过运行状况/卷详细信息页面创建SnapMirror保护关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用运行状况/卷详细信息页面创建SnapMirror关系、以便启用数据复制以实现保护。使用 SnapMirror 复制，您可以在源上发生数据丢失时从目标卷还原数据。



== 开始之前

* 您必须具有OnCommand 管理员或存储管理员角色。
* 您必须已设置 Workflow Automation 。




== 关于此任务

在以下情况下，不会显示 * 保护 * 菜单：

* 如果 RBAC 设置不允许执行此操作：例如，您只有操作员权限
* 卷为FlexGroup 卷时
* 当卷 ID 未知时：例如，当您具有集群间关系且尚未发现目标集群时


您最多可以同时执行 10 个保护作业，而不会影响性能。如果同时运行 11 到 30 个作业，则可能会对性能产生一定影响。建议不要同时运行 30 个以上的作业。



== 步骤

. 在*运行状况/卷*详细信息页面的*保护*选项卡中、右键单击拓扑视图中要保护的卷的名称。
. 从菜单中选择 * 保护 * > * SnapMirror * 。
+
此时将显示配置保护对话框。

. 单击 * SnapMirror * 可查看 * SnapMirror * 选项卡并配置目标信息。
. 根据需要单击 * 高级 * 设置空间保证，然后单击 * 应用 * 。
. 完成 * 配置保护 * 对话框中的 * 目标信息 * 区域和 * 关系设置 * 区域。
. 单击 * 应用 * 。
+
此时将返回到运行状况/卷详细信息页面。

. 单击*运行状况/卷*详细信息页面顶部的保护配置作业链接。
+
作业的任务和详细信息将显示在保护/作业详细信息页面中。

. 在*保护/作业*详细信息页面中、单击*刷新*以更新与保护配置作业关联的任务列表和任务详细信息、并确定作业完成的时间。
. 作业任务完成后、单击浏览器上的*返回*以返回到*运行状况/卷*详细信息页面。
+
新关系将显示在运行状况/卷详细信息页面拓扑视图中。





== 结果

根据您在配置期间指定的目标 SVM 或在 " 高级 " 设置中启用的选项，生成的 SnapMirror 关系可能是以下几种可能的变体之一：

* 如果您指定的目标 SVM 在与源卷相同或更新版本的 ONTAP 下运行，则默认结果为基于块复制的 SnapMirror 关系。
* 如果您指定的目标SVM在与源卷相同或更新版本的ONTAP (8.3或更高版本)下运行、但您在"高级"设置中启用了版本灵活复制、则会生成具有版本灵活复制功能的SnapMirror关系。
* 如果您指定的目标SVM在ONTAP 8.3的早期版本或高于源卷的版本下运行、并且早期版本支持版本灵活复制、则会自动生成具有版本灵活复制功能的SnapMirror关系。

