---
permalink: health-checker/task-generating-and-uploading-a-support-bundle.html 
sidebar: sidebar 
keywords:  
summary: 您可以生成包含完整诊断信息的支持包、以便随后检索该支持包并将其发送给技术支持以获取故障排除帮助。由于某些类型的数据可能会占用大量集群资源或需要很长时间才能完成、因此您可以指定要在支持包中包含或排除的数据类型。 
---
= 生成支持包
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以生成包含完整诊断信息的支持包、以便随后检索该支持包并将其发送给技术支持以获取故障排除帮助。由于某些类型的数据可能会占用大量集群资源或需要很长时间才能完成、因此您可以指定要在支持包中包含或排除的数据类型。



== 开始之前

您必须以维护用户身份访问维护控制台。



== 关于此任务

Unified Manager 仅存储最近生成的两个支持包。旧的支持包将从系统中删除。

[NOTE]
====
在Windows系统上、使用命令 `supportbundle.bat` 不再支持生成支持包。

====


== 步骤

. 在维护控制台 * 主菜单 * 中，选择 * 支持 / 诊断 * 。
. 选择*生成支持包*。
. 选择或取消选择要在支持包中包含或排除的以下数据类型：
+
** * 数据库转储 *
+
MySQL Server 数据库的转储。

** * 堆转储 *
+
主要 Unified Manager 服务器进程状态的快照。默认情况下，此选项处于禁用状态，只有在客户支持请求时才应选择此选项。

** * 采集记录 *
+
记录 Unified Manager 与受监控集群之间的所有通信。



+
[NOTE]
====
如果取消选择所有数据类型，则仍会使用其他 Unified Manager 数据生成支持包。

====
. Type `g`、然后按Enter生成支持包。
+
由于生成支持包是一项内存密集型操作，因此系统会提示您确认此时确实要生成支持包。

. Type `y`、然后按Enter生成支持包。
+
如果此时不想生成支持包、请键入 `n`、然后按Enter键。

. 如果支持包中包含数据库转储文件、则系统会提示您指定要包含性能统计信息的时间段。包括性能统计信息可能需要大量时间和空间，因此您也可以在不包含性能统计信息的情况下转储数据库：
+
.. 以 YYMMDDD 格式输入开始日期。
+
例如、输入 `20170101` 适用于2017年1月1日。输入 ... `n` 如果不希望包括性能统计信息。

.. 输入要包括的统计信息天数，从上午 12 点开始指定的开始日期。
+
您可以输入 1 到 10 之间的数字。



+
如果要包括性能统计信息，则系统将显示收集性能统计信息的时间段。

. 选择*生成支持包*。
+
生成的支持包位于中 `/support` 目录。





== 完成后

生成支持包后、您可以使用SFTP客户端或UNIX或Linux命令行界面命令检索它。在 Windows 安装中，您可以使用远程桌面（ RDP ）检索支持包。

生成的支持包位于中 `/support` VMware系统上的目录、在中 `/opt/netapp/data/support/` 在Linux系统和中 `ProgramData\NetApp\OnCommandAppData\ocum\support` 在Windows系统上。
