---
permalink: config/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: 您可以将集群添加到OnCommand 统一管理器中、以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。 
---
= 添加集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将集群添加到OnCommand 统一管理器中、以便监控集群。这包括能够获取集群的运行状况，容量，性能和配置等集群信息，以便您可以发现并解决可能发生的任何问题。



== 开始之前

* 您必须具有OnCommand 管理员或存储管理员角色。
* 您必须具有以下信息：
+
** 主机名或集群管理 IP 地址
+
主机名是 Unified Manager 用于连接到集群的 FQDN 或简称。主机名必须解析为集群管理 IP 地址。

+
集群管理 IP 地址必须是管理 Storage Virtual Machine （ SVM ）的集群管理 LIF 。如果使用节点管理 LIF ，则操作将失败。

** Data ONTAP 管理员用户名和密码
+
此帐户必须具有 _admin_ 角色，并且应用程序访问权限设置为 _ontapi_ ， _ssh_ 和 _http_ 。

** 可以在集群上配置的协议类型(HTTP或HTTPS)以及用于连接到集群的端口号


+
[NOTE]
====
您可以使用 Unified Manager NAT IP 地址添加位于 NAT/ 防火墙后面的集群。任何已连接的 Workflow Automation 或 SnapProtect 系统也必须位于 NAT/ 防火墙后面， SnapProtect API 调用必须使用 NAT IP 地址来标识集群。

====
* Unified Manager FQDN必须能够对ONTAP 系统执行ping操作。
+
您可以使用以下ONTAP 命令验证此问题： `ping -node node_name -destination Unified_Manager_FQDN`。

* Unified Manager 服务器上必须有足够的空间。如果数据库目录中已占用的空间超过 90% ，则系统将阻止您向服务器添加集群。




== 关于此任务

对于 MetroCluster 配置，必须同时添加本地和远程集群，并且必须正确配置这些集群。

您可以通过两个 Unified Manager 实例监控一个集群，但前提是您已在集群上配置了另一个集群管理 LIF ，以便 Unified Manager 的每个实例都通过不同的 LIF 进行连接。



== 步骤

. 在左侧导航窗格中、单击*配置*>*集群数据源*。
. 在*配置/集群数据源*页面上、单击*添加*。
. 在*添加集群*对话框中、指定所需的值、例如集群的主机名或IP地址、用户名、密码、通信协议和端口号。
+
默认情况下、HTTPS协议和端口443处于选中状态。

+
您可以将集群管理 IP 地址从 IPv6 更改为 IPv4 或从 IPv4 更改为 IPv6 。下一个监控周期完成后，新 IP 地址将反映在集群网格和集群配置页面中。

. 单击 * 提交 * 。
. 如果选择 HTTPS ，请执行以下步骤：
+
.. 在 * 授权主机 * 对话框中，单击 * 查看证书 * 以查看有关集群的证书信息。
.. 单击 * 是 * 。
+
只有在首次添加集群时， Unified Manager 才会检查证书。Unified Manager 不会检查对 ONTAP 的每次 API 调用的证书。

+
如果证书已过期、则无法添加新集群。您必须先续订SSL证书、然后再添加集群。







== 结果

发现新集群的所有对象(大约15分钟)后、Unified Manager将开始收集前15天的历史性能数据。这些统计信息是使用数据连续性收集功能收集的。添加集群后，此功能会立即为您提供超过两周的集群性能信息。数据连续性收集周期完成后，系统会默认每五分钟收集一次实时集群性能数据。

[NOTE]
====
由于收集 15 天的性能数据需要占用大量 CPU 资源，因此建议您错开添加新集群的时间，以便不会在太多集群上同时运行数据连续性收集轮询。此外，如果您在数据连续性收集期间重新启动 Unified Manager ，则收集将暂停，并且性能图表中会显示缺少的时间范围。

====
[TIP]
====
如果您收到一条错误消息，指出无法添加集群，请检查是否存在以下问题：

* 如果两个系统上的时钟未同步，并且 Unified Manager HTTPS 证书开始日期晚于集群上的日期。您必须确保时钟使用 NTP 或类似服务进行同步。
* 如果集群已达到 EMS 通知目标的最大数量，则无法添加 Unified Manager 地址。默认情况下，只能在集群上定义 20 个 EMS 通知目标。


====